from typing import NamedTuple

from monsters.constants import MonsterSpecies, Species


class Skill(NamedTuple):
    """An action monsters can take."""

    name: str
    slug: str
    description: str
    monsters: list[Species]  # Monsters who can learn it naturally, without breeding.
    monster_level_requirement: int
    hp_requirement: int | None
    mp_requirement: int | None
    atk_requirement: int | None
    def_requirement: int | None
    agl_requirement: int | None
    int_requirement: int | None


class Skills:
    """All skills monsters can learn."""

    AHHH = Skill(
        name="Ahhh",
        slug="ahhh",
        description="Female foe: Stops action for 1 turn Male foe: Damage to one foe",
        monsters=[MonsterSpecies.LIPSY],
        monster_level_requirement=10,
        hp_requirement=None,
        mp_requirement=None,
        atk_requirement=60,
        def_requirement=None,
        agl_requirement=60,
        int_requirement=None,
    )

    ANTIDOTE = Skill(
        name="Antidote",
        slug="antidote",
        description="Cures poison to one ally",
        monsters=[
            MonsterSpecies.DRACKY,
            MonsterSpecies.FLORAMAN,
            MonsterSpecies.PIXY,
            MonsterSpecies.UNICORN,
        ],
        monster_level_requirement=5,
        hp_requirement=None,
        mp_requirement=21,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=20,
    )
    BANG = Skill(
        name="Bang",
        slug="bang",
        description="20-30 Explosion Damage to all foes",
        monsters=[
            MonsterSpecies.AKUBAR,
            MonsterSpecies.ARCDEMON,
            MonsterSpecies.BALZAK,
            MonsterSpecies.BARAMOS,
            MonsterSpecies.BONESLAVE,
            MonsterSpecies.GOATHORN,
            MonsterSpecies.HARGON,
            MonsterSpecies.METABBLE,
            MonsterSpecies.MIRUDRAAS1,
        ],
        monster_level_requirement=4,
        hp_requirement=None,
        mp_requirement=13,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=26,
    )
    BARRIER = Skill(
        name="Barrier",
        slug="barrier",
        description="Reduces Fire and Ice breath damage by 50% for the rest of the fight",
        monsters=[
            MonsterSpecies.AMBERWEED,
            MonsterSpecies.KINGSLIME,
            MonsterSpecies.MISTYWING,
            MonsterSpecies.WEEDBUG,
            MonsterSpecies.WINDMERGE,
        ],
        monster_level_requirement=18,
        hp_requirement=None,
        mp_requirement=76,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=70,
    )

    BAZOOCALL = Skill(
        name="BazooCall",
        slug="bazoocall",
        description="Summons a Bazoo that uses IceStorm,Hellblast,DeMagic to fight with",
        monsters=[],
        monster_level_requirement=35,
        hp_requirement=None,
        mp_requirement=160,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=180,
    )
    BEASTCUT = Skill(
        name="BeastCut",
        slug="beastcut",
        description="50% more Damage to beasts Normal against other foes",
        monsters=[
            MonsterSpecies.FLORAJAY,
            MonsterSpecies.GIANTWORM,
            MonsterSpecies.LIZARDMAN,
            MonsterSpecies.MADKNIGHT,
            MonsterSpecies.SLIMENITE,
        ],
        monster_level_requirement=12,
        hp_requirement=62,
        mp_requirement=None,
        atk_requirement=68,
        def_requirement=None,
        agl_requirement=72,
        int_requirement=None,
    )
    BEAT = Skill(
        name="Beat",
        slug="beat",
        description="Instant death to one foe",
        monsters=[
            MonsterSpecies.DEADNOBLE,
            MonsterSpecies.BLIZZARDY,
            MonsterSpecies.EVILPOT,
            MonsterSpecies.GOPHECADA,
            MonsterSpecies.METALY,
            MonsterSpecies.MIMIC,
            MonsterSpecies.MUDRON,
        ],
        monster_level_requirement=16,
        hp_requirement=None,
        mp_requirement=58,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=76,
    )
    BEDRAGON = Skill(
        name="BeDragon",
        slug="bedragon",
        description="Transforms you into a dragon for the rest of the fight with skills: SnowStorm,Scorching,DeMagic",
        monsters=[
            MonsterSpecies.CRESTPENT,
            MonsterSpecies.DRACOLORD1,
            MonsterSpecies.DRAKSLIME,
        ],
        monster_level_requirement=28,
        hp_requirement=None,
        mp_requirement=124,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=160,
    )
    BESERKER = Skill(
        name="Beserker",
        slug="beserker",
        description="Normal attack with increased Damage and defence at 0",
        monsters=[],
        monster_level_requirement=14,
        hp_requirement=98,
        mp_requirement=None,
        atk_requirement=84,
        def_requirement=84,
        agl_requirement=None,
        int_requirement=None,
    )
    BIATTACK = Skill(
        name="BiAttack",
        slug="biattack",
        description="Attacks twice one turn with 75% strength",
        monsters=[
            MonsterSpecies.JAMIRUS,
            MonsterSpecies.KINGLEO,
            MonsterSpecies.OROCHI,
            MonsterSpecies.PIZZARO,
            MonsterSpecies.ROBOSTER,
            MonsterSpecies.ROSEVINE,
            MonsterSpecies.SKELETOR,
        ],
        monster_level_requirement=19,
        hp_requirement=88,
        mp_requirement=None,
        atk_requirement=98,
        def_requirement=None,
        agl_requirement=112,
        int_requirement=None,
    )
    BIGBANG = Skill(
        name="BigBang",
        slug="bigbang",
        description="300-400 Explosion Damage to all foes",
        monsters=[
            MonsterSpecies.DEATHMORE1,
            MonsterSpecies.DEATHMORE3,
            MonsterSpecies.DIVINEGON,
            MonsterSpecies.GOLDGOLEM,
            MonsterSpecies.GOLDSLIME,
            MonsterSpecies.ZOMA,
        ],
        monster_level_requirement=36,
        hp_requirement=196,
        mp_requirement=196,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    BIGTRIP = Skill(
        name="BigTrip",
        slug="bigtrip",
        description="Trips all foes and stops their actions for 1 turn",
        monsters=[],
        monster_level_requirement=12,
        hp_requirement=66,
        mp_requirement=None,
        atk_requirement=63,
        def_requirement=None,
        agl_requirement=48,
        int_requirement=None,
    )
    BIRDBLOW = Skill(
        name="BirdBlow",
        slug="birdblow",
        description="50% more Damage to birds Normal against other foes",
        monsters=[
            MonsterSpecies.ARCDEMON,
            MonsterSpecies.BONESLAVE,
            MonsterSpecies.DURRAN,
            MonsterSpecies.MADGOPHER,
            MonsterSpecies.ORC,
            MonsterSpecies.SKELETOR,
        ],
        monster_level_requirement=12,
        hp_requirement=62,
        mp_requirement=None,
        atk_requirement=68,
        def_requirement=None,
        agl_requirement=72,
        int_requirement=None,
    )
    BLADED = Skill(
        name="BladeD",
        slug="bladed",
        description="Halves the Damage inflicted by the foe from physical attacks and reflects the Damage taken 50% of the time",
        monsters=[
            MonsterSpecies.ROSEVINE,
            MonsterSpecies.SLIMEBORG,
            MonsterSpecies.SWORDGON,
        ],
        monster_level_requirement=14,
        hp_requirement=98,
        mp_requirement=None,
        atk_requirement=84,
        def_requirement=84,
        agl_requirement=84,
        int_requirement=None,
    )

    BLAZE = Skill(
        name="Blaze",
        slug="blaze",
        description="12-15 Fire Damage to one foe",
        monsters=[
            MonsterSpecies.ONEEYECLOWN,
            MonsterSpecies.BOXSLIME,
            MonsterSpecies.DEMONITE,
            MonsterSpecies.FIREWEED,
            MonsterSpecies.GATEGUARD,
            MonsterSpecies.JAMIRUS,
            MonsterSpecies.LAVAMAN,
            MonsterSpecies.MADCANDLE,
            MonsterSpecies.METALY,
            MonsterSpecies.MIMIC,
            MonsterSpecies.MIRUDRAAS1,
            MonsterSpecies.SERVANT,
        ],
        monster_level_requirement=1,
        hp_requirement=None,
        mp_requirement=7,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=20,
    )

    BLAZEAIR = Skill(
        name="BlazeAir",
        slug="blazeair",
        description="32-48 Fire Damage to all foes",
        monsters=[],
        monster_level_requirement=10,
        hp_requirement=70,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    BLAZEMORE = Skill(
        name="Blazemore",
        slug="blazemore",
        description="70-90 Fire Damage to one foe",
        monsters=[],
        monster_level_requirement=13,
        hp_requirement=None,
        mp_requirement=46,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=64,
    )
    BLAZEMOST = Skill(
        name="Blazemost",
        slug="blazemost",
        description="180-200 Fire Damage to one foe",
        monsters=[],
        monster_level_requirement=28,
        hp_requirement=None,
        mp_requirement=112,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=146,
    )
    BLIZZARD = Skill(
        name="Blizzard",
        slug="blizzard",
        description="80-104 Ice Damage to all foes",
        monsters=[],
        monster_level_requirement=25,
        hp_requirement=None,
        mp_requirement=88,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=110,
    )
    BOLT = Skill(
        name="Bolt",
        slug="bolt",
        description="35-50 Lightning Damage to all foes",
        monsters=[
            MonsterSpecies.BALZAK,
            MonsterSpecies.DARKDRIUM,
            MonsterSpecies.METALKING,
            MonsterSpecies.MIRUDRAAS1,
            MonsterSpecies.WHITEKING,
        ],
        monster_level_requirement=6,
        hp_requirement=None,
        mp_requirement=20,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=35,
    )
    BOLTSLASH = Skill(
        name="BoltSlash",
        slug="boltslash",
        description="Normal attack based on Lightning resistance of the foe",
        monsters=[
            MonsterSpecies.ARCDEMON,
            MonsterSpecies.BONESLAVE,
            MonsterSpecies.COATOL,
            MonsterSpecies.EVILARMOR,
            MonsterSpecies.HORNBEET,
            MonsterSpecies.LANDOWL,
            MonsterSpecies.ROTRAVEN,
            MonsterSpecies.ZAPBIRD,
        ],
        monster_level_requirement=11,
        hp_requirement=77,
        mp_requirement=34,
        atk_requirement=66,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    BOOM = Skill(
        name="Boom",
        slug="boom",
        description="52-68 Explosion Damage to all foes",
        monsters=[],
        monster_level_requirement=14,
        hp_requirement=None,
        mp_requirement=50,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=68,
    )
    BOUNCE = Skill(
        name="Bounce",
        slug="bounce",
        description="Reflects spells back at opponents",
        monsters=[],
        monster_level_requirement=20,
        hp_requirement=None,
        mp_requirement=84,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=78,
    )
    BRANCHING = Skill(
        name="Branching",
        slug="branching",
        description="50% more damage to plants Normal against other foes",
        monsters=[
            MonsterSpecies.BULLBIRD,
            MonsterSpecies.DROLL,
            MonsterSpecies.MEDUSAEYE,
        ],
        monster_level_requirement=12,
        hp_requirement=62,
        mp_requirement=None,
        atk_requirement=68,
        def_requirement=None,
        agl_requirement=72,
        int_requirement=None,
    )
    CALLHELP = Skill(
        name="CallHelp",
        slug="callhelp",
        description="Calls randomly allies to help,level based Damage",
        monsters=[
            MonsterSpecies.ARMYANT,
            MonsterSpecies.ARMYCRAB,
            MonsterSpecies.BUTTERFLY,
            MonsterSpecies.FANGSLIME,
            MonsterSpecies.GOHOPPER,
            MonsterSpecies.GOOPI,
            MonsterSpecies.SNAILY,
            MonsterSpecies.GOPHECADA,
            MonsterSpecies.MINIDRAK,
            MonsterSpecies.MUMMY,
            MonsterSpecies.PILLOWRAT,
            MonsterSpecies.SNAPPER,
            MonsterSpecies.SPOTSLIME,
            MonsterSpecies.WILDAPE,
        ],
        monster_level_requirement=17,
        hp_requirement=84,
        mp_requirement=42,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=68,
        int_requirement=None,
    )
    CHANCE = Skill(
        name="Chance",
        slug="chance",
        description="Casts a random effect - Can be good or bad",
        monsters=[
            MonsterSpecies.GOLDSLIME,
            MonsterSpecies.WATABOU,
            MonsterSpecies.WHITEKING,
        ],
        monster_level_requirement=40,
        hp_requirement=None,
        mp_requirement=224,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=236,
    )
    CHARGEUP = Skill(
        name="ChargeUP",
        slug="chargeup",
        description="Additional Damage next turn.",
        monsters=[
            MonsterSpecies.ALMIRAJ,
            MonsterSpecies.BULLBIRD,
            MonsterSpecies.FANGSLIME,
            MonsterSpecies.GIGANTES,
            MonsterSpecies.GOHOPPER,
            MonsterSpecies.GOLEM,
            MonsterSpecies.HAMMERMAN,
            MonsterSpecies.MADGOPHER,
            MonsterSpecies.ONIONO,
            MonsterSpecies.SKULLROO,
        ],
        monster_level_requirement=14,
        hp_requirement=98,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=84,
        agl_requirement=None,
        int_requirement=None,
    )
    CLEANCUT = Skill(
        name="CleanCut",
        slug="cleancut",
        description="50% more damage to Materials Normal against other foes",
        monsters=[
            MonsterSpecies.EVILSEED,
            MonsterSpecies.GATEGUARD,
            MonsterSpecies.SPOTKING,
            MonsterSpecies.SWORDGON,
        ],
        monster_level_requirement=12,
        hp_requirement=62,
        mp_requirement=None,
        atk_requirement=68,
        def_requirement=None,
        agl_requirement=72,
        int_requirement=None,
    )
    COVER = Skill(
        name="Cover",
        slug="cover",
        description="Takes the attack against one ally",
        monsters=[
            MonsterSpecies.GRENDAL,
            MonsterSpecies.IRONTURT,
            MonsterSpecies.LAVAMAN,
            MonsterSpecies.STONEMAN,
        ],
        monster_level_requirement=5,
        hp_requirement=35,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=30,
        agl_requirement=30,
        int_requirement=None,
    )
    CURSE = Skill(
        name="Curse",
        slug="curse",
        description="Curses all foes,random effects",
        monsters=[
            MonsterSpecies.BUTTERFLY,
            MonsterSpecies.DUCKKITE,
            MonsterSpecies.FACETREE,
            MonsterSpecies.HERBMAN,
            MonsterSpecies.KINGCOBRA,
            MonsterSpecies.REAPER,
        ],
        monster_level_requirement=15,
        hp_requirement=None,
        mp_requirement=65,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=82,
        int_requirement=None,
    )
    CURSEOFF = Skill(
        name="CurseOff",
        slug="curseoff",
        description="Remove the curse from one ally",
        monsters=[
            MonsterSpecies.FLORAMAN,
            MonsterSpecies.DEADNITE,
            MonsterSpecies.TREEBOY,
            MonsterSpecies.WINDMERGE,
        ],
        monster_level_requirement=7,
        hp_requirement=None,
        mp_requirement=27,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=24,
    )
    DANCESHUT = Skill(
        name="DanceShut",
        slug="danceshut",
        description="Suspends all foes Dance attacks",
        monsters=[MonsterSpecies.HERBMAN],
        monster_level_requirement=16,
        hp_requirement=100,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=120,
        int_requirement=None,
    )
    DECHAOS = Skill(
        name="DeChaos",
        slug="dechaos",
        description="Cures confusion",
        monsters=[
            MonsterSpecies.COILBIRD,
            MonsterSpecies.EVILWAND,
            MonsterSpecies.FIREWEED,
            MonsterSpecies.SHADOW,
        ],
        monster_level_requirement=6,
        hp_requirement=None,
        mp_requirement=24,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=22,
    )
    DEFEAT = Skill(
        name="Defeat",
        slug="defeat",
        description="Instant death to all foes",
        monsters=[],
        monster_level_requirement=24,
        hp_requirement=None,
        mp_requirement=80,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=98,
    )
    DEFENCE = Skill(
        name="Defence",
        slug="defence",
        description="Decreases defense of all foes by 50%",
        monsters=[],
        monster_level_requirement=8,
        hp_requirement=None,
        mp_requirement=36,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=32,
    )
    DEMAGIC = Skill(
        name="DeMagic",
        slug="demagic",
        description="Dispels magic effects on all foes (Upper,Speed,Barrier,MagicWall)",
        monsters=[
            MonsterSpecies.DEATHMORE3,
            MonsterSpecies.ESTERK,
            MonsterSpecies.MIRUDRAAS2,
            MonsterSpecies.ZOMA,
        ],
        monster_level_requirement=20,
        hp_requirement=None,
        mp_requirement=100,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=140,
    )
    DEVILCUT = Skill(
        name="DevilCut",
        slug="devilcut",
        description="50% more Damage to Devils Normal against other foes",
        monsters=[
            MonsterSpecies.HORNBEET,
            MonsterSpecies.RAYBURN,
            MonsterSpecies.REAPER,
            MonsterSpecies.SABREMAN,
        ],
        monster_level_requirement=12,
        hp_requirement=64,
        mp_requirement=None,
        atk_requirement=58,
        def_requirement=None,
        agl_requirement=62,
        int_requirement=None,
    )
    DIAGOCALL = Skill(
        name="DiagoCall",
        slug="diagocall",
        description="Summons a Diago that uses TwinHits,SickLick,Scorching to fight with",
        monsters=[],
        monster_level_requirement=25,
        hp_requirement=None,
        mp_requirement=100,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=120,
    )
    DODGE = Skill(
        name="Dodge",
        slug="dodge",
        description="Changes the target of a physical attack against the caster 20% Chance target is an ally, 80% Chance target is an enemy",
        monsters=[
            MonsterSpecies.BIGROOST,
            MonsterSpecies.DRAGONKID,
            MonsterSpecies.GIANTSLUG,
            MonsterSpecies.GOOPI,
        ],
        monster_level_requirement=18,
        hp_requirement=126,
        mp_requirement=None,
        atk_requirement=108,
        def_requirement=108,
        agl_requirement=108,
        int_requirement=None,
    )
    DRAKSLASH = Skill(
        name="DrakSlash",
        slug="drakslash",
        description="50% more damage against Dragons Normal against other foes",
        monsters=[
            MonsterSpecies.FLORAJAY,
            MonsterSpecies.GIANTWORM,
            MonsterSpecies.LIZARDMAN,
            MonsterSpecies.MADKNIGHT,
            MonsterSpecies.SLIMENITE,
        ],
        monster_level_requirement=12,
        hp_requirement=68,
        mp_requirement=None,
        atk_requirement=72,
        def_requirement=None,
        agl_requirement=62,
        int_requirement=None,
    )
    EERIELITE = Skill(
        name="EerieLite",
        slug="eerielite",
        description="Lowers magic resistance for all foes",
        monsters=[
            MonsterSpecies.BABBLE,
            MonsterSpecies.HORK,
            MonsterSpecies.MISTYWING,
            MonsterSpecies.REAPER,
        ],
        monster_level_requirement=14,
        hp_requirement=None,
        mp_requirement=65,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=84,
        int_requirement=None,
    )
    EVILSLASH = Skill(
        name="EvilSlash",
        slug="evilslash",
        description="Physical Damage based on the attack of user",
        monsters=[
            MonsterSpecies.ARMORPION,
            MonsterSpecies.BATTLEREX,
            MonsterSpecies.COATOL,
            MonsterSpecies.GIGANTES,
            MonsterSpecies.HAMMERMAN,
            MonsterSpecies.LIZARDMAN,
            MonsterSpecies.MADDRAGON,
            MonsterSpecies.MUMMY,
            MonsterSpecies.ROGUENITE,
        ],
        monster_level_requirement=15,
        hp_requirement=106,
        mp_requirement=None,
        atk_requirement=90,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    EXPLODET = Skill(
        name="Explodet",
        slug="explodet",
        description="130-140 Explosion Damage to all foes",
        monsters=[],
        monster_level_requirement=29,
        hp_requirement=None,
        mp_requirement=120,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=158,
    )
    FAREWELL = Skill(
        name="Farewell",
        slug="farewell",
        description="Revives all allies and causes instant death to the caster",
        monsters=[
            MonsterSpecies.BOMBCRAG,
            MonsterSpecies.DIGSTER,
            MonsterSpecies.GASGON,
            MonsterSpecies.WINGTREE,
        ],
        monster_level_requirement=32,
        hp_requirement=None,
        mp_requirement=188,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=176,
    )
    FIREAIR = Skill(
        name="FireAir",
        slug="fireair",
        description="14-22 Fire Damage to all foes",
        monsters=[
            MonsterSpecies.BATTLEREX,
            MonsterSpecies.DARKDRIUM,
            MonsterSpecies.DEATHMORE2,
            MonsterSpecies.DRACOLORD2,
            MonsterSpecies.DRAGON,
            MonsterSpecies.DRAGONKID,
            MonsterSpecies.DRAKSLIME,
            MonsterSpecies.GISMO,
            MonsterSpecies.LAVAMAN,
            MonsterSpecies.LIZARDFLY,
            MonsterSpecies.MIRUDRAAS2,
            MonsterSpecies.MUDOU,
            MonsterSpecies.NITEWHIP,
            MonsterSpecies.OROCHI,
            MonsterSpecies.PHOENIX,
            MonsterSpecies.PIZZARO,
            MonsterSpecies.SIDOH,
            MonsterSpecies.SKYDRAGON,
            MonsterSpecies.STAGBUG,
        ],
        monster_level_requirement=3,
        hp_requirement=21,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    FIREBAL = Skill(
        name="Firebal",
        slug="firebal",
        description="16-24 Fire Damage to all foes",
        monsters=[
            MonsterSpecies.ONEEYECLOWN,
            MonsterSpecies.AGDEVIL,
            MonsterSpecies.DRACOLORD1,
            MonsterSpecies.EVILBEAST,
            MonsterSpecies.EYEDER,
            MonsterSpecies.FLORAMAN,
            MonsterSpecies.GOATEGON,
            MonsterSpecies.GREMLIN,
            MonsterSpecies.HARGON,
            MonsterSpecies.JEWELBAG,
            MonsterSpecies.KINGLEO,
            MonsterSpecies.LIZARDFLY,
            MonsterSpecies.MADCONDOR,
            MonsterSpecies.METABBLE,
            MonsterSpecies.PTERANOD,
            MonsterSpecies.SLIME,
        ],
        monster_level_requirement=3,
        hp_requirement=None,
        mp_requirement=11,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=23,
    )
    FIREBANE = Skill(
        name="Firebane",
        slug="firebane",
        description="30-42 Fire Damage to all foes",
        monsters=[],
        monster_level_requirement=10,
        hp_requirement=None,
        mp_requirement=34,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=52,
    )
    FIREBOLT = Skill(
        name="Firebolt",
        slug="firebolt",
        description="88-112 Fire Damage to all foes",
        monsters=[],
        monster_level_requirement=26,
        hp_requirement=None,
        mp_requirement=96,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=122,
    )
    FIRESLASH = Skill(
        name="FireSlash",
        slug="fireslash",
        description="Normal attack based on Fire resistance of the foe",
        monsters=[
            MonsterSpecies.CENTASAUR,
            MonsterSpecies.DEMONITE,
            MonsterSpecies.DRAGON,
            MonsterSpecies.EVILARMOR,
            MonsterSpecies.GRENDAL,
            MonsterSpecies.OROCHI,
            MonsterSpecies.SKULRIDER,
        ],
        monster_level_requirement=11,
        hp_requirement=77,
        mp_requirement=34,
        atk_requirement=66,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    FOCUS = Skill(
        name="Focus",
        slug="focus",
        description="Two attacks next turn",
        monsters=[
            MonsterSpecies.AKUBAR,
            MonsterSpecies.DEATHMORE3,
            MonsterSpecies.HERBMAN,
            MonsterSpecies.SERVANT,
        ],
        monster_level_requirement=18,
        hp_requirement=126,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=108,
        agl_requirement=108,
        int_requirement=None,
    )
    FRIGIDAIR = Skill(
        name="FrigidAir",
        slug="frigidair",
        description="16-24 Ice Damage to all foes",
        monsters=[
            MonsterSpecies.AKUBAR,
            MonsterSpecies.BIGEYE,
            MonsterSpecies.BLIZZARDY,
            MonsterSpecies.DARKDRIUM,
            MonsterSpecies.DEMONITE,
            MonsterSpecies.DIVINEGON,
            MonsterSpecies.EVILBEAST,
            MonsterSpecies.EVILWAND,
            MonsterSpecies.GISMO,
            MonsterSpecies.GREATDRAK,
            MonsterSpecies.ICEMAN,
            MonsterSpecies.KINGLEO,
            MonsterSpecies.MUDOU,
            MonsterSpecies.SHADOW,
            MonsterSpecies.SIDOH,
            MonsterSpecies.SKULLGON,
            MonsterSpecies.WYVERN,
            MonsterSpecies.ZOMA,
        ],
        monster_level_requirement=3,
        hp_requirement=21,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    GIGASLASH = Skill(
        name="GigaSlash",
        slug="gigaslash",
        description="350-410 Damage to one foe",
        monsters=[
            MonsterSpecies.ESTERK,
            MonsterSpecies.LIZARDMAN,
            MonsterSpecies.MADKNIGHT,
        ],
        monster_level_requirement=33,
        hp_requirement=231,
        mp_requirement=164,
        atk_requirement=198,
        def_requirement=None,
        agl_requirement=198,
        int_requirement=None,
    )
    GUARDIAN = Skill(
        name="Guardian",
        slug="guardian",
        description="Takes all attacks for one turn",
        monsters=[],
        monster_level_requirement=12,
        hp_requirement=84,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=72,
        agl_requirement=72,
        int_requirement=None,
    )
    HEAL = Skill(
        name="Heal",
        slug="heal",
        description="Heals 30-40 Hp for one ally",
        monsters=[
            MonsterSpecies.BIGEYE,
            MonsterSpecies.DEADNITE,
            MonsterSpecies.EYEDER,
            MonsterSpecies.GREMLIN,
            MonsterSpecies.HEALER,
            MonsterSpecies.KINGSLIME,
            MonsterSpecies.MUDRON,
            MonsterSpecies.ROGUENITE,
        ],
        monster_level_requirement=1,
        hp_requirement=None,
        mp_requirement=7,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=6,
    )
    HEALALL = Skill(
        name="HealAll",
        slug="healall",
        description="Heals all Hp for one ally",
        monsters=[],
        monster_level_requirement=16,
        hp_requirement=None,
        mp_requirement=82,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=80,
    )
    HEALMORE = Skill(
        name="HealMore",
        slug="healmore",
        description="Heals 75-90 Hp for one ally",
        monsters=[],
        monster_level_requirement=10,
        hp_requirement=None,
        mp_requirement=52,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=48,
    )
    HEALUS = Skill(
        name="HealUs",
        slug="healus",
        description="Heals 90-120 Hp for all allies",
        monsters=[
            MonsterSpecies.DEADNOBLE,
            MonsterSpecies.HEALER,
            MonsterSpecies.LIONEX,
            MonsterSpecies.MADCONDOR,
        ],
        monster_level_requirement=20,
        hp_requirement=None,
        mp_requirement=140,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=120,
    )
    HEALUSALL = Skill(
        name="HealUsAll",
        slug="healusall",
        description="Heals all Hp for all allies",
        monsters=[],
        monster_level_requirement=28,
        hp_requirement=None,
        mp_requirement=196,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=160,
    )
    HELLBLAST = Skill(
        name="HellBlast",
        slug="hellblast",
        description="210-290 Lightning Damage to all foes",
        monsters=[
            MonsterSpecies.BARAMOS,
            MonsterSpecies.DEATHMORE1,
            MonsterSpecies.METALKING,
            MonsterSpecies.PIZZARO,
            MonsterSpecies.SIDOH,
            MonsterSpecies.ZAPBIRD,
        ],
        monster_level_requirement=34,
        hp_requirement=184,
        mp_requirement=184,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    HIGHJUMP = Skill(
        name="HighJump",
        slug="highjump",
        description="Jump into the Air and attack next turn with increased attack",
        monsters=[
            MonsterSpecies.CACTIBALL,
            MonsterSpecies.MADRAVEN,
            MonsterSpecies.ROCKSLIME,
            MonsterSpecies.SPIKYBOY,
            MonsterSpecies.WINGSNAKE,
        ],
        monster_level_requirement=20,
        hp_requirement=140,
        mp_requirement=None,
        atk_requirement=120,
        def_requirement=None,
        agl_requirement=120,
        int_requirement=None,
    )
    HUSTLE = Skill(
        name="Hustle",
        slug="hustle",
        description="Heals 70-80 Hp for all allies",
        monsters=[
            MonsterSpecies.FUNKYBIRD,
            MonsterSpecies.MUDDOLL,
            MonsterSpecies.SUPERTEN,
        ],
        monster_level_requirement=18,
        hp_requirement=114,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=130,
        int_requirement=None,
    )
    ICEAIR = Skill(
        name="IceAir",
        slug="iceair",
        description="42-54 Ice Damage to all foes",
        monsters=[],
        monster_level_requirement=10,
        hp_requirement=70,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    ICEBOLT = Skill(
        name="IceBolt",
        slug="icebolt",
        description="25-35 Ice Damage to all foes",
        monsters=[
            MonsterSpecies.ONEEYECLOWN,
            MonsterSpecies.BIGEYE,
            MonsterSpecies.GOATHORN,
            MonsterSpecies.ICEMAN,
            MonsterSpecies.METALY,
            MonsterSpecies.MOMMONJA,
            MonsterSpecies.SERVANT,
            MonsterSpecies.SNAILY,
            MonsterSpecies.TREEBOY,
            MonsterSpecies.WINDBEAST,
            MonsterSpecies.YETI,
        ],
        monster_level_requirement=5,
        hp_requirement=None,
        mp_requirement=16,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=30,
    )
    ICESLASH = Skill(
        name="IceSlash",
        slug="iceslash",
        description="Normal attack based on Ice resistance of the foe",
        monsters=[
            MonsterSpecies.BLIZZARDY,
            MonsterSpecies.GREATDRAK,
            MonsterSpecies.SKULLGON,
            MonsterSpecies.TAILEATER,
            MonsterSpecies.YETI,
        ],
        monster_level_requirement=11,
        hp_requirement=77,
        mp_requirement=34,
        atk_requirement=66,
        def_requirement=None,
        agl_requirement=60,
        int_requirement=None,
    )
    ICESTORM = Skill(
        name="IceStorm",
        slug="icestorm",
        description="82-112 Ice Damage to all foes",
        monsters=[],
        monster_level_requirement=20,
        hp_requirement=140,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    IMITATE = Skill(
        name="Imitate",
        slug="imitate",
        description="Copy and return every skill cast on Caster for 1 turn",
        monsters=[
            MonsterSpecies.COPYCAT,
            MonsterSpecies.SPOTSLIME,
            MonsterSpecies.SUPERTEN,
            MonsterSpecies.WATABOU,
        ],
        monster_level_requirement=21,
        hp_requirement=None,
        mp_requirement=147,
        atk_requirement=126,
        def_requirement=126,
        agl_requirement=126,
        int_requirement=None,
    )
    INCREASE = Skill(
        name="Increase",
        slug="increase",
        description="Increases defence for all allies by 50%",
        monsters=[],
        monster_level_requirement=6,
        hp_requirement=None,
        mp_requirement=27,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=12,
    )
    INFERMORE = Skill(
        name="Infermore",
        slug="infermore",
        description="25-55 Air Damage to all foes",
        monsters=[],
        monster_level_requirement=11,
        hp_requirement=None,
        mp_requirement=38,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=56,
    )
    INFERMOST = Skill(
        name="Infermost",
        slug="infermost",
        description="80-180 Air Damage to all foes",
        monsters=[],
        monster_level_requirement=27,
        hp_requirement=None,
        mp_requirement=104,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=134,
    )
    INFERNOS = Skill(
        name="Infernos",
        slug="infernos",
        description="8-24 Air Damage to all foes",
        monsters=[
            MonsterSpecies.ANDREAL,
            MonsterSpecies.FACER,
            MonsterSpecies.GOATHORN,
            MonsterSpecies.GULPPLE,
            MonsterSpecies.LANDOWL,
            MonsterSpecies.LIONEX,
            MonsterSpecies.MADPECKER,
            MonsterSpecies.WHITEKING,
            MonsterSpecies.WINDBEAST,
            MonsterSpecies.WINDMERGE,
        ],
        monster_level_requirement=2,
        hp_requirement=None,
        mp_requirement=10,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=21,
    )
    IRONIZE = Skill(
        name="Ironize",
        slug="ironize",
        description="All allies become invulernable for 3 turns [but can't move]",
        monsters=[
            MonsterSpecies.DARKCRAB,
            MonsterSpecies.EVILBEAST,
            MonsterSpecies.EYEBALL,
            MonsterSpecies.METALKING,
            MonsterSpecies.TORTRAGON,
            MonsterSpecies.WHIPBIRD,
        ],
        monster_level_requirement=15,
        hp_requirement=None,
        mp_requirement=62,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=58,
    )
    K_O_DANCE = Skill(
        name="K.O.Dance",
        slug="k.o.dance",
        description="Instant death to all foes",
        monsters=[
            MonsterSpecies.DANCEVEGI,
            MonsterSpecies.KINGCOBRA,
            MonsterSpecies.SHADOW,
            MonsterSpecies.SUPERTEN,
        ],
        monster_level_requirement=20,
        hp_requirement=140,
        mp_requirement=72,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=120,
        int_requirement=None,
    )
    KAMIKAZE = Skill(
        name="Kamikaze",
        slug="kamikaze",
        description="Reduces foe's Hp to 1 and attacker's Hp to 1 if successful",
        monsters=[
            MonsterSpecies.ARMYANT,
            MonsterSpecies.HAMMERMAN,
            MonsterSpecies.ROTRAVEN,
            MonsterSpecies.SPIKEROUS,
        ],
        monster_level_requirement=18,
        hp_requirement=126,
        mp_requirement=None,
        atk_requirement=108,
        def_requirement=108,
        agl_requirement=None,
        int_requirement=None,
    )
    LEGSWEEP = Skill(
        name="LegSweep",
        slug="legsweep",
        description="Trips one foe and stops his action for 1 turn",
        monsters=[
            MonsterSpecies.GOOPI,
            MonsterSpecies.GRIZZLY,
            MonsterSpecies.MADCAT,
            MonsterSpecies.SKULRIDER,
            MonsterSpecies.SLABBIT,
            MonsterSpecies.STAGBUG,
            MonsterSpecies.WILDAPE,
        ],
        monster_level_requirement=6,
        hp_requirement=32,
        mp_requirement=None,
        atk_requirement=31,
        def_requirement=None,
        agl_requirement=48,
        int_requirement=None,
    )
    LIFEDANCE = Skill(
        name="LifeDance",
        slug="lifedance",
        description="Revives all allies and causes instant death to the caster",
        monsters=[MonsterSpecies.FUNKYBIRD],
        monster_level_requirement=30,
        hp_requirement=210,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=180,
        int_requirement=None,
    )
    LIFESONG = Skill(
        name="LifeSong",
        slug="lifesong",
        description="Revives all allies (requires 2 turns and can fail)",
        monsters=[MonsterSpecies.FACER, MonsterSpecies.FLORAJAY],
        monster_level_requirement=27,
        hp_requirement=198,
        mp_requirement=94,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=145,
        int_requirement=None,
    )
    LIGHTNING = Skill(
        name="Lightning",
        slug="lightning",
        description="40-60 Lightning Damage to all foes",
        monsters=[
            MonsterSpecies.NITEWHIP,
            MonsterSpecies.ROTRAVEN,
            MonsterSpecies.SLIMEBORG,
            MonsterSpecies.TORTRAGON,
            MonsterSpecies.ZAPBIRD,
        ],
        monster_level_requirement=10,
        hp_requirement=65,
        mp_requirement=None,
        atk_requirement=90,
        def_requirement=None,
        agl_requirement=52,
        int_requirement=None,
    )
    LUREDANCE = Skill(
        name="LureDance",
        slug="luredance",
        description="Stops actions of all foes for one turn by inviting them to dance",
        monsters=[
            MonsterSpecies.DANCEVEGI,
            MonsterSpecies.MADDRAGON,
            MonsterSpecies.MADGOOSE,
            MonsterSpecies.MOMMONJA,
        ],
        monster_level_requirement=14,
        hp_requirement=84,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=98,
        int_requirement=None,
    )
    LUSHLICKS = Skill(
        name="LushLicks",
        slug="lushlicks",
        description="Stops the action of one foe for one turn",
        monsters=[
            MonsterSpecies.ANTEATER,
            MonsterSpecies.FAIRYDRAK,
            MonsterSpecies.GIANTSLUG,
            MonsterSpecies.HORK,
            MonsterSpecies.LIPSY,
            MonsterSpecies.POISONGON,
            MonsterSpecies.SPOOKY,
            MonsterSpecies.SPOTSLIME,
            MonsterSpecies.TONGUELLA,
        ],
        monster_level_requirement=7,
        hp_requirement=55,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=67,
        int_requirement=None,
    )
    MAGICBACK = Skill(
        name="MagicBack",
        slug="magicback",
        description="Reflects back a skill once to the foes",
        monsters=[
            MonsterSpecies.EYEBALL,
            MonsterSpecies.GOPHECADA,
            MonsterSpecies.IRONTURT,
            MonsterSpecies.MADMIRROR,
            MonsterSpecies.PUTREPUP,
            MonsterSpecies.TORTRAGON,
        ],
        monster_level_requirement=16,
        hp_requirement=None,
        mp_requirement=68,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=62,
    )
    MAGICWALL = Skill(
        name="MagicWall",
        slug="magicwall",
        description="Increases resistance against foes' skills",
        monsters=[
            MonsterSpecies.AMBERWEED,
            MonsterSpecies.DARKCRAB,
            MonsterSpecies.WEEDBUG,
        ],
        monster_level_requirement=19,
        hp_requirement=None,
        mp_requirement=80,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=74,
    )
    MAPMAGIC = Skill(
        name="MapMagic",
        slug="mapmagic",
        description="Reveals whole map of current level inside a gate",
        monsters=[
            MonsterSpecies.BEANMAN,
            MonsterSpecies.EVILWAND,
            MonsterSpecies.EYEDER,
            MonsterSpecies.MADMIRROR,
        ],
        monster_level_requirement=10,
        hp_requirement=None,
        mp_requirement=40,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=34,
    )
    MASSACRE = Skill(
        name="Massacre",
        slug="massacre",
        description="Inflicts 95-105% of the caster's attack against one random monster",
        monsters=[
            MonsterSpecies.DRACOLORD2,
            MonsterSpecies.EVILPOT,
            MonsterSpecies.GULPBEAST,
            MonsterSpecies.MADDRAGON,
            MonsterSpecies.MADKNIGHT,
            MonsterSpecies.METALDRAK,
            MonsterSpecies.OGRE,
        ],
        monster_level_requirement=12,
        hp_requirement=84,
        mp_requirement=None,
        atk_requirement=72,
        def_requirement=None,
        agl_requirement=72,
        int_requirement=None,
    )
    MEDITATE = Skill(
        name="Meditate",
        slug="meditate",
        description="Heals 500 Hp to the caster in combat only",
        monsters=[
            MonsterSpecies.BOMBCRAG,
            MonsterSpecies.DIVINEGON,
            MonsterSpecies.DRACOLORD1,
            MonsterSpecies.STONEMAN,
        ],
        monster_level_requirement=26,
        hp_requirement=182,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=156,
        agl_requirement=None,
        int_requirement=None,
    )
    MEGAMAGIC = Skill(
        name="MegaMagic",
        slug="megamagic",
        description="Highest Damage spell to all foes",
        monsters=[MonsterSpecies.RAINHAWK, MonsterSpecies.SLIME],
        monster_level_requirement=38,
        hp_requirement=None,
        mp_requirement=210,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=224,
    )
    METALCUT = Skill(
        name="MetalCut",
        slug="metalcut",
        description="50% more Damage against Metal monsters, Normal against other foes",
        monsters=[
            MonsterSpecies.ANTEATER,
            MonsterSpecies.ARMYCRAB,
            MonsterSpecies.BATTLEREX,
            MonsterSpecies.DARKEYE,
            MonsterSpecies.OGRE,
            MonsterSpecies.ROGUENITE,
        ],
        monster_level_requirement=12,
        hp_requirement=68,
        mp_requirement=None,
        atk_requirement=72,
        def_requirement=None,
        agl_requirement=62,
        int_requirement=None,
    )
    MOUTHSHUT = Skill(
        name="MouthShut",
        slug="mouthshut",
        description="Suspends one foe's breath attack",
        monsters=[
            MonsterSpecies.MOMMONJA,
            MonsterSpecies.SPOOKY,
            MonsterSpecies.SPOTKING,
            MonsterSpecies.TOADSTOOL,
        ],
        monster_level_requirement=17,
        hp_requirement=120,
        mp_requirement=None,
        atk_requirement=100,
        def_requirement=None,
        agl_requirement=140,
        int_requirement=None,
    )
    MULTICUT = Skill(
        name="MultiCut",
        slug="multicut",
        description="180-210 Cut Damage to all foes",
        monsters=[
            MonsterSpecies.BALZAK,
            MonsterSpecies.SKYDRAGON,
            MonsterSpecies.MADCONDOR,
        ],
        monster_level_requirement=28,
        hp_requirement=154,
        mp_requirement=140,
        atk_requirement=168,
        def_requirement=None,
        agl_requirement=168,
        int_requirement=None,
    )
    NAPATTACK = Skill(
        name="NapAttack",
        slug="napattack",
        description="Normal attack and tries to sleep the foe",
        monsters=[
            MonsterSpecies.ARMYANT,
            MonsterSpecies.GULPPLE,
            MonsterSpecies.LIPSY,
            MonsterSpecies.SPOTKING,
            MonsterSpecies.TOADSTOOL,
            MonsterSpecies.TONGUELLA,
        ],
        monster_level_requirement=7,
        hp_requirement=49,
        mp_requirement=None,
        atk_requirement=42,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    NUMBOFF = Skill(
        name="NumbOff",
        slug="numboff",
        description="Cures paralysis or wakes an ally",
        monsters=[
            MonsterSpecies.COILBIRD,
            MonsterSpecies.MADPLANT,
            MonsterSpecies.SNAILY,
        ],
        monster_level_requirement=8,
        hp_requirement=None,
        mp_requirement=30,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=26,
    )
    ODDDANCE = Skill(
        name="OddDance",
        slug="odddance",
        description="Lowers one foe's Mp depending on the caster's level",
        monsters=[
            MonsterSpecies.CACTIBALL,
            MonsterSpecies.CATFLY,
            MonsterSpecies.COPYCAT,
            MonsterSpecies.FACETREE,
            MonsterSpecies.GIANTWORM,
            MonsterSpecies.MADGOOSE,
            MonsterSpecies.MUDDOLL,
        ],
        monster_level_requirement=10,
        hp_requirement=54,
        mp_requirement=27,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=63,
        int_requirement=None,
    )
    PALSYAIR = Skill(
        name="PalsyAir",
        slug="palsyair",
        description="Breathes Air to paralyze all foes",
        monsters=[
            MonsterSpecies.CHAMELGON,
            MonsterSpecies.DARKEYE,
            MonsterSpecies.FIREWEED,
            MonsterSpecies.SACCER,
        ],
        monster_level_requirement=16,
        hp_requirement=112,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=96,
    )
    PANICALL = Skill(
        name="PanicAll",
        slug="panicall",
        description="Confuses all foes",
        monsters=[
            MonsterSpecies.CHAMELGON,
            MonsterSpecies.DUCKKITE,
            MonsterSpecies.JEWELBAG,
            MonsterSpecies.MADGOOSE,
            MonsterSpecies.VOODOLL,
        ],
        monster_level_requirement=12,
        hp_requirement=None,
        mp_requirement=56,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=49,
    )
    PANIDANCE = Skill(
        name="PaniDance",
        slug="panidance",
        description="Confuses or paralyzes all foes",
        monsters=[MonsterSpecies.FUNKYBIRD, MonsterSpecies.SKULLROO],
        monster_level_requirement=13,
        hp_requirement=74,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=78,
        int_requirement=None,
    )
    PARALYZE = Skill(
        name="Paralyze",
        slug="paralyze",
        description="Normal attack and tries to paralyze the foe",
        monsters=[
            MonsterSpecies.CACTIBALL,
            MonsterSpecies.CHAMELGON,
            MonsterSpecies.EVILSEED,
            MonsterSpecies.GIANTMOTH,
            MonsterSpecies.MADHORNET,
            MonsterSpecies.MUMMY,
            MonsterSpecies.SABREMAN,
            MonsterSpecies.TREESLIME,
        ],
        monster_level_requirement=9,
        hp_requirement=63,
        mp_requirement=None,
        atk_requirement=54,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    POISONAIR = Skill(
        name="PoisonAir",
        slug="poisonair",
        description="Breathes Air to poison all foes",
        monsters=[],
        monster_level_requirement=14,
        hp_requirement=98,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=84,
    )
    POISONGAS = Skill(
        name="PoisonGas",
        slug="poisongas",
        description="Breathes gas to poison all foes",
        monsters=[
            MonsterSpecies.ANDREAL,
            MonsterSpecies.CATAPILA,
            MonsterSpecies.HORK,
            MonsterSpecies.MUDOU,
            MonsterSpecies.POISONGON,
            MonsterSpecies.TAILEATER,
            MonsterSpecies.WINGSNAKE,
        ],
        monster_level_requirement=9,
        hp_requirement=63,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=54,
    )
    POISONHIT = Skill(
        name="PoisonHit",
        slug="poisonhit",
        description="Normal attack and tries to poison the foe",
        monsters=[
            MonsterSpecies.BABBLE,
            MonsterSpecies.CRESTPENT,
            MonsterSpecies.KINGCOBRA,
            MonsterSpecies.MADHORNET,
            MonsterSpecies.POISONGON,
            MonsterSpecies.RAYBURN,
        ],
        monster_level_requirement=5,
        hp_requirement=35,
        mp_requirement=None,
        atk_requirement=30,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    PSYCHEUP = Skill(
        name="PsycheUp",
        slug="psycheup",
        description="Greater Damage with normal attack after end of this turn",
        monsters=[
            MonsterSpecies.DARKHORN,
            MonsterSpecies.GOLEM,
            MonsterSpecies.MADCANDLE,
            MonsterSpecies.MANEATER,
            MonsterSpecies.SACCER,
        ],
        monster_level_requirement=12,
        hp_requirement=72,
        mp_requirement=None,
        atk_requirement=82,
        def_requirement=68,
        agl_requirement=None,
        int_requirement=None,
    )
    QUADHITS = Skill(
        name="QuadHits",
        slug="quadhits",
        description="Attacks 4 times random foes",
        monsters=[],
        monster_level_requirement=24,
        hp_requirement=124,
        mp_requirement=None,
        atk_requirement=112,
        def_requirement=None,
        agl_requirement=136,
        int_requirement=None,
    )
    RADIANT = Skill(
        name="Radiant",
        slug="radiant",
        description="Decreases physical hit chance of all foes",
        monsters=[
            MonsterSpecies.DARKEYE,
            MonsterSpecies.EVILSEED,
            MonsterSpecies.GIANTMOTH,
            MonsterSpecies.MADSPIRIT,
            MonsterSpecies.SLIME,
            MonsterSpecies.SPOOKY,
            MonsterSpecies.TAILEATER,
        ],
        monster_level_requirement=12,
        hp_requirement=None,
        mp_requirement=42,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=72,
        int_requirement=None,
    )
    RAINSLASH = Skill(
        name="RainSlash",
        slug="rainslash",
        description="Physical attack against all foes",
        monsters=[
            MonsterSpecies.ARMORPION,
            MonsterSpecies.CENTASAUR,
            MonsterSpecies.ESTERK,
            MonsterSpecies.OGRE,
            MonsterSpecies.ROBOSTER,
            MonsterSpecies.SLIMEBORG,
            MonsterSpecies.SKULRIDER,
            MonsterSpecies.SNAPPER,
            MonsterSpecies.STUBBIRD,
            MonsterSpecies.SWORDGON,
        ],
        monster_level_requirement=15,
        hp_requirement=92,
        mp_requirement=None,
        atk_requirement=90,
        def_requirement=None,
        agl_requirement=96,
        int_requirement=None,
    )
    RAMMING = Skill(
        name="Ramming",
        slug="ramming",
        description="Reduces the foe's Hp by 50% and hurts the caster too",
        monsters=[
            MonsterSpecies.BOXSLIME,
            MonsterSpecies.BULLBIRD,
            MonsterSpecies.DEATHMORE2,
            MonsterSpecies.GULPBEAST,
            MonsterSpecies.MINIDRAK,
            MonsterSpecies.PILLOWRAT,
        ],
        monster_level_requirement=12,
        hp_requirement=70,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=70,
        int_requirement=None,
    )
    REVIVE = Skill(
        name="Revive",
        slug="revive",
        description="Restores life to one ally with full Hp",
        monsters=[],
        monster_level_requirement=27,
        hp_requirement=None,
        mp_requirement=174,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=152,
    )
    ROBMAGIC = Skill(
        name="RobMagic",
        slug="robmagic",
        description="Steals one foe's Mp",
        monsters=[
            MonsterSpecies.BEANMAN,
            MonsterSpecies.DRACKY,
            MonsterSpecies.GOHOPPER,
            MonsterSpecies.ONIONO,
            MonsterSpecies.SABREMAN,
            MonsterSpecies.WEEDBUG,
        ],
        monster_level_requirement=7,
        hp_requirement=None,
        mp_requirement=32,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=28,
    )
    ROCKTHROW = Skill(
        name="RockThrow",
        slug="rockthrow",
        description="75-100 Damage with rocks to all foes",
        monsters=[
            MonsterSpecies.BARAMOS,
            MonsterSpecies.HORNBEET,
            MonsterSpecies.METALDRAK,
            MonsterSpecies.ROCKSLIME,
            MonsterSpecies.SPIKEROUS,
        ],
        monster_level_requirement=16,
        hp_requirement=124,
        mp_requirement=None,
        atk_requirement=102,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    SACRIFICE = Skill(
        name="Sacrifice",
        slug="sacrifice",
        description="Causes instant death or close to it to all foes and caster",
        monsters=[
            MonsterSpecies.AGDEVIL,
            MonsterSpecies.BOMBCRAG,
            MonsterSpecies.FACER,
            MonsterSpecies.GASGON,
            MonsterSpecies.METABBLE,
            MonsterSpecies.SPIKYBOY,
        ],
        monster_level_requirement=1,
        hp_requirement=None,
        mp_requirement=7,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=6,
    )
    SAMSICALL = Skill(
        name="SamsiCall",
        slug="samsicall",
        description="Summons a Samsi to fight using EvilSlash,SquallHit,RainSlash",
        monsters=[],
        monster_level_requirement=30,
        hp_requirement=None,
        mp_requirement=130,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=150,
    )
    SANDSTORM = Skill(
        name="SandStorm",
        slug="sandstorm",
        description="Decreases hit chance of all foes",
        monsters=[
            MonsterSpecies.BIGROOST,
            MonsterSpecies.METALDRAK,
            MonsterSpecies.MINIDRAK,
            MonsterSpecies.TRUMPETER,
        ],
        monster_level_requirement=10,
        hp_requirement=70,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=70,
        int_requirement=None,
    )
    SAP = Skill(
        name="Sap",
        slug="sap",
        description="Decreases defense of one foe by 50%",
        monsters=[
            MonsterSpecies.MADPECKER,
            MonsterSpecies.MADPLANT,
            MonsterSpecies.MEDUSAEYE,
            MonsterSpecies.ORC,
            MonsterSpecies.PICKY,
            MonsterSpecies.PUTREPUP,
            MonsterSpecies.SKELETOR,
            MonsterSpecies.TREESLIME,
            MonsterSpecies.VOODOLL,
        ],
        monster_level_requirement=4,
        hp_requirement=None,
        mp_requirement=18,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=15,
    )
    SCORCHING = Skill(
        name="Scorching",
        slug="scorching",
        description="75-100 Fire Damage to all foes",
        monsters=[],
        monster_level_requirement=20,
        hp_requirement=140,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    SHELDODGE = Skill(
        name="Sheldodge",
        slug="sheldodge",
        description="50% more damge against Bugs Normal against other foes",
        monsters=[MonsterSpecies.PICKY, MonsterSpecies.STUBBIRD],
        monster_level_requirement=5,
        hp_requirement=None,
        mp_requirement=21,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=20,
    )
    SICKLICK = Skill(
        name="SickLick",
        slug="sicklick",
        description="Stops action of one foe and reduces his defense to 1 for one turn",
        monsters=[],
        monster_level_requirement=13,
        hp_requirement=81,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=94,
        int_requirement=None,
    )
    SIDESTEP = Skill(
        name="SideStep",
        slug="sidestep",
        description="Increase chance to dodge foes' attacks",
        monsters=[
            MonsterSpecies.DANCEVEGI,
            MonsterSpecies.LANDOWL,
            MonsterSpecies.MUDDOLL,
            MonsterSpecies.SLABBIT,
            MonsterSpecies.PILLOWRAT,
        ],
        monster_level_requirement=9,
        hp_requirement=63,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=54,
        int_requirement=None,
    )
    SLEEP = Skill(
        name="Sleep",
        slug="sleep",
        description="Puts one foe to sleep",
        monsters=[
            MonsterSpecies.ALMIRAJ,
            MonsterSpecies.DARKHORN,
            MonsterSpecies.DRACKY,
            MonsterSpecies.DUCKKITE,
            MonsterSpecies.EVILPOT,
            MonsterSpecies.GULPPLE,
            MonsterSpecies.STAGBUG,
            MonsterSpecies.STUBSUCK,
            MonsterSpecies.TOADSTOOL,
            MonsterSpecies.WYVERN,
        ],
        monster_level_requirement=4,
        hp_requirement=None,
        mp_requirement=24,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=16,
    )
    SLEEPAIR = Skill(
        name="SleepAir",
        slug="sleepair",
        description="Puts all foes to sleep",
        monsters=[
            MonsterSpecies.AGDEVIL,
            MonsterSpecies.DRAGONKID,
            MonsterSpecies.FAIRYDRAK,
            MonsterSpecies.GOATEGON,
            MonsterSpecies.MANEATER,
            MonsterSpecies.MADSPIRIT,
            MonsterSpecies.ONIONO,
            MonsterSpecies.TREESLIME,
            MonsterSpecies.TOADSTOOL,
            MonsterSpecies.TONGUELLA,
        ],
        monster_level_requirement=10,
        hp_requirement=70,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=60,
    )
    SLEEPALL = Skill(
        name="SleepAll",
        slug="sleepall",
        description="Puts all foes to sleep",
        monsters=[],
        monster_level_requirement=11,
        hp_requirement=None,
        mp_requirement=52,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=46,
    )
    SLOW = Skill(
        name="Slow",
        slug="slow",
        description="Decreases agility of one foe by 50%",
        monsters=[
            MonsterSpecies.CATFLY,
            MonsterSpecies.DROLL,
            MonsterSpecies.FAIRYRAT,
            MonsterSpecies.GOATEGON,
            MonsterSpecies.MADPLANT,
            MonsterSpecies.PUTREPUP,
        ],
        monster_level_requirement=3,
        hp_requirement=None,
        mp_requirement=16,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=14,
    )
    SLOWALL = Skill(
        name="SlowAll",
        slug="slowall",
        description="Decreases agility of all foes by 50%",
        monsters=[],
        monster_level_requirement=7,
        hp_requirement=None,
        mp_requirement=32,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=28,
    )
    SMASHLIME = Skill(
        name="Smashlime",
        slug="smashlime",
        description="50% more Damage against Slimes Normal against other foes",
        monsters=[MonsterSpecies.FAIRYRAT, MonsterSpecies.SPIKYBOY],
        monster_level_requirement=12,
        hp_requirement=62,
        mp_requirement=None,
        atk_requirement=68,
        def_requirement=None,
        agl_requirement=72,
        int_requirement=None,
    )
    SNOWSTORM = Skill(
        name="SnowStorm",
        slug="snowstorm",
        description="42-58 Ice Damage to all foes",
        monsters=[],
        monster_level_requirement=12,
        hp_requirement=None,
        mp_requirement=42,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=60,
    )
    SPEED = Skill(
        name="Speed",
        slug="speed",
        description="Increases agility of one foe by 50%",
        monsters=[
            MonsterSpecies.CURSELAMP,
            MonsterSpecies.FLORAJAY,
            MonsterSpecies.PIXY,
        ],
        monster_level_requirement=1,
        hp_requirement=None,
        mp_requirement=10,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=8,
    )
    SPEEDUP = Skill(
        name="SpeedUp",
        slug="speedup",
        description="Increases agility of all foes by 50%",
        monsters=[],
        monster_level_requirement=5,
        hp_requirement=None,
        mp_requirement=24,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=20,
    )
    SQUALLHIT = Skill(
        name="SquallHit",
        slug="squallhit",
        description="Physical Attack which lets you always attack first this turn",
        monsters=[
            MonsterSpecies.ANTEATER,
            MonsterSpecies.CHOPCLOWN,
            MonsterSpecies.GRIZZLY,
            MonsterSpecies.MADCAT,
            MonsterSpecies.PHOENIX,
            MonsterSpecies.ROBOSTER,
            MonsterSpecies.WINGSLIME,
            MonsterSpecies.WINGSNAKE,
        ],
        monster_level_requirement=12,
        hp_requirement=72,
        mp_requirement=None,
        atk_requirement=68,
        def_requirement=None,
        agl_requirement=82,
        int_requirement=None,
    )
    STEPGUARD = Skill(
        name="StepGuard",
        slug="stepguard",
        description="Prevents Damage from lava, swamp, barrier for 1 level inside Gates",
        monsters=[
            MonsterSpecies.DARKCRAB,
            MonsterSpecies.DROLL,
            MonsterSpecies.GIANTWORM,
            MonsterSpecies.MIMIC,
            MonsterSpecies.STUBSUCK,
            MonsterSpecies.WINGTREE,
        ],
        monster_level_requirement=10,
        hp_requirement=None,
        mp_requirement=40,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=34,
    )
    STOPSPELL = Skill(
        name="StopSpell",
        slug="stopspell",
        description="Suspends all magical skills of all foes",
        monsters=[
            MonsterSpecies.CATFLY,
            MonsterSpecies.CENTASAUR,
            MonsterSpecies.CRESTPENT,
            MonsterSpecies.DARKHORN,
            MonsterSpecies.FACETREE,
            MonsterSpecies.GREMLIN,
            MonsterSpecies.JEWELBAG,
            MonsterSpecies.SNAPPER,
        ],
        monster_level_requirement=9,
        hp_requirement=None,
        mp_requirement=44,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=38,
    )
    STORMWIND = Skill(
        name="StormWind",
        slug="stormwind",
        description="Reflects breath attacks to all foes",
        monsters=[],
        monster_level_requirement=19,
        hp_requirement=140,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=126,
        agl_requirement=140,
        int_requirement=None,
    )
    STRONGD = Skill(
        name="StrongD",
        slug="strongd",
        description="Reduces every Damage taken this turn by 90%",
        monsters=[
            MonsterSpecies.DIGSTER,
            MonsterSpecies.GOLEM,
            MonsterSpecies.ICEMAN,
            MonsterSpecies.IRONTURT,
            MonsterSpecies.RAINHAWK,
            MonsterSpecies.ROCKSLIME,
        ],
        monster_level_requirement=14,
        hp_requirement=98,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=84,
        agl_requirement=None,
        int_requirement=None,
    )
    SUCKAIR = Skill(
        name="SuckAir",
        slug="suckair",
        description="More Damage next turn with breath skills",
        monsters=[
            MonsterSpecies.DRAKSLIME,
            MonsterSpecies.GISMO,
            MonsterSpecies.MIRUDRAAS2,
            MonsterSpecies.SKYDRAGON,
        ],
        monster_level_requirement=17,
        hp_requirement=119,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=102,
        agl_requirement=None,
        int_requirement=None,
    )
    SUCKALL = Skill(
        name="SuckAll",
        slug="suckall",
        description="Sucks in all attacks targeted at one ally for one turn",
        monsters=[
            MonsterSpecies.COILBIRD,
            MonsterSpecies.DIGSTER,
            MonsterSpecies.DRAGON,
            MonsterSpecies.GREATDRAK,
            MonsterSpecies.STONEMAN,
        ],
        monster_level_requirement=13,
        hp_requirement=91,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=78,
        agl_requirement=None,
        int_requirement=None,
    )
    SURGE = Skill(
        name="Surge",
        slug="surge",
        description="Cures any ailments for all allies",
        monsters=[
            MonsterSpecies.DRACOLORD2,
            MonsterSpecies.GOLDGOLEM,
            MonsterSpecies.GOLDSLIME,
            MonsterSpecies.RAINHAWK,
        ],
        monster_level_requirement=23,
        hp_requirement=None,
        mp_requirement=130,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=170,
    )
    SURROUND = Skill(
        name="Surround",
        slug="surround",
        description="Decreases hit chance of all foes",
        monsters=[
            MonsterSpecies.ANDREAL,
            MonsterSpecies.BABBLE,
            MonsterSpecies.BUTTERFLY,
            MonsterSpecies.FAIRYDRAK,
            MonsterSpecies.FAIRYRAT,
            MonsterSpecies.PICKY,
            MonsterSpecies.MEDUSAEYE,
            MonsterSpecies.MISTYWING,
            MonsterSpecies.VOODOLL,
        ],
        monster_level_requirement=10,
        hp_requirement=None,
        mp_requirement=47,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=41,
    )
    TAILWIND = Skill(
        name="TailWind",
        slug="tailwind",
        description="Reflects breath attacks to one foe",
        monsters=[
            MonsterSpecies.JAMIRUS,
            MonsterSpecies.MADHORNET,
            MonsterSpecies.MADRAVEN,
            MonsterSpecies.PHOENIX,
            MonsterSpecies.PTERANOD,
            MonsterSpecies.WINGSLIME,
        ],
        monster_level_requirement=11,
        hp_requirement=75,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=84,
        agl_requirement=70,
        int_requirement=None,
    )
    TAKEMAGIC = Skill(
        name="TakeMagic",
        slug="takemagic",
        description="Absorbs Mp of one spell cast by foe",
        monsters=[],
        monster_level_requirement=13,
        hp_requirement=None,
        mp_requirement=58,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=52,
    )
    TATSUCALL = Skill(
        name="TatsuCall",
        slug="tatsucall",
        description="Summons a Tatsu using HealMore,Lightning,Cover",
        monsters=[
            MonsterSpecies.DEATHMORE1,
            MonsterSpecies.DEADNOBLE,
            MonsterSpecies.GOLDGOLEM,
            MonsterSpecies.HARGON,
            MonsterSpecies.WHIPBIRD,
        ],
        monster_level_requirement=20,
        hp_requirement=None,
        mp_requirement=70,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=90,
    )
    THICKFOG = Skill(
        name="ThickFog",
        slug="thickfog",
        description="Suspends the skills of everyone for one round",
        monsters=[
            MonsterSpecies.CATAPILA,
            MonsterSpecies.GATEGUARD,
            MonsterSpecies.MADSPIRIT,
            MonsterSpecies.SHADOW,
            MonsterSpecies.WHIPBIRD,
        ],
        monster_level_requirement=22,
        hp_requirement=None,
        mp_requirement=120,
        atk_requirement=60,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    THORDAIN = Skill(
        name="Thordain",
        slug="thordain",
        description="175-225 Lightning Damage to all foes",
        monsters=[],
        monster_level_requirement=30,
        hp_requirement=None,
        mp_requirement=128,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=174,
    )
    TRANSFORM = Skill(
        name="Transform",
        slug="transform",
        description="Transforms a monsters skills and stats to those of the selected foe",
        monsters=[MonsterSpecies.COPYCAT, MonsterSpecies.MADMIRROR],
        monster_level_requirement=21,
        hp_requirement=None,
        mp_requirement=92,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=88,
    )
    TWINHITS = Skill(
        name="TwinHits",
        slug="twinhits",
        description="Increases the amount of Damage of the physical attacks",
        monsters=[
            MonsterSpecies.AMBERWEED,
            MonsterSpecies.ARMORPEDE,
            MonsterSpecies.BEANMAN,
            MonsterSpecies.CHOPCLOWN,
            MonsterSpecies.CURSELAMP,
            MonsterSpecies.PIXY,
            MonsterSpecies.STUBBIRD,
        ],
        monster_level_requirement=17,
        hp_requirement=None,
        mp_requirement=72,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=66,
    )
    TWINSLASH = Skill(
        name="TwinSlash",
        slug="twinslash",
        description="Inflicts physical Damage against one foe and wounds yourself",
        monsters=[
            MonsterSpecies.ARMORPEDE,
            MonsterSpecies.GRIZZLY,
            MonsterSpecies.SKULLGON,
            MonsterSpecies.WILDAPE,
        ],
        monster_level_requirement=8,
        hp_requirement=80,
        mp_requirement=None,
        atk_requirement=80,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    ULTRADOWN = Skill(
        name="UltraDown",
        slug="ultradown",
        description="Casts Sap,Slow,Surround on one foe",
        monsters=[MonsterSpecies.DEATHMORE2, MonsterSpecies.ROSEVINE],
        monster_level_requirement=21,
        hp_requirement=None,
        mp_requirement=110,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=150,
    )
    UPPER = Skill(
        name="Upper",
        slug="upper",
        description="Increases defence for one ally by 50%",
        monsters=[
            MonsterSpecies.ARMORPEDE,
            MonsterSpecies.ARMYCRAB,
            MonsterSpecies.BOXSLIME,
            MonsterSpecies.CATAPILA,
            MonsterSpecies.CURSELAMP,
            MonsterSpecies.HEALER,
            MonsterSpecies.SACCER,
            MonsterSpecies.SLIMENITE,
        ],
        monster_level_requirement=2,
        hp_requirement=None,
        mp_requirement=14,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=12,
    )
    VACUSLASH = Skill(
        name="VacuSlash",
        slug="vacuslash",
        description="Normal attack based on Air resistance of the foe",
        monsters=[
            MonsterSpecies.BIGROOST,
            MonsterSpecies.CHOPCLOWN,
            MonsterSpecies.LIONEX,
            MonsterSpecies.MADCAT,
            MonsterSpecies.MADPECKER,
            MonsterSpecies.RAYBURN,
            MonsterSpecies.WINDBEAST,
        ],
        monster_level_requirement=11,
        hp_requirement=77,
        mp_requirement=34,
        atk_requirement=66,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    VACUUM = Skill(
        name="Vacuum",
        slug="vacuum",
        description="Air Damage to all foes,level based",
        monsters=[],
        monster_level_requirement=19,
        hp_requirement=112,
        mp_requirement=None,
        atk_requirement=114,
        def_requirement=None,
        agl_requirement=132,
        int_requirement=None,
    )
    VIVIFY = Skill(
        name="Vivify",
        slug="vivify",
        description="Restores life to one ally with half his Hp (50% chance of sucess)",
        monsters=[
            MonsterSpecies.KINGSLIME,
            MonsterSpecies.MUDRON,
            MonsterSpecies.ORC,
            MonsterSpecies.UNICORN,
        ],
        monster_level_requirement=14,
        hp_requirement=None,
        mp_requirement=63,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=54,
    )
    WARCRY = Skill(
        name="WarCry",
        slug="warcry",
        description="Freezes all foes with a loud roar to stop  their actions for 1 turn",
        monsters=[
            MonsterSpecies.EYEBALL,
            MonsterSpecies.FANGSLIME,
            MonsterSpecies.GULPBEAST,
            MonsterSpecies.TRUMPETER,
            MonsterSpecies.YETI,
        ],
        monster_level_requirement=14,
        hp_requirement=120,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    WHISTLE = Skill(
        name="Whistle",
        slug="whistle",
        description="Summons monsters inside the gates to fight you",
        monsters=[
            MonsterSpecies.GIANTSLUG,
            MonsterSpecies.MADCANDLE,
            MonsterSpecies.SLABBIT,
            MonsterSpecies.WATABOU,
        ],
        monster_level_requirement=4,
        hp_requirement=None,
        mp_requirement=28,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=24,
    )
    WHITEAIR = Skill(
        name="WhiteAir",
        slug="whiteair",
        description="160-180 Ice Damage to all foes",
        monsters=[],
        monster_level_requirement=30,
        hp_requirement=210,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    WHITEFIRE = Skill(
        name="WhiteFire",
        slug="whitefire",
        description="150-170 Fire Damage to all foes",
        monsters=[],
        monster_level_requirement=30,
        hp_requirement=210,
        mp_requirement=None,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=None,
    )
    WINDBEAST = Skill(
        name="WindBeast",
        slug="windbeast",
        description="Air Damage to one foe,level based",
        monsters=[
            MonsterSpecies.DURRAN,
            MonsterSpecies.GIANTMOTH,
            MonsterSpecies.LIZARDFLY,
            MonsterSpecies.NITEWHIP,
            MonsterSpecies.PTERANOD,
            MonsterSpecies.WINGSLIME,
        ],
        monster_level_requirement=13,
        hp_requirement=74,
        mp_requirement=None,
        atk_requirement=60,
        def_requirement=None,
        agl_requirement=84,
        int_requirement=None,
    )
    YELLHELP = Skill(
        name="YellHelp",
        slug="yellhelp",
        description="Calls randomly allies to help,level based Damage",
        monsters=[],
        monster_level_requirement=23,
        hp_requirement=128,
        mp_requirement=64,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=82,
        int_requirement=None,
    )
    ZAP = Skill(
        name="Zap",
        slug="zap",
        description="70-90 Lightning Damage to all foes",
        monsters=[],
        monster_level_requirement=15,
        hp_requirement=None,
        mp_requirement=54,
        atk_requirement=None,
        def_requirement=None,
        agl_requirement=None,
        int_requirement=72,
    )
    ZOMBIECUT = Skill(
        name="ZombieCut",
        slug="zombiecut",
        description="50% more Damage against Zombies Normal against other foes",
        monsters=[
            MonsterSpecies.ARMORPION,
            MonsterSpecies.GIGANTES,
            MonsterSpecies.MADGOPHER,
            MonsterSpecies.STUBSUCK,
            MonsterSpecies.WINGTREE,
        ],
        monster_level_requirement=12,
        hp_requirement=64,
        mp_requirement=None,
        atk_requirement=58,
        def_requirement=None,
        agl_requirement=62,
        int_requirement=None,
    )


class LevelledSkill(NamedTuple):
    """A skill that levels up with the monster."""

    levelled_skill: Skill
    level: int  # The level of this advancing skill, if it is levelled
    base_skill: (
        Skill | None
    )  # The base skill this levelled skill originates from, if there is one


class LevelledSkills:
    """All levelling skills."""

    BAZOOCALL = LevelledSkill(
        level=4,
        levelled_skill=Skills.BAZOOCALL,
        base_skill=Skills.TATSUCALL,
    )
    BIGTRIP = LevelledSkill(
        level=2,
        levelled_skill=Skills.BIGTRIP,
        base_skill=Skills.LEGSWEEP,
    )
    BLAZEAIR = LevelledSkill(
        level=2,
        levelled_skill=Skills.BLAZEAIR,
        base_skill=Skills.FIREAIR,
    )
    BLAZEMORE = LevelledSkill(
        level=2,
        levelled_skill=Skills.BLAZEMORE,
        base_skill=Skills.BLAZE,
    )
    BLAZEMOST = LevelledSkill(
        level=3,
        levelled_skill=Skills.BLAZEMOST,
        base_skill=Skills.BLAZE,
    )
    BLIZZARD = LevelledSkill(
        level=3,
        levelled_skill=Skills.BLIZZARD,
        base_skill=Skills.ICEBOLT,
    )
    BOOM = LevelledSkill(level=2, levelled_skill=Skills.BOOM, base_skill=Skills.BANG)
    DEFEAT = LevelledSkill(
        level=2,
        levelled_skill=Skills.DEFEAT,
        base_skill=Skills.BEAT,
    )
    DEFENCE = LevelledSkill(
        level=2,
        levelled_skill=Skills.DEFENCE,
        base_skill=Skills.SAP,
    )
    DIAGOCALL = LevelledSkill(
        level=2,
        levelled_skill=Skills.DIAGOCALL,
        base_skill=Skills.TATSUCALL,
    )
    EXPLODET = LevelledSkill(
        level=3,
        levelled_skill=Skills.EXPLODET,
        base_skill=Skills.BANG,
    )
    FIREBANE = LevelledSkill(
        level=2,
        levelled_skill=Skills.FIREBANE,
        base_skill=Skills.FIREBAL,
    )
    FIREBOLT = LevelledSkill(
        level=3,
        levelled_skill=Skills.FIREBOLT,
        base_skill=Skills.FIREBAL,
    )
    GUARDIAN = LevelledSkill(
        level=2,
        levelled_skill=Skills.GUARDIAN,
        base_skill=Skills.COVER,
    )
    HEALALL = LevelledSkill(
        level=3,
        levelled_skill=Skills.HEALALL,
        base_skill=Skills.HEAL,
    )
    HEALMORE = LevelledSkill(
        level=2,
        levelled_skill=Skills.HEALMORE,
        base_skill=Skills.HEAL,
    )
    HEALUSALL = LevelledSkill(
        level=2,
        levelled_skill=Skills.HEALUSALL,
        base_skill=Skills.HEALUS,
    )
    ICEAIR = LevelledSkill(
        level=2,
        levelled_skill=Skills.ICEAIR,
        base_skill=Skills.FRIGIDAIR,
    )
    ICESTORM = LevelledSkill(
        level=3,
        levelled_skill=Skills.ICESTORM,
        base_skill=Skills.FRIGIDAIR,
    )
    INCREASE = LevelledSkill(
        level=2,
        levelled_skill=Skills.INCREASE,
        base_skill=Skills.UPPER,
    )
    INFERMORE = LevelledSkill(
        level=2,
        levelled_skill=Skills.INFERMORE,
        base_skill=Skills.INFERNOS,
    )
    INFERMOST = LevelledSkill(
        level=3,
        levelled_skill=Skills.INFERMOST,
        base_skill=Skills.INFERNOS,
    )
    POISONAIR = LevelledSkill(
        level=2,
        levelled_skill=Skills.POISONAIR,
        base_skill=Skills.POISONGAS,
    )
    QUADHITS = LevelledSkill(
        level=2,
        levelled_skill=Skills.QUADHITS,
        base_skill=Skills.BIATTACK,
    )
    REVIVE = LevelledSkill(
        level=2,
        levelled_skill=Skills.REVIVE,
        base_skill=Skills.VIVIFY,
    )
    SAMSICALL = LevelledSkill(
        level=3,
        levelled_skill=Skills.SAMSICALL,
        base_skill=Skills.TATSUCALL,
    )
    SCORCHING = LevelledSkill(
        level=3,
        levelled_skill=Skills.SCORCHING,
        base_skill=Skills.FIREAIR,
    )
    SICKLICK = LevelledSkill(
        level=2,
        levelled_skill=Skills.SICKLICK,
        base_skill=Skills.LUSHLICKS,
    )
    SLEEPALL = LevelledSkill(
        level=2,
        levelled_skill=Skills.SLEEPALL,
        base_skill=Skills.SLEEP,
    )
    SLOWALL = LevelledSkill(
        level=2,
        levelled_skill=Skills.SLOWALL,
        base_skill=Skills.SLOW,
    )
    SNOWSTORM = LevelledSkill(
        level=2,
        levelled_skill=Skills.SNOWSTORM,
        base_skill=Skills.ICEBOLT,
    )
    SPEEDUP = LevelledSkill(
        level=2,
        levelled_skill=Skills.SPEEDUP,
        base_skill=Skills.SPEED,
    )
    STORMWIND = LevelledSkill(
        level=2,
        levelled_skill=Skills.STORMWIND,
        base_skill=Skills.TAILWIND,
    )
    TAKEMAGIC = LevelledSkill(
        level=2,
        levelled_skill=Skills.TAKEMAGIC,
        base_skill=Skills.ROBMAGIC,
    )
    THORDAIN = LevelledSkill(
        level=3,
        levelled_skill=Skills.THORDAIN,
        base_skill=Skills.BOLT,
    )
    VACUUM = LevelledSkill(
        level=2,
        levelled_skill=Skills.VACUUM,
        base_skill=Skills.WINDBEAST,
    )
    WHITEAIR = LevelledSkill(
        level=4,
        levelled_skill=Skills.WHITEAIR,
        base_skill=Skills.FRIGIDAIR,
    )
    WHITEFIRE = LevelledSkill(
        level=4,
        levelled_skill=Skills.WHITEFIRE,
        base_skill=Skills.FIREAIR,
    )
    YELLHELP = LevelledSkill(
        level=2,
        levelled_skill=Skills.YELLHELP,
        base_skill=Skills.CALLHELP,
    )
    ZAP = LevelledSkill(level=2, levelled_skill=Skills.ZAP, base_skill=Skills.BOLT)


class ComboSkill(NamedTuple):
    """A skill that has prerequisites."""

    combined_skill: Skill
    prerequisites: list[Skill]  # The required skills to combine into this skill, if any


class ComboSkills:
    """All combination skills that have prerequisites."""

    BIGBANG = ComboSkill(
        combined_skill=Skills.BIGBANG,
        prerequisites=[Skills.EXPLODET, Skills.WHITEFIRE, Skills.WHITEAIR],
    )
    BOLTSLASH = ComboSkill(
        combined_skill=Skills.BOLTSLASH,
        prerequisites=[Skills.CHARGEUP, Skills.LIGHTNING],
    )
    DEMAGIC = ComboSkill(
        combined_skill=Skills.DEMAGIC,
        prerequisites=[Skills.SURGE, Skills.ULTRADOWN],
    )
    EERIELITE = ComboSkill(
        combined_skill=Skills.EERIELITE,
        prerequisites=[Skills.CURSE, Skills.RADIANT],
    )
    FAREWELL = ComboSkill(
        combined_skill=Skills.FAREWELL,
        prerequisites=[Skills.SACRIFICE, Skills.REVIVE],
    )
    FIRESLASH = ComboSkill(
        combined_skill=Skills.FIRESLASH,
        prerequisites=[Skills.BLAZEMORE, Skills.CHARGEUP],
    )
    FOCUS = ComboSkill(
        combined_skill=Skills.FOCUS,
        prerequisites=[Skills.CHARGEUP, Skills.SUCKAIR, Skills.MEDITATE],
    )
    GIGASLASH = ComboSkill(
        combined_skill=Skills.GIGASLASH,
        prerequisites=[
            Skills.FIRESLASH,
            Skills.BOLTSLASH,
            Skills.VACUSLASH,
            Skills.ICESLASH,
        ],
    )
    HELLBLAST = ComboSkill(
        combined_skill=Skills.HELLBLAST,
        prerequisites=[Skills.THORDAIN, Skills.LIGHTNING],
    )
    HUSTLE = ComboSkill(
        combined_skill=Skills.HUSTLE,
        prerequisites=[Skills.HEALALL, Skills.SIDESTEP],
    )
    ICESLASH = ComboSkill(
        combined_skill=Skills.ICESLASH,
        prerequisites=[Skills.CHARGEUP, Skills.SNOWSTORM],
    )
    IMITATE = ComboSkill(
        combined_skill=Skills.IMITATE,
        prerequisites=[Skills.TRANSFORM, Skills.FOCUS],
    )
    KAMIKAZE = ComboSkill(
        combined_skill=Skills.KAMIKAZE,
        prerequisites=[Skills.CHARGEUP, Skills.RAMMING],
    )
    LIFEDANCE = ComboSkill(
        combined_skill=Skills.LIFEDANCE,
        prerequisites=[Skills.HUSTLE, Skills.SACRIFICE],
    )
    LIFESONG = ComboSkill(
        combined_skill=Skills.LIFESONG,
        prerequisites=[Skills.REVIVE, Skills.WARCRY],
    )
    MEDITATE = ComboSkill(
        combined_skill=Skills.MEDITATE,
        prerequisites=[Skills.GUARDIAN, Skills.STRONGD],
    )
    MEGAMAGIC = ComboSkill(
        combined_skill=Skills.MEGAMAGIC,
        prerequisites=[
            Skills.BLAZEMOST,
            Skills.BLIZZARD,
            Skills.EXPLODET,
            Skills.FIREBOLT,
            Skills.INFERMOST,
        ],
    )
    MULTICUT = ComboSkill(
        combined_skill=Skills.MULTICUT,
        prerequisites=[Skills.ZOMBIECUT, Skills.VACUUM],
    )
    PALSYAIR = ComboSkill(
        combined_skill=Skills.PALSYAIR,
        prerequisites=[Skills.SLEEPAIR, Skills.POISONAIR],
    )
    PARALYZE = ComboSkill(
        combined_skill=Skills.PARALYZE,
        prerequisites=[Skills.POISONHIT, Skills.NAPATTACK],
    )
    RAINSLASH = ComboSkill(
        combined_skill=Skills.RAINSLASH,
        prerequisites=[Skills.BIATTACK, Skills.SQUALLHIT],
    )
    SURGE = ComboSkill(
        combined_skill=Skills.SURGE,
        prerequisites=[
            Skills.ANTIDOTE,
            Skills.NUMBOFF,
            Skills.DECHAOS,
            Skills.CURSEOFF,
        ],
    )
    ULTRADOWN = ComboSkill(
        combined_skill=Skills.ULTRADOWN,
        prerequisites=[Skills.SURROUND, Skills.DEFENCE, Skills.SLOWALL],
    )
    VACUSLASH = ComboSkill(
        combined_skill=Skills.VACUSLASH,
        prerequisites=[Skills.CHARGEUP, Skills.WINDBEAST],
    )
