"""Constants pertaining to monster breeding in Dragon Warrior Monsters."""

from collections import defaultdict
from collections.abc import Sequence
from typing import ClassVar, Literal, NamedTuple, overload

from monsters.constants import MonsterFamily, MonsterSpecies, Species


class Recipe(NamedTuple):
    """One breeding pair."""

    pedigree: list[Species | MonsterFamily]
    mate: list[Species | MonsterFamily]
    result: Species
    note: str | None = None


class Recipes:
    """All breeding combinations."""

    _all_recipes: ClassVar[list[Recipe]] = [
        Recipe(
            result=MonsterSpecies.DRAKSLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.SPOTSLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.WINGSLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.TREESLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.SNAILY,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.SLIMENITE,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.BABBLE,
            pedigree=[MonsterFamily.SLIME],
            mate=[
                MonsterSpecies.POISONGON,
                MonsterSpecies.GIANTMOTH,
                MonsterFamily.ZOMBIE,
            ],
        ),
        Recipe(
            result=MonsterSpecies.BOXSLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.HEALER,
            pedigree=[MonsterFamily.SLIME],
            mate=[
                MonsterSpecies.PILLOWRAT,
                MonsterSpecies.FUNKYBIRD,
                MonsterSpecies.MADPLANT,
                MonsterSpecies.COPYCAT,
            ],
        ),
        Recipe(
            result=MonsterSpecies.FANGSLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[
                MonsterSpecies.ALMIRAJ,
                MonsterSpecies.GULPBEAST,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.KINGLEO,
                MonsterSpecies.DARKHORN,
                MonsterSpecies.MADCAT,
            ],
        ),
        Recipe(
            result=MonsterSpecies.ROCKSLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[
                MonsterSpecies.DIGSTER,
                MonsterSpecies.DEADNITE,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
                MonsterSpecies.BOMBCRAG,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SLIMEBORG,
            pedigree=[
                MonsterSpecies.DRAKSLIME,
                MonsterSpecies.SLIMENITE,
                MonsterSpecies.ROCKSLIME,
                MonsterSpecies.METABBLE,
            ],
            mate=[
                MonsterSpecies.SWORDGON,
                MonsterSpecies.SPIKEROUS,
                MonsterSpecies.GREATDRAK,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.SKYDRAGON,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SLIMEBORG,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterSpecies.ROBOSTER],
        ),
        Recipe(
            result=MonsterSpecies.SLABBIT,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterSpecies.SKULLROO],
        ),
        Recipe(
            result=MonsterSpecies.SPOTKING,
            pedigree=[MonsterSpecies.KINGSLIME, MonsterSpecies.METALKING],
            mate=[
                MonsterSpecies.GREATDRAK,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.DIVINEGON,
                MonsterSpecies.UNICORN,
                MonsterSpecies.KINGLEO,
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.ZAPBIRD,
                MonsterSpecies.WHIPBIRD,
                MonsterSpecies.GIGANTES,
                MonsterSpecies.CENTASAUR,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.WHITEKING,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SPOTKING,
            pedigree=[MonsterSpecies.SPOTSLIME],
            mate=[MonsterSpecies.SPOTSLIME],
            note="+4 or better required",
        ),
        Recipe(
            result=MonsterSpecies.KINGSLIME,
            pedigree=[MonsterSpecies.SPOTKING],
            mate=[
                MonsterSpecies.GREATDRAK,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.DIVINEGON,
                MonsterSpecies.UNICORN,
                MonsterSpecies.KINGLEO,
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.ZAPBIRD,
                MonsterSpecies.WHIPBIRD,
                MonsterSpecies.GIGANTES,
                MonsterSpecies.CENTASAUR,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.WHITEKING,
            ],
        ),
        Recipe(
            result=MonsterSpecies.KINGSLIME,
            pedigree=[MonsterSpecies.SLIME],
            mate=[MonsterSpecies.SLIME],
            note="+4 or better required",
        ),
        Recipe(
            result=MonsterSpecies.KINGSLIME,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.METALY,
            pedigree=[MonsterFamily.SLIME],
            mate=[MonsterSpecies.METALDRAK],
        ),
        Recipe(
            result=MonsterSpecies.METABBLE,
            pedigree=[MonsterSpecies.METALY],
            mate=[MonsterSpecies.METALY],
        ),
        Recipe(
            result=MonsterSpecies.METALKING,
            pedigree=[MonsterSpecies.SPOTKING, MonsterSpecies.KINGSLIME],
            mate=[MonsterSpecies.METALDRAK],
        ),
        Recipe(
            result=MonsterSpecies.METALKING,
            pedigree=[MonsterSpecies.METABBLE],
            mate=[MonsterSpecies.METABBLE],
        ),
        Recipe(
            result=MonsterSpecies.GOLDSLIME,
            pedigree=[
                MonsterSpecies.SPOTKING,
                MonsterSpecies.KINGSLIME,
                MonsterSpecies.METALKING,
            ],
            mate=[
                MonsterSpecies.GOLDGOLEM,
            ],
        ),
        Recipe(
            result=MonsterSpecies.GOLDSLIME,
            pedigree=[MonsterSpecies.METALKING],
            mate=[MonsterSpecies.METALKING],
        ),
        Recipe(
            result=MonsterSpecies.DRAGONKID,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.TORTRAGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.PTERANOD,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.GASGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.FAIRYDRAK,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.LIZARDMAN,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.POISONGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.SWORDGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.DRAGON,
            pedigree=[MonsterSpecies.DRAGONKID],
            mate=[MonsterSpecies.DRAGONKID],
        ),
        Recipe(
            result=MonsterSpecies.MINIDRAK,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.PICKY],
        ),
        Recipe(
            result=MonsterSpecies.MADDRAGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.GULPBEAST],
        ),
        Recipe(
            result=MonsterSpecies.MADDRAGON,
            pedigree=[MonsterSpecies.GASGON],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.RAYBURN,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.MADCONDOR],
        ),
        Recipe(
            result=MonsterSpecies.CHAMELGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.VOODOLL],
        ),
        Recipe(
            result=MonsterSpecies.LIZARDFLY,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.GOHOPPER],
        ),
        Recipe(
            result=MonsterSpecies.ANDREAL,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.GULPPLE],
        ),
        Recipe(
            result=MonsterSpecies.ANDREAL,
            pedigree=[
                MonsterSpecies.GASGON,
                MonsterSpecies.MADDRAGON,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.SKYDRAGON,
            ],
            mate=[
                MonsterSpecies.GOATEGON,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.WHIPBIRD,
                MonsterSpecies.FUNKYBIRD,
                MonsterSpecies.ARCDEMON,
                MonsterSpecies.LIONEX,
                MonsterSpecies.GOATHORN,
                MonsterSpecies.OGRE,
                MonsterSpecies.AKUBAR,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.GOLEM,
            ],
        ),
        Recipe(
            result=MonsterSpecies.KINGCOBRA,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.BABBLE],
        ),
        Recipe(
            result=MonsterSpecies.SPIKEROUS,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.ARMYCRAB, MonsterSpecies.DIGSTER],
        ),
        Recipe(
            result=MonsterSpecies.GREATDRAK,
            pedigree=[MonsterSpecies.DRAGONKID],
            mate=[MonsterSpecies.DRAGONKID],
            note="Offspring must be at least +4",
        ),
        Recipe(
            result=MonsterSpecies.GREATDRAK,
            pedigree=[MonsterSpecies.DRAGON],
            mate=[MonsterSpecies.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.RAYBURN,
            pedigree=[MonsterSpecies.LIZARDMAN],
            mate=[
                MonsterSpecies.WINGSLIME,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.MADCAT,
                MonsterSpecies.FACETREE,
                MonsterSpecies.LIONEX,
                MonsterSpecies.GOATHORN,
                MonsterSpecies.GATEGUARD,
                MonsterSpecies.GIGANTES,
            ],
        ),
        Recipe(
            result=MonsterSpecies.GREATDRAK,
            pedigree=[MonsterFamily.DRAGON],
            mate=[
                MonsterSpecies.SPOTKING,
                MonsterSpecies.KINGSLIME,
                MonsterSpecies.METALKING,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.UNICORN,
                MonsterSpecies.ZAPBIRD,
                MonsterSpecies.WHIPBIRD,
                MonsterSpecies.GIGANTES,
                MonsterSpecies.CENTASAUR,
            ],
        ),
        Recipe(
            result=MonsterSpecies.CRESTPENT,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.BIGROOST],
        ),
        Recipe(
            result=MonsterSpecies.WINGSNAKE,
            pedigree=[MonsterSpecies.CRESTPENT],
            mate=[MonsterSpecies.CRESTPENT],
        ),
        Recipe(
            result=MonsterSpecies.COATOL,
            pedigree=[MonsterSpecies.WINGSNAKE],
            mate=[MonsterSpecies.WINGSNAKE],
        ),
        Recipe(
            result=MonsterSpecies.COATOL,
            pedigree=[
                MonsterSpecies.PTERANOD,
                MonsterSpecies.GASGON,
                MonsterSpecies.LIZARDMAN,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.SKYDRAGON,
            ],
            mate=[
                MonsterSpecies.DARKHORN,
                MonsterSpecies.MADKNIGHT,
                MonsterSpecies.COPYCAT,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.OROCHI,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.OROCHI,
            pedigree=[MonsterSpecies.ANDREAL, MonsterSpecies.GREATDRAK],
            mate=[MonsterSpecies.MEDUSAEYE],
        ),
        Recipe(
            result=MonsterSpecies.BATTLEREX,
            pedigree=[MonsterFamily.DRAGON],
            mate=[
                MonsterSpecies.KINGLEO,
                MonsterSpecies.LIONEX,
                MonsterSpecies.OGRE,
                MonsterSpecies.MADKNIGHT,
                MonsterSpecies.EVILARMOR,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SKYDRAGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[MonsterSpecies.PHOENIX],
        ),
        Recipe(
            result=MonsterSpecies.DIVINEGON,
            pedigree=[MonsterSpecies.SKYDRAGON],
            mate=[MonsterSpecies.OROCHI],
        ),
        Recipe(
            result=MonsterSpecies.TONGUELLA,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.ALMIRAJ,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.CATFLY,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.PILLOWRAT,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.SACCER,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.GULPBEAST,
            pedigree=[MonsterSpecies.GRIZZLY],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.SKULLROO,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.WINDBEAST,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.WINDBEAST,
            pedigree=[MonsterSpecies.CATFLY],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.ANTEATER,
            pedigree=[MonsterSpecies.SACCER],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.SUPERTEN,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.MUDRON],
        ),
        Recipe(
            result=MonsterSpecies.SUPERTEN,
            pedigree=[MonsterSpecies.TONGUELLA, MonsterSpecies.GULPBEAST],
            mate=[
                MonsterSpecies.TREESLIME,
                MonsterSpecies.FANGSLIME,
                MonsterSpecies.MADDRAGON,
                MonsterSpecies.FUNKYBIRD,
                MonsterSpecies.MADPLANT,
                MonsterSpecies.FACETREE,
                MonsterSpecies.LIPSY,
                MonsterSpecies.DEMONITE,
                MonsterSpecies.GREMLIN,
                MonsterSpecies.COPYCAT,
                MonsterSpecies.JEWELBAG,
                MonsterSpecies.MIMIC,
            ],
        ),
        Recipe(
            result=MonsterSpecies.IRONTURT,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.TORTRAGON],
        ),
        Recipe(
            result=MonsterSpecies.MOMMONJA,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.DUCKKITE],
        ),
        Recipe(
            result=MonsterSpecies.HAMMERMAN,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.STUBSUCK],
        ),
        Recipe(
            result=MonsterSpecies.MADGOPHER,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.SABREMAN],
        ),
        Recipe(
            result=MonsterSpecies.FAIRYRAT,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.LIZARDFLY],
        ),
        Recipe(
            result=MonsterSpecies.UNICORN,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.FANGSLIME],
        ),
        Recipe(
            result=MonsterSpecies.WILDAPE,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.MADPECKER],
        ),
        Recipe(
            result=MonsterSpecies.WILDAPE,
            pedigree=[MonsterSpecies.ALMIRAJ],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.TRUMPETER,
            pedigree=[MonsterSpecies.WILDAPE],
            mate=[MonsterSpecies.WILDAPE],
        ),
        Recipe(
            result=MonsterSpecies.TRUMPETER,
            pedigree=[MonsterSpecies.SUPERTEN],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.DARKHORN,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.MADCAT,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.BIGEYE,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.EYEBALL],
        ),
        Recipe(
            result=MonsterSpecies.PICKY,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.WYVERN,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.BULLBIRD,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.FLORAJAY,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.DUCKKITE,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.MADPECKER,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.MADRAVEN,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.MISTYWING,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.DRACKY,
            pedigree=[MonsterSpecies.PICKY],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.STUBBIRD,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterSpecies.ROCKSLIME],
        ),
        Recipe(
            result=MonsterSpecies.LANDOWL,
            pedigree=[MonsterSpecies.BULLBIRD],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.MADGOOSE,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterSpecies.DROLL],
        ),
        Recipe(
            result=MonsterSpecies.MADCONDOR,
            pedigree=[MonsterSpecies.LANDOWL],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.MADCONDOR,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterSpecies.COILBIRD],
        ),
        Recipe(
            result=MonsterSpecies.WHIPBIRD,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterSpecies.RAYBURN],
        ),
        Recipe(
            result=MonsterSpecies.FUNKYBIRD,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterSpecies.DANCEVEGI],
        ),
        Recipe(
            result=MonsterSpecies.RAINHAWK,
            pedigree=[MonsterSpecies.BLIZZARDY],
            mate=[MonsterSpecies.PHOENIX],
        ),
        Recipe(
            result=MonsterSpecies.MADPLANT,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.FIREWEED,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.FLORAMAN,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.WINGTREE,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.CACTIBALL,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.GULPPLE,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.TOADSTOOL,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.AMBERWEED,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.STUBSUCK,
            pedigree=[MonsterSpecies.AMBERWEED],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.ONIONO,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterSpecies.GOPHECADA],
        ),
        Recipe(
            result=MonsterSpecies.DANCEVEGI,
            pedigree=[MonsterSpecies.MADPLANT],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.DANCEVEGI,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterSpecies.FACER],
        ),
        Recipe(
            result=MonsterSpecies.TREEBOY,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterSpecies.PIXY],
        ),
        Recipe(
            result=MonsterSpecies.FACETREE,
            pedigree=[MonsterSpecies.HERBMAN],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.FACETREE,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterSpecies.NITEWHIP],
        ),
        Recipe(
            result=MonsterSpecies.HERBMAN,
            pedigree=[MonsterSpecies.DANCEVEGI],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.HERBMAN,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterSpecies.FUNKYBIRD],
        ),
        Recipe(
            result=MonsterSpecies.BEANMAN,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterSpecies.PILLOWRAT],
        ),
        Recipe(
            result=MonsterSpecies.MANEATER,
            pedigree=[MonsterSpecies.EVILSEED],
            mate=[MonsterSpecies.EVILSEED],
        ),
        Recipe(
            result=MonsterSpecies.SNAPPER,
            pedigree=[MonsterSpecies.MANEATER],
            mate=[MonsterSpecies.MANEATER],
        ),
        Recipe(
            result=MonsterSpecies.ROSEVINE,
            pedigree=[MonsterFamily.PLANT],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.GIANTSLUG,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.CATAPILA,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.GOPHECADA,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.BUTTERFLY,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.WEEDBUG,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.GIANTWORM,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.LIPSY,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.STAGBUG,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.ARMYANT,
            pedigree=[MonsterSpecies.GIANTSLUG],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.TAILEATER,
            pedigree=[MonsterSpecies.WEEDBUG],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.TAILEATER,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterSpecies.FLORAMAN],
        ),
        Recipe(
            result=MonsterSpecies.ARMORPEDE,
            pedigree=[MonsterSpecies.GIANTWORM],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.ARMORPEDE,
            pedigree=[MonsterSpecies.DROLL],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.ARMORPEDE,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterSpecies.IRONTURT],
        ),
        Recipe(
            result=MonsterSpecies.EYEDER,
            pedigree=[MonsterSpecies.CATAPILA],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.EYEDER,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterSpecies.AMBERWEED],
        ),
        Recipe(
            result=MonsterSpecies.GIANTMOTH,
            pedigree=[MonsterSpecies.BUTTERFLY],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.GIANTMOTH,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterSpecies.SACCER],
        ),
        Recipe(
            result=MonsterSpecies.DROLL,
            pedigree=[MonsterSpecies.LIPSY],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.DROLL,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterSpecies.SPOOKY],
        ),
        Recipe(
            result=MonsterSpecies.ARMYCRAB,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterSpecies.DARKCRAB],
        ),
        Recipe(
            result=MonsterSpecies.MADHORNET,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterSpecies.FAIRYRAT],
        ),
        Recipe(
            result=MonsterSpecies.HORNBEET,
            pedigree=[MonsterSpecies.STAGBUG],
            mate=[MonsterSpecies.STAGBUG],
        ),
        Recipe(
            result=MonsterSpecies.HORNBEET,
            pedigree=[MonsterSpecies.ARMORPEDE],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.ARMORPION,
            pedigree=[MonsterSpecies.HORNBEET],
            mate=[MonsterSpecies.HORNBEET],
        ),
        Recipe(
            result=MonsterSpecies.DIGSTER,
            pedigree=[MonsterFamily.BUG],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.PIXY,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.ARCDEMON,
            pedigree=[MonsterSpecies.GATEGUARD],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.ARCDEMON,
            pedigree=[MonsterSpecies.OGRE],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.ARCDEMON,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.DEMONITE,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.DARKEYE,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.EYEBALL,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.SKULRIDER,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.EVILBEAST,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.MEDUSAEYE,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.LIONEX,
            pedigree=[MonsterSpecies.ARCDEMON],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.LIONEX,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.LIZARDMAN],
        ),
        Recipe(
            result=MonsterSpecies.GOATHORN,
            pedigree=[MonsterSpecies.ARCDEMON],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.GOATHORN,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.DARKHORN],
        ),
        Recipe(
            result=MonsterSpecies.ORC,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.BEANMAN],
        ),
        Recipe(
            result=MonsterSpecies.OGRE,
            pedigree=[MonsterSpecies.GATEGUARD],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.OGRE,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.HAMMERMAN],
        ),
        Recipe(
            result=MonsterSpecies.GATEGUARD,
            pedigree=[MonsterSpecies.DEMONITE],
            mate=[MonsterSpecies.DEMONITE],
        ),
        Recipe(
            result=MonsterSpecies.GATEGUARD,
            pedigree=[MonsterSpecies.OGRE],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.CHOPCLOWN,
            pedigree=[MonsterSpecies.ONEEYECLOWN],
            mate=[MonsterSpecies.ONEEYECLOWN],
        ),
        Recipe(
            result=MonsterSpecies.GRENDAL,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.MADDRAGON],
        ),
        Recipe(
            result=MonsterSpecies.AKUBAR,
            pedigree=[MonsterSpecies.ARCDEMON],
            mate=[MonsterSpecies.GATEGUARD],
        ),
        Recipe(
            result=MonsterSpecies.AKUBAR,
            pedigree=[MonsterSpecies.GRENDAL],
            mate=[MonsterSpecies.GRENDAL],
        ),
        Recipe(
            result=MonsterSpecies.MADKNIGHT,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.ROGUENITE],
        ),
        Recipe(
            result=MonsterSpecies.GIGANTES,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.BIGEYE],
        ),
        Recipe(
            result=MonsterSpecies.CENTASAUR,
            pedigree=[MonsterSpecies.ARCDEMON],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.EVILARMOR,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterSpecies.ARMORPEDE],
        ),
        Recipe(
            result=MonsterSpecies.JAMIRUS,
            pedigree=[MonsterSpecies.AKUBAR],
            mate=[MonsterSpecies.RAINHAWK],
        ),
        Recipe(
            result=MonsterSpecies.JAMIRUS,
            pedigree=[MonsterSpecies.RAINHAWK],
            mate=[MonsterSpecies.AKUBAR],
        ),
        Recipe(
            result=MonsterSpecies.DURRAN,
            pedigree=[MonsterSpecies.CENTASAUR],
            mate=[MonsterSpecies.GOLDGOLEM],
        ),
        Recipe(
            result=MonsterSpecies.DURRAN,
            pedigree=[MonsterSpecies.GOLDGOLEM],
            mate=[MonsterSpecies.CENTASAUR],
        ),
        Recipe(
            result=MonsterSpecies.SPOOKY,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.YETI,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.ORC],
        ),
        Recipe(
            result=MonsterSpecies.PUTREPUP,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.ROTRAVEN,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.MUMMY,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.DARKCRAB,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.DEADNITE,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.SHADOW,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.HORK,
            pedigree=[MonsterSpecies.SPOOKY],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.SKELETOR,
            pedigree=[MonsterSpecies.BONESLAVE],
            mate=[MonsterSpecies.BONESLAVE],
        ),
        Recipe(
            result=MonsterSpecies.SKELETOR,
            pedigree=[MonsterSpecies.MADSPIRIT],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.SERVANT,
            pedigree=[MonsterSpecies.SKELETOR],
            mate=[MonsterSpecies.SKELETOR],
        ),
        Recipe(
            result=MonsterSpecies.SERVANT,
            pedigree=[MonsterSpecies.WHITEKING],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.JEWELBAG,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.EVILWAND,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.MADCANDLE,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.COILBIRD,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.FACER,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.PLANT],
        ),
        Recipe(
            result=MonsterSpecies.SPIKYBOY,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.MADMIRROR,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.ROGUENITE,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.GOOPI,
            pedigree=[MonsterSpecies.JEWELBAG],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.ICEMAN,
            pedigree=[MonsterSpecies.ROBOSTER],
            mate=[MonsterSpecies.KINGLEO],
        ),
        Recipe(
            result=MonsterSpecies.MIMIC,
            pedigree=[MonsterSpecies.ROBOSTER],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.MIMIC,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterSpecies.BOXSLIME],
        ),
        Recipe(
            result=MonsterSpecies.MUDDOLL,
            pedigree=[MonsterSpecies.GOOPI],
            mate=[MonsterSpecies.GOOPI],
        ),
        Recipe(
            result=MonsterSpecies.GOLEM,
            pedigree=[MonsterSpecies.MUDDOLL],
            mate=[MonsterSpecies.MUDDOLL],
        ),
        Recipe(
            result=MonsterSpecies.NITEWHIP,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterSpecies.MISTYWING],
        ),
        Recipe(
            result=MonsterSpecies.MADSPIRIT,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.WINDMERGE,
            pedigree=[MonsterSpecies.ROTRAVEN],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.WINDMERGE,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterSpecies.WINDBEAST],
        ),
        Recipe(
            result=MonsterSpecies.SABREMAN,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterSpecies.GIANTWORM],
        ),
        Recipe(
            result=MonsterSpecies.CURSELAMP,
            pedigree=[MonsterSpecies.ROBOSTER],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.CURSELAMP,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterSpecies.WINGTREE],
        ),
        Recipe(
            result=MonsterSpecies.EVILPOT,
            pedigree=[MonsterSpecies.GISMO],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.EVILPOT,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterSpecies.SNAILY],
        ),
        Recipe(
            result=MonsterSpecies.BOMBCRAG,
            pedigree=[MonsterSpecies.SPIKYBOY],
            mate=[MonsterSpecies.SPIKYBOY],
        ),
        Recipe(
            result=MonsterSpecies.BOMBCRAG,
            pedigree=[MonsterSpecies.ROBOSTER],
            mate=[MonsterFamily.BUG],
        ),
        Recipe(
            result=MonsterSpecies.GOLDGOLEM,
            pedigree=[MonsterSpecies.ICEMAN],
            mate=[MonsterSpecies.LAVAMAN],
        ),
        Recipe(
            result=MonsterSpecies.HARGON,
            pedigree=[MonsterSpecies.WHITEKING],
            mate=[MonsterSpecies.METALKING],
        ),
        Recipe(
            result=MonsterSpecies.SIDOH,
            pedigree=[MonsterSpecies.JAMIRUS],
            mate=[MonsterSpecies.ROSEVINE],
        ),
        Recipe(
            result=MonsterSpecies.BARAMOS,
            pedigree=[MonsterSpecies.HARGON],
            mate=[MonsterSpecies.OROCHI],
        ),
        Recipe(
            result=MonsterSpecies.DRACOLORD2,
            pedigree=[MonsterSpecies.DRACOLORD1],
            mate=[MonsterSpecies.DIVINEGON],
        ),
        Recipe(
            result=MonsterSpecies.PIZZARO,
            pedigree=[MonsterSpecies.DURRAN],
            mate=[MonsterSpecies.DIVINEGON],
        ),
        Recipe(
            result=MonsterSpecies.ESTERK,
            pedigree=[MonsterSpecies.PIZZARO],
            mate=[MonsterSpecies.KINGLEO],
        ),
        Recipe(
            result=MonsterSpecies.MIRUDRAAS1,
            pedigree=[MonsterSpecies.ESTERK],
            mate=[MonsterSpecies.GOLDSLIME],
        ),
        Recipe(
            result=MonsterSpecies.MIRUDRAAS2,
            pedigree=[MonsterSpecies.MIRUDRAAS1],
            mate=[MonsterSpecies.SPIKEROUS],
        ),
        Recipe(
            result=MonsterSpecies.MUDOU,
            pedigree=[MonsterSpecies.BARAMOS],
            mate=[MonsterSpecies.DARKHORN],
        ),
        Recipe(
            result=MonsterSpecies.DEATHMORE2,
            pedigree=[MonsterSpecies.DEATHMORE1],
            mate=[MonsterSpecies.ARMORPION],
        ),
        Recipe(
            result=MonsterSpecies.DEATHMORE3,
            pedigree=[MonsterSpecies.DEATHMORE1],
            mate=[MonsterSpecies.MUDOU],
        ),
        Recipe(
            result=MonsterSpecies.DARKDRIUM,
            pedigree=[MonsterSpecies.DEATHMORE1],
            mate=[MonsterSpecies.WATABOU],
        ),
        Recipe(
            result=MonsterSpecies.REAPER,
            pedigree=[MonsterSpecies.SPOOKY, MonsterSpecies.HORK],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.REAPER,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterSpecies.WEEDBUG],
        ),
        Recipe(
            result=MonsterSpecies.DEADNOBLE,
            pedigree=[MonsterSpecies.DEADNITE],
            mate=[MonsterSpecies.DEADNITE],
        ),
        Recipe(
            result=MonsterSpecies.VOODOLL,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterSpecies.LIPSY],
        ),
        Recipe(
            result=MonsterSpecies.METALDRAK,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterSpecies.ANDREAL],
        ),
        Recipe(
            result=MonsterSpecies.BONESLAVE,
            pedigree=[MonsterSpecies.HORK],
            mate=[MonsterSpecies.HORK],
        ),
        Recipe(
            result=MonsterSpecies.GREMLIN,
            pedigree=[MonsterFamily.DEVIL],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.ZAPBIRD,
            pedigree=[MonsterFamily.BIRD],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.WHITEKING,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.BALZAK,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterFamily.BOSS],
        ),
        Recipe(
            result=MonsterSpecies.NITEWHIP,
            pedigree=[MonsterSpecies.DARKCRAB, MonsterSpecies.MADSPIRIT],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.BALZAK,
            pedigree=[MonsterSpecies.LAVAMAN, MonsterSpecies.ICEMAN],
            mate=[MonsterFamily.DEVIL],
        ),
        Recipe(
            result=MonsterSpecies.METALDRAK,
            pedigree=[MonsterSpecies.METALDRAK, MonsterSpecies.ROBOSTER],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.STONEMAN,
            pedigree=[MonsterSpecies.GOLEM, MonsterSpecies.STONEMAN],
            mate=[MonsterSpecies.GOLEM],
        ),
        Recipe(
            result=MonsterSpecies.CENTASAUR,
            pedigree=[MonsterSpecies.OGRE, MonsterSpecies.GATEGUARD],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.GIGANTES,
            pedigree=[MonsterSpecies.SKULRIDER, MonsterSpecies.EVILBEAST],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.MADHORNET,
            pedigree=[MonsterSpecies.EYEDER, MonsterSpecies.DROLL],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.ZOMA,
            pedigree=[MonsterSpecies.DRACOLORD1, MonsterSpecies.DRACOLORD2],
            mate=[MonsterSpecies.SIDOH],
        ),
        Recipe(
            result=MonsterSpecies.ICEMAN,
            pedigree=[MonsterSpecies.METALDRAK],
            mate=[MonsterSpecies.SKULLGON, MonsterSpecies.WHITEKING],
        ),
        Recipe(
            result=MonsterSpecies.STONEMAN,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[MonsterSpecies.HORNBEET, MonsterSpecies.DIGSTER],
        ),
        Recipe(
            result=MonsterSpecies.DRACOLORD1,
            pedigree=[MonsterSpecies.SERVANT],
            mate=[MonsterSpecies.ANDREAL, MonsterSpecies.GREATDRAK],
        ),
        Recipe(
            result=MonsterSpecies.DEATHMORE1,
            pedigree=[MonsterSpecies.ZOMA],
            mate=[MonsterSpecies.MIRUDRAAS1, MonsterSpecies.MIRUDRAAS2],
        ),
        Recipe(
            result=MonsterSpecies.GOATEGON,
            pedigree=[MonsterFamily.BEAST],
            mate=[MonsterSpecies.DRAKSLIME, MonsterSpecies.LIZARDMAN],
        ),
        Recipe(
            result=MonsterSpecies.GULPBEAST,
            pedigree=[
                MonsterSpecies.TONGUELLA,
                MonsterSpecies.GRIZZLY,
                MonsterSpecies.YETI,
                MonsterSpecies.UNICORN,
                MonsterSpecies.WILDAPE,
                MonsterSpecies.TRUMPETER,
            ],
            mate=[
                MonsterSpecies.DIGSTER,
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.WHITEKING,
                MonsterSpecies.SKELETOR,
            ],
        ),
        Recipe(
            result=MonsterSpecies.GULPBEAST,
            pedigree=[
                MonsterSpecies.GRIZZLY,
                MonsterSpecies.YETI,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.BIGEYE,
            ],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.ZAPBIRD,
            pedigree=[
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.PHOENIX,
                MonsterSpecies.WHIPBIRD,
            ],
            mate=[MonsterSpecies.GISMO],
        ),
        Recipe(
            result=MonsterSpecies.GULPBEAST,
            pedigree=[
                MonsterSpecies.IRONTURT,
                MonsterSpecies.GRIZZLY,
                MonsterSpecies.YETI,
                MonsterSpecies.UNICORN,
                MonsterSpecies.GOATEGON,
                MonsterSpecies.WILDAPE,
            ],
            mate=[
                MonsterSpecies.METALDRAK,
                MonsterSpecies.ROBOSTER,
                MonsterSpecies.LAVAMAN,
                MonsterSpecies.ICEMAN,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.GRIZZLY,
            pedigree=[MonsterFamily.BEAST],
            mate=[
                MonsterFamily.DEVIL,
                MonsterSpecies.METALDRAK,
                MonsterSpecies.ROBOSTER,
                MonsterSpecies.LAVAMAN,
                MonsterSpecies.ICEMAN,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.YETI,
            pedigree=[
                MonsterSpecies.IRONTURT,
                MonsterSpecies.GOATEGON,
                MonsterSpecies.WILDAPE,
                MonsterSpecies.MADCAT,
            ],
            mate=[
                MonsterSpecies.PTERANOD,
                MonsterSpecies.GASGON,
                MonsterSpecies.SWORDGON,
                MonsterSpecies.MADDRAGON,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.SKYDRAGON,
            ],
        ),
        Recipe(
            result=MonsterSpecies.UNICORN,
            pedigree=[
                MonsterSpecies.TONGUELLA,
                MonsterSpecies.GULPBEAST,
                MonsterSpecies.GRIZZLY,
                MonsterSpecies.YETI,
                MonsterSpecies.GOATEGON,
                MonsterSpecies.WILDAPE,
                MonsterSpecies.TRUMPETER,
            ],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.TRUMPETER,
            pedigree=[MonsterSpecies.GULPBEAST],
            mate=[
                MonsterSpecies.METALDRAK,
                MonsterSpecies.BALZAK,
                MonsterSpecies.ROBOSTER,
                MonsterSpecies.LAVAMAN,
                MonsterSpecies.ICEMAN,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.KINGLEO,
            pedigree=[MonsterSpecies.TRUMPETER],
            mate=[
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.METALDRAK,
                MonsterSpecies.BALZAK,
                MonsterSpecies.GOLDGOLEM,
            ],
        ),
        Recipe(
            result=MonsterSpecies.KINGLEO,
            pedigree=[MonsterSpecies.ROBOSTER],
            mate=[
                MonsterSpecies.GULPBEAST,
                MonsterSpecies.SUPERTEN,
                MonsterSpecies.UNICORN,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.DARKHORN,
                MonsterSpecies.MADCAT,
            ],
        ),
        Recipe(
            result=MonsterSpecies.ROBOSTER,
            pedigree=[MonsterFamily.MATERIAL],
            mate=[
                MonsterSpecies.GULPBEAST,
                MonsterSpecies.GRIZZLY,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.KINGLEO,
                MonsterSpecies.SKULRIDER,
            ],
        ),
        Recipe(
            result=MonsterSpecies.LAVAMAN,
            pedigree=[MonsterSpecies.METALDRAK],
            mate=[
                MonsterSpecies.OROCHI,
                MonsterSpecies.KINGLEO,
                MonsterSpecies.ZAPBIRD,
                MonsterSpecies.ARCDEMON,
                MonsterSpecies.CENTASAUR,
            ],
        ),
        Recipe(
            result=MonsterSpecies.ROBOSTER,
            pedigree=[MonsterSpecies.SABREMAN],
            mate=[
                MonsterSpecies.SLIMEBORG,
                MonsterSpecies.GREATDRAK,
                MonsterSpecies.UNICORN,
                MonsterSpecies.OGRE,
                MonsterSpecies.GRENDAL,
                MonsterSpecies.EVILARMOR,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.SKELETOR,
            ],
        ),
        Recipe(
            result=MonsterSpecies.EVILSEED,
            pedigree=[MonsterFamily.PLANT],
            mate=[
                MonsterSpecies.ROCKSLIME,
                MonsterSpecies.BIGEYE,
                MonsterSpecies.DUCKKITE,
                MonsterSpecies.BUTTERFLY,
                MonsterSpecies.EYEDER,
                MonsterSpecies.DARKEYE,
                MonsterSpecies.EYEBALL,
                MonsterSpecies.MADMIRROR,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SKULLGON,
            pedigree=[MonsterFamily.DRAGON],
            mate=[
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.WHITEKING,
                MonsterSpecies.SERVANT,
            ],
        ),
        Recipe(
            result=MonsterSpecies.MUDRON,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[
                MonsterSpecies.BOXSLIME,
                MonsterSpecies.FANGSLIME,
                MonsterSpecies.TONGUELLA,
                MonsterSpecies.YETI,
                MonsterSpecies.FUNKYBIRD,
                MonsterSpecies.MADPLANT,
                MonsterSpecies.DANCEVEGI,
                MonsterSpecies.GIANTSLUG,
                MonsterSpecies.LIPSY,
                MonsterSpecies.DROLL,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SKULLGON,
            pedigree=[MonsterFamily.ZOMBIE],
            mate=[
                MonsterSpecies.SWORDGON,
                MonsterSpecies.RAYBURN,
                MonsterSpecies.ANDREAL,
                MonsterSpecies.GREATDRAK,
                MonsterSpecies.OROCHI,
                MonsterSpecies.BATTLEREX,
                MonsterSpecies.DIVINEGON,
            ],
        ),
        Recipe(
            result=MonsterSpecies.BLIZZARDY,
            pedigree=[MonsterFamily.BIRD],
            mate=[
                MonsterSpecies.METALY,
                MonsterSpecies.METABBLE,
                MonsterSpecies.SUPERTEN,
                MonsterSpecies.YETI,
                MonsterSpecies.GOATEGON,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.WHITEKING,
                MonsterSpecies.SKELETOR,
                MonsterSpecies.SERVANT,
                MonsterSpecies.ICEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.PHOENIX,
            pedigree=[MonsterFamily.BIRD],
            mate=[
                MonsterSpecies.DRAKSLIME,
                MonsterSpecies.GULPBEAST,
                MonsterSpecies.IRONTURT,
                MonsterSpecies.GRIZZLY,
                MonsterSpecies.ARCDEMON,
                MonsterSpecies.COPYCAT,
                MonsterSpecies.GISMO,
                MonsterSpecies.LAVAMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.MADGOOSE,
            pedigree=[
                MonsterSpecies.WYVERN,
                MonsterSpecies.LANDOWL,
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.PHOENIX,
            ],
            mate=[MonsterFamily.DRAGON, MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.WHIPBIRD,
            pedigree=[
                MonsterSpecies.LANDOWL,
                MonsterSpecies.MADGOOSE,
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.BLIZZARDY,
                MonsterSpecies.ZAPBIRD,
            ],
            mate=[
                MonsterSpecies.ROCKSLIME,
                MonsterSpecies.SLIMEBORG,
                MonsterSpecies.DIGSTER,
                MonsterSpecies.METALDRAK,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.DROLL,
            pedigree=[
                MonsterSpecies.BUTTERFLY,
                MonsterSpecies.TAILEATER,
                MonsterSpecies.EYEDER,
            ],
            mate=[
                MonsterSpecies.BUTTERFLY,
                MonsterSpecies.TAILEATER,
                MonsterSpecies.EYEDER,
            ],
        ),
        Recipe(
            result=MonsterSpecies.ARCDEMON,
            pedigree=[
                MonsterSpecies.AGDEVIL,
                MonsterSpecies.GRENDAL,
                MonsterSpecies.GIGANTES,
            ],
            mate=[
                MonsterSpecies.SPOTKING,
                MonsterSpecies.KINGSLIME,
                MonsterSpecies.METALKING,
                MonsterSpecies.ANDREAL,
                MonsterSpecies.GREATDRAK,
                MonsterSpecies.OROCHI,
                MonsterSpecies.TRUMPETER,
                MonsterSpecies.KINGLEO,
                MonsterSpecies.ZAPBIRD,
                MonsterSpecies.WHIPBIRD,
                MonsterSpecies.METALDRAK,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.AGDEVIL,
            pedigree=[
                MonsterSpecies.SKULRIDER,
                MonsterSpecies.EVILBEAST,
                MonsterSpecies.GREMLIN,
                MonsterSpecies.MEDUSAEYE,
            ],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.ONEEYECLOWN,
            pedigree=[
                MonsterSpecies.PIXY,
                MonsterSpecies.DEMONITE,
                MonsterSpecies.EYEBALL,
            ],
            mate=[MonsterFamily.SLIME],
        ),
        Recipe(
            result=MonsterSpecies.MEDUSAEYE,
            pedigree=[
                MonsterSpecies.MEDUSAEYE,
                MonsterSpecies.ONEEYECLOWN,
                MonsterSpecies.GREMLIN,
            ],
            mate=[MonsterFamily.ZOMBIE],
        ),
        Recipe(
            result=MonsterSpecies.GRENDAL,
            pedigree=[
                MonsterSpecies.SKULRIDER,
                MonsterSpecies.EVILBEAST,
                MonsterSpecies.GREMLIN,
                MonsterSpecies.MEDUSAEYE,
            ],
            mate=[MonsterFamily.BEAST],
        ),
        Recipe(
            result=MonsterSpecies.EVILARMOR,
            pedigree=[
                MonsterSpecies.ARCDEMON,
                MonsterSpecies.OGRE,
                MonsterSpecies.GATEGUARD,
            ],
            mate=[MonsterFamily.MATERIAL],
        ),
        Recipe(
            result=MonsterSpecies.SKULLGON,
            pedigree=[
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.WHITEKING,
                MonsterSpecies.BONESLAVE,
                MonsterSpecies.SKELETOR,
            ],
            mate=[MonsterFamily.DRAGON],
        ),
        Recipe(
            result=MonsterSpecies.DEADNOBLE,
            pedigree=[
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNITE,
                MonsterSpecies.MUDRON,
                MonsterSpecies.BONESLAVE,
                MonsterSpecies.SKELETOR,
            ],
            mate=[MonsterSpecies.COPYCAT],
        ),
        Recipe(
            result=MonsterSpecies.MADSPIRIT,
            pedigree=[
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNITE,
                MonsterSpecies.MUDRON,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.BONESLAVE,
                MonsterSpecies.SKELETOR,
            ],
            mate=[MonsterFamily.BIRD],
        ),
        Recipe(
            result=MonsterSpecies.OGRE,
            pedigree=[
                MonsterSpecies.AGDEVIL,
                MonsterSpecies.GRENDAL,
                MonsterSpecies.GIGANTES,
            ],
            mate=[
                MonsterSpecies.GULPBEAST,
                MonsterSpecies.UNICORN,
                MonsterSpecies.DIGSTER,
                MonsterSpecies.ROBOSTER,
            ],
        ),
        Recipe(
            result=MonsterSpecies.GATEGUARD,
            pedigree=[
                MonsterSpecies.AGDEVIL,
                MonsterSpecies.GRENDAL,
                MonsterSpecies.GIGANTES,
            ],
            mate=[
                MonsterSpecies.SLIMEBORG,
                MonsterSpecies.SWORDGON,
                MonsterSpecies.COATOL,
                MonsterSpecies.MISTYWING,
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.ROSEVINE,
                MonsterSpecies.GIANTMOTH,
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.WHITEKING,
            ],
        ),
        Recipe(
            result=MonsterSpecies.DEADNOBLE,
            pedigree=[
                MonsterSpecies.MUDRON,
                MonsterSpecies.MADSPIRIT,
                MonsterSpecies.BONESLAVE,
                MonsterSpecies.SKELETOR,
            ],
            mate=[
                MonsterSpecies.ARCDEMON,
                MonsterSpecies.LIONEX,
                MonsterSpecies.GATEGUARD,
                MonsterSpecies.METALDRAK,
                MonsterSpecies.ROBOSTER,
            ],
        ),
        Recipe(
            result=MonsterSpecies.WHITEKING,
            pedigree=[
                MonsterSpecies.SKULLGON,
                MonsterSpecies.DEADNOBLE,
                MonsterSpecies.BONESLAVE,
                MonsterSpecies.SKELETOR,
            ],
            mate=[
                MonsterSpecies.SPOTKING,
                MonsterSpecies.KINGSLIME,
                MonsterSpecies.METALKING,
                MonsterSpecies.ANDREAL,
                MonsterSpecies.GREATDRAK,
                MonsterSpecies.KINGLEO,
                MonsterSpecies.BLIZZARDY,
                MonsterSpecies.ZAPBIRD,
                MonsterSpecies.WHIPBIRD,
                MonsterSpecies.GOLDGOLEM,
            ],
        ),
        Recipe(
            result=MonsterSpecies.BONESLAVE,
            pedigree=[
                MonsterSpecies.MUMMY,
                MonsterSpecies.DEADNITE,
                MonsterSpecies.HORK,
            ],
            mate=[
                MonsterSpecies.ROCKSLIME,
                MonsterSpecies.SLIMEBORG,
                MonsterSpecies.LANDOWL,
                MonsterSpecies.MADGOOSE,
                MonsterSpecies.FLORAMAN,
                MonsterSpecies.HORNBEET,
                MonsterSpecies.GREMLIN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SKELETOR,
            pedigree=[
                MonsterSpecies.MUMMY,
                MonsterSpecies.DEADNITE,
                MonsterSpecies.HORK,
                MonsterSpecies.MUDRON,
            ],
            mate=[
                MonsterSpecies.GULPBEAST,
                MonsterSpecies.GRIZZLY,
                MonsterSpecies.MADCAT,
                MonsterSpecies.MADRAVEN,
                MonsterSpecies.MADCONDOR,
                MonsterSpecies.EVILBEAST,
                MonsterSpecies.OGRE,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.VOODOLL,
            pedigree=[MonsterSpecies.GOLEM, MonsterSpecies.STONEMAN],
            mate=[
                MonsterSpecies.DRAKSLIME,
                MonsterSpecies.SNAILY,
                MonsterSpecies.SLIMENITE,
                MonsterSpecies.ROCKSLIME,
            ],
        ),
        Recipe(
            result=MonsterSpecies.METALDRAK,
            pedigree=[
                MonsterSpecies.ANDREAL,
                MonsterSpecies.SPIKEROUS,
                MonsterSpecies.GREATDRAK,
            ],
            mate=[
                MonsterSpecies.SLIMEBORG,
                MonsterSpecies.KINGSLIME,
                MonsterSpecies.DIGSTER,
                MonsterSpecies.SKULLGON,
                MonsterSpecies.ROBOSTER,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
            ],
        ),
        Recipe(
            result=MonsterSpecies.SABREMAN,
            pedigree=[
                MonsterSpecies.EVILWAND,
                MonsterSpecies.VOODOLL,
                MonsterSpecies.GOLEM,
                MonsterSpecies.STONEMAN,
            ],
            mate=[
                MonsterSpecies.LANDOWL,
                MonsterSpecies.MADGOOSE,
                MonsterSpecies.PHOENIX,
                MonsterSpecies.FUNKYBIRD,
            ],
        ),
        Recipe(
            result=MonsterSpecies.GISMO,
            pedigree=[
                MonsterSpecies.MADCANDLE,
                MonsterSpecies.MADMIRROR,
                MonsterSpecies.GOOPI,
            ],
            mate=[
                MonsterSpecies.DRAKSLIME,
                MonsterSpecies.WYVERN,
                MonsterSpecies.MISTYWING,
                MonsterSpecies.PHOENIX,
                MonsterSpecies.FIREWEED,
                MonsterSpecies.EVILSEED,
            ],
        ),
    ]

    @property
    def recipes_by_species_id(self) -> defaultdict[int, list[Recipe]]:
        """Returns a map of species ID to a list of recipes."""
        recipes_by_id = defaultdict(list)
        for recipe in self._all_recipes:
            recipes_by_id[recipe.result.id].append(recipe)
        return recipes_by_id

    def get_recipes_for_species_id(self, species_id: int) -> list[Recipe]:
        """Get a list of recipes for a specific species ID."""
        return self.recipes_by_species_id[species_id]

    @overload
    def get(
        self,
        *,
        role: Literal["pedigree", "mate"] = "pedigree",
        species_id: int,
        recipes: Sequence[Recipe] | None = None,
    ) -> list[Recipe]: ...

    @overload
    def get(
        self,
        *,
        role: Literal["pedigree", "mate"] = "pedigree",
        family: MonsterFamily,
        recipes: Sequence[Recipe] | None = None,
    ) -> list[Recipe]: ...

    def get(
        self,
        *,
        role: Literal["pedigree", "mate"] = "pedigree",
        species_id: int | None = None,
        family: MonsterFamily | None = None,
        recipes: Sequence[Recipe] | None = None,
    ) -> list[Recipe]:
        """Get recipes for a breeding pair."""
        pool = recipes if recipes is not None else self._all_recipes

        def matches(recipe: Species | MonsterFamily) -> bool:
            if species_id is not None:
                return isinstance(recipe, Species) and recipe.id == species_id
            return recipe == family

        if role == "pedigree":
            return [
                recipe
                for recipe in pool
                if any(matches(ped) for ped in recipe.pedigree)
            ]
        return [recipe for recipe in pool if any(matches(m) for m in recipe.mate)]
