"""
Tests for breeding.utils.

All Slime-result combinations are derived from the Combinations sheet
in monster_breeding.xlsx (reference document for game rules).

Class-based recipes (e.g. any Slime + any Dragon -> DrakSlime) are tested
with multiple pedigree/mate species. Species-specific recipes use one pair each.
"""

import pytest

from breeding.utils import get_breeding_result
from monsters.constants import MonsterSpecies, Species


@pytest.mark.parametrize(
    ("pedigree", "mate", "expected"),
    [
        # Any Slime + any Dragon -> DrakSlime
        (MonsterSpecies.SLIME, MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.MINIDRAK, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.TORTRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.PTERANOD, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SPOTSLIME, MonsterSpecies.ANDREAL, MonsterSpecies.DRAKSLIME),
        # Any Slime + any Beast -> Spotslime
        (MonsterSpecies.SLIME, MonsterSpecies.ANTEATER, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.CATFLY, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.WILDAPE, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.GRIZZLY, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.WINGSLIME, MonsterSpecies.ANTEATER, MonsterSpecies.SPOTSLIME),
        # Any Slime + any Bird -> Wingslime
        (MonsterSpecies.SLIME, MonsterSpecies.DRACKY, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BULLBIRD, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.PHOENIX, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.TREESLIME, MonsterSpecies.DRACKY, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SNAILY, MonsterSpecies.BIGROOST, MonsterSpecies.WINGSLIME),
        # Any Slime + any Plant -> Treeslime
        (MonsterSpecies.SLIME, MonsterSpecies.FIREWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.AMBERWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.FLORAMAN, MonsterSpecies.TREESLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.FIREWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.HEALER, MonsterSpecies.CACTIBALL, MonsterSpecies.TREESLIME),
        # Any Slime + any Bug -> Snaily
        (MonsterSpecies.SLIME, MonsterSpecies.CATAPILA, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIME, MonsterSpecies.BUTTERFLY, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIME, MonsterSpecies.ARMYANT, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIMENITE, MonsterSpecies.CATAPILA, MonsterSpecies.SNAILY),
        (MonsterSpecies.BABBLE, MonsterSpecies.HORNBEET, MonsterSpecies.SNAILY),
        # Any Slime + any Devil -> SlimeNite
        (MonsterSpecies.SLIME, MonsterSpecies.DEMONITE, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.SLIME, MonsterSpecies.ARCDEMON, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.SLIME, MonsterSpecies.AGDEVIL, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DEMONITE, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.ROCKSLIME, MonsterSpecies.ARCDEMON, MonsterSpecies.SLIMENITE),
        # Any Slime + any Material -> BoxSlime (mates that don't trigger other recipes)
        (MonsterSpecies.SLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BALZAK, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.CURSELAMP, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.FANGSLIME, MonsterSpecies.EVILPOT, MonsterSpecies.BOXSLIME),
        # Any Slime + any Boss -> Kingslime
        (MonsterSpecies.SLIME, MonsterSpecies.DRACOLORD1, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BARAMOS, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.HARGON, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DRACOLORD1, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.HEALER, MonsterSpecies.SIDOH, MonsterSpecies.KINGSLIME),
        # Species-specific: Babble (row 8) - slime + poisongon, giantmoth, or zombie
        (MonsterSpecies.SLIME, MonsterSpecies.POISONGON, MonsterSpecies.BABBLE),
        (MonsterSpecies.SLIME, MonsterSpecies.GIANTMOTH, MonsterSpecies.BABBLE),
        (MonsterSpecies.SLIME, MonsterSpecies.SPOOKY, MonsterSpecies.BABBLE),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.TREESLIME, MonsterSpecies.BOXSLIME),
        # Healer (row 11) - slime + pillowrat, funkybird, madplant, copycat
        (MonsterSpecies.SLIME, MonsterSpecies.PILLOWRAT, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.FUNKYBIRD, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.MADPLANT, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.COPYCAT, MonsterSpecies.HEALER),
        # FangSlime (row 12) - slime + almiraj, gulpbeast, trumpeter, kingleo, darkhorn, madcat
        (MonsterSpecies.SLIME, MonsterSpecies.ALMIRAJ, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.GULPBEAST, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.TRUMPETER, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.KINGLEO, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.DARKHORN, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.MADCAT, MonsterSpecies.FANGSLIME),
        # RockSlime (row 13) - slime + digster, deadnite, golem, stoneman, bombcrag
        (MonsterSpecies.SLIME, MonsterSpecies.DIGSTER, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.DEADNITE, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.GOLEM, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.STONEMAN, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BOMBCRAG, MonsterSpecies.ROCKSLIME),
        # SlimeBorg (row 14) - [drakslime,slimenite,rockslime,metabble] + [swordgon,spikerous,greatdrak,battlerex,skydragon]
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SPIKEROUS, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.GREATDRAK, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.BATTLEREX, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SKYDRAGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIMENITE, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.ROCKSLIME, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.METABBLE, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIME, MonsterSpecies.ROBOSTER, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIME, MonsterSpecies.SKULLROO, MonsterSpecies.SLABBIT),
        # SpotKing + any of [greatdrak, battlerex, ...] -> Kingslime (row 17 style)
        (MonsterSpecies.SPOTKING, MonsterSpecies.GREATDRAK, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.BATTLEREX, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.DIVINEGON, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.UNICORN, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.KINGLEO, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.MADCONDOR, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.ZAPBIRD, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.WHIPBIRD, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.GIGANTES, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.CENTASAUR, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.DEADNOBLE, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.WHITEKING, MonsterSpecies.KINGSLIME),
        # Kingslime + any of [greatdrak, battlerex, ...] -> SpotKing
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GREATDRAK, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.BATTLEREX, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.DIVINEGON, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.UNICORN, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.KINGLEO, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.MADCONDOR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.ZAPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.WHIPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GIGANTES, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.CENTASAUR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.DEADNOBLE, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.WHITEKING, MonsterSpecies.SPOTKING),
        # MetalKing + any of [greatdrak, battlerex, ...] -> SpotKing
        (MonsterSpecies.METALKING, MonsterSpecies.GREATDRAK, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.BATTLEREX, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.DIVINEGON, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.UNICORN, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.KINGLEO, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.MADCONDOR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.ZAPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.WHIPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.GIGANTES, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.CENTASAUR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.DEADNOBLE, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.WHITEKING, MonsterSpecies.SPOTKING),
        (MonsterSpecies.SPOTSLIME, MonsterSpecies.SPOTSLIME, MonsterSpecies.SPOTKING),
        (MonsterSpecies.SLIME, MonsterSpecies.SLIME, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.METALDRAK, MonsterSpecies.METALY),
        (MonsterSpecies.METALY, MonsterSpecies.METALY, MonsterSpecies.METABBLE),
        # MetalKing (row 24) - spotking or kingslime + metaldrak
        (MonsterSpecies.SPOTKING, MonsterSpecies.METALDRAK, MonsterSpecies.METALKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.METALDRAK, MonsterSpecies.METALKING),
        (MonsterSpecies.METABBLE, MonsterSpecies.METABBLE, MonsterSpecies.METALKING),
        # GoldSlime (row 26) - spotking, kingslime, or metalking + goldgolem
        (MonsterSpecies.SPOTKING, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.METALKING, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.METALKING, MonsterSpecies.METALKING, MonsterSpecies.GOLDSLIME),
    ],
    ids=[
        "slime_dragon",
        "slime_minidrak",
        "slime_tortragon",
        "boxslime_dragon",
        "drakslime_pteranod",
        "spotslime_andreal",
        "slime_anteater",
        "slime_catfly",
        "slime_wildape",
        "boxslime_grizzly",
        "wingslime_anteater",
        "slime_dracky",
        "slime_bullbird",
        "slime_phoenix",
        "treeslime_dracky",
        "snaily_bigroost",
        "slime_fireweed",
        "slime_amberweed",
        "slime_floraman",
        "drakslime_fireweed",
        "healer_cactiball",
        "slime_catapila",
        "slime_butterfly",
        "slime_armyant",
        "slimenite_catapila",
        "babble_hornbeet",
        "slime_demonite",
        "slime_arcdemon",
        "slime_agdevil",
        "boxslime_demonite",
        "rockslime_arcdemon",
        "slime_goldgolem",
        "slime_balzak",
        "slime_curselamp",
        "drakslime_goldgolem",
        "fangslime_evilpot",
        "slime_dracolord1",
        "slime_baramos",
        "slime_hargon",
        "boxslime_dracolord1",
        "healer_sidoh",
        "babble_slime_poisongon",
        "babble_slime_giantmoth",
        "babble_slime_spooky",
        "boxslime_treeslime",
        "healer_slime_pillowrat",
        "healer_slime_funkybird",
        "healer_slime_madplant",
        "healer_slime_copycat",
        "fangslime_slime_almiraj",
        "fangslime_slime_gulpbeast",
        "fangslime_slime_trumpeter",
        "fangslime_slime_kingleo",
        "fangslime_slime_darkhorn",
        "fangslime_slime_madcat",
        "rockslime_slime_digster",
        "rockslime_slime_deadnite",
        "rockslime_slime_golem",
        "rockslime_slime_stoneman",
        "rockslime_slime_bombcrag",
        "slimeborg_drakslime_swordgon",
        "slimeborg_drakslime_spikerous",
        "slimeborg_drakslime_greatdrak",
        "slimeborg_drakslime_battlerex",
        "slimeborg_drakslime_skydragon",
        "slimeborg_slimenite_swordgon",
        "slimeborg_rockslime_swordgon",
        "slimeborg_metabble_swordgon",
        "slimeborg_slime_roboster",
        "slime_skullroo",
        "kingslime_spotking_greatdrak",
        "kingslime_spotking_battlerex",
        "kingslime_spotking_divinegon",
        "kingslime_spotking_unicorn",
        "kingslime_spotking_kingleo",
        "kingslime_spotking_madcondor",
        "kingslime_spotking_zapbird",
        "kingslime_spotking_whipbird",
        "kingslime_spotking_gigantes",
        "kingslime_spotking_centasaur",
        "kingslime_spotking_deadnoble",
        "kingslime_spotking_whiteking",
        "spotking_kingslime_greatdrak",
        "spotking_kingslime_battlerex",
        "spotking_kingslime_divinegon",
        "spotking_kingslime_unicorn",
        "spotking_kingslime_kingleo",
        "spotking_kingslime_madcondor",
        "spotking_kingslime_zapbird",
        "spotking_kingslime_whipbird",
        "spotking_kingslime_gigantes",
        "spotking_kingslime_centasaur",
        "spotking_kingslime_deadnoble",
        "spotking_kingslime_whiteking",
        "spotking_metalking_greatdrak",
        "spotking_metalking_battlerex",
        "spotking_metalking_divinegon",
        "spotking_metalking_unicorn",
        "spotking_metalking_kingleo",
        "spotking_metalking_madcondor",
        "spotking_metalking_zapbird",
        "spotking_metalking_whipbird",
        "spotking_metalking_gigantes",
        "spotking_metalking_centasaur",
        "spotking_metalking_deadnoble",
        "spotking_metalking_whiteking",
        "spotslime_spotslime",
        "slime_slime",
        "slime_metaldrak",
        "metaly_metaly",
        "metalking_spotking_metaldrak",
        "metalking_kingslime_metaldrak",
        "metabble_metabble",
        "goldslime_spotking_goldgolem",
        "goldslime_kingslime_goldgolem",
        "goldslime_metalking_goldgolem",
        "goldslime_metalking_metalking",
    ],
)
def test_slime_breeding_combos(
    pedigree: Species,
    mate: Species,
    expected: Species,
) -> None:
    """Breeding pedigree + mate yields expected Slime result (per Combinations sheet)."""
    result = get_breeding_result(pedigree=pedigree, mate=mate)
    assert result == expected
