"""
Tests for breeding.utils.

Slime and Dragon result combinations are derived from the Rules sheet
in monster_breeding.xlsx (reference document for game rules).

Class-based recipes (e.g. any Slime + any Dragon -> DrakSlime) are tested
with multiple pedigree/mate species. Species-specific recipes use one or more pairs each.
"""

import pytest

from breeding.utils import get_breeding_result
from monsters.constants import MonsterSpecies, Species


@pytest.mark.parametrize(
    ("pedigree", "mate", "expected"),
    [
        # Any Slime + any Dragon -> DrakSlime
        (MonsterSpecies.SLIME, MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.MINIDRAK, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.TORTRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.PTERANOD, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SPOTSLIME, MonsterSpecies.ANDREAL, MonsterSpecies.DRAKSLIME),
        # Any Slime + any Beast -> Spotslime
        (MonsterSpecies.SLIME, MonsterSpecies.ANTEATER, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.CATFLY, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.WILDAPE, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.GRIZZLY, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.WINGSLIME, MonsterSpecies.ANTEATER, MonsterSpecies.SPOTSLIME),
        # Any Slime + any Bird -> Wingslime
        (MonsterSpecies.SLIME, MonsterSpecies.DRACKY, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BULLBIRD, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.PHOENIX, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.TREESLIME, MonsterSpecies.DRACKY, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SNAILY, MonsterSpecies.BIGROOST, MonsterSpecies.WINGSLIME),
        # Any Slime + any Plant -> Treeslime
        (MonsterSpecies.SLIME, MonsterSpecies.FIREWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.AMBERWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.FLORAMAN, MonsterSpecies.TREESLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.FIREWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.HEALER, MonsterSpecies.CACTIBALL, MonsterSpecies.TREESLIME),
        # Any Slime + any Bug -> Snaily
        (MonsterSpecies.SLIME, MonsterSpecies.CATAPILA, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIME, MonsterSpecies.BUTTERFLY, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIME, MonsterSpecies.ARMYANT, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIMENITE, MonsterSpecies.CATAPILA, MonsterSpecies.SNAILY),
        (MonsterSpecies.BABBLE, MonsterSpecies.HORNBEET, MonsterSpecies.SNAILY),
        # Any Slime + any Devil -> SlimeNite
        (MonsterSpecies.SLIME, MonsterSpecies.DEMONITE, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.SLIME, MonsterSpecies.ARCDEMON, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.SLIME, MonsterSpecies.AGDEVIL, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DEMONITE, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.ROCKSLIME, MonsterSpecies.ARCDEMON, MonsterSpecies.SLIMENITE),
        # Any Slime + any Material -> BoxSlime (mates that don't trigger other recipes)
        (MonsterSpecies.SLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BALZAK, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.CURSELAMP, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.FANGSLIME, MonsterSpecies.EVILPOT, MonsterSpecies.BOXSLIME),
        # Any Slime + any Boss -> Kingslime
        (MonsterSpecies.SLIME, MonsterSpecies.DRACOLORD1, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BARAMOS, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.HARGON, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DRACOLORD1, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.HEALER, MonsterSpecies.SIDOH, MonsterSpecies.KINGSLIME),
        # Species-specific: Babble (row 8) - slime + poisongon, giantmoth, or zombie
        (MonsterSpecies.SLIME, MonsterSpecies.POISONGON, MonsterSpecies.BABBLE),
        (MonsterSpecies.SLIME, MonsterSpecies.GIANTMOTH, MonsterSpecies.BABBLE),
        (MonsterSpecies.SLIME, MonsterSpecies.SPOOKY, MonsterSpecies.BABBLE),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.TREESLIME, MonsterSpecies.BOXSLIME),
        # Healer (row 11) - slime + pillowrat, funkybird, madplant, copycat
        (MonsterSpecies.SLIME, MonsterSpecies.PILLOWRAT, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.FUNKYBIRD, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.MADPLANT, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.COPYCAT, MonsterSpecies.HEALER),
        # FangSlime (row 12) - slime + almiraj, gulpbeast, trumpeter, kingleo, darkhorn, madcat
        (MonsterSpecies.SLIME, MonsterSpecies.ALMIRAJ, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.GULPBEAST, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.TRUMPETER, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.KINGLEO, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.DARKHORN, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.MADCAT, MonsterSpecies.FANGSLIME),
        # RockSlime (row 13) - slime + digster, deadnite, golem, stoneman, bombcrag
        (MonsterSpecies.SLIME, MonsterSpecies.DIGSTER, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.DEADNITE, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.GOLEM, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.STONEMAN, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BOMBCRAG, MonsterSpecies.ROCKSLIME),
        # SlimeBorg (row 14) - [drakslime,slimenite,rockslime,metabble] + [swordgon,spikerous,greatdrak,battlerex,skydragon]
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SPIKEROUS, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.GREATDRAK, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.BATTLEREX, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SKYDRAGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIMENITE, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.ROCKSLIME, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.METABBLE, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIME, MonsterSpecies.ROBOSTER, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIME, MonsterSpecies.SKULLROO, MonsterSpecies.SLABBIT),
        # SpotKing + any of [greatdrak, battlerex, ...] -> Kingslime (row 17 style)
        (MonsterSpecies.SPOTKING, MonsterSpecies.GREATDRAK, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.BATTLEREX, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.DIVINEGON, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.UNICORN, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.KINGLEO, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.MADCONDOR, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.ZAPBIRD, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.WHIPBIRD, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.GIGANTES, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.CENTASAUR, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.DEADNOBLE, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.WHITEKING, MonsterSpecies.KINGSLIME),
        # Kingslime + any of [greatdrak, battlerex, ...] -> SpotKing
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GREATDRAK, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.BATTLEREX, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.DIVINEGON, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.UNICORN, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.KINGLEO, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.MADCONDOR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.ZAPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.WHIPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GIGANTES, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.CENTASAUR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.DEADNOBLE, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.WHITEKING, MonsterSpecies.SPOTKING),
        # MetalKing + any of [greatdrak, battlerex, ...] -> SpotKing
        (MonsterSpecies.METALKING, MonsterSpecies.GREATDRAK, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.BATTLEREX, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.DIVINEGON, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.UNICORN, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.KINGLEO, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.MADCONDOR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.ZAPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.WHIPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.GIGANTES, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.CENTASAUR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.DEADNOBLE, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.WHITEKING, MonsterSpecies.SPOTKING),
        (MonsterSpecies.SPOTSLIME, MonsterSpecies.SPOTSLIME, MonsterSpecies.SPOTKING),
        (MonsterSpecies.SLIME, MonsterSpecies.SLIME, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.METALDRAK, MonsterSpecies.METALY),
        (MonsterSpecies.METALY, MonsterSpecies.METALY, MonsterSpecies.METABBLE),
        # MetalKing (row 24) - spotking or kingslime + metaldrak
        (MonsterSpecies.SPOTKING, MonsterSpecies.METALDRAK, MonsterSpecies.METALKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.METALDRAK, MonsterSpecies.METALKING),
        (MonsterSpecies.METABBLE, MonsterSpecies.METABBLE, MonsterSpecies.METALKING),
        # GoldSlime (row 26) - spotking, kingslime, or metalking + goldgolem
        (MonsterSpecies.SPOTKING, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.METALKING, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.METALKING, MonsterSpecies.METALKING, MonsterSpecies.GOLDSLIME),
    ],
    ids=[
        "slime_dragon",
        "slime_minidrak",
        "slime_tortragon",
        "boxslime_dragon",
        "drakslime_pteranod",
        "spotslime_andreal",
        "slime_anteater",
        "slime_catfly",
        "slime_wildape",
        "boxslime_grizzly",
        "wingslime_anteater",
        "slime_dracky",
        "slime_bullbird",
        "slime_phoenix",
        "treeslime_dracky",
        "snaily_bigroost",
        "slime_fireweed",
        "slime_amberweed",
        "slime_floraman",
        "drakslime_fireweed",
        "healer_cactiball",
        "slime_catapila",
        "slime_butterfly",
        "slime_armyant",
        "slimenite_catapila",
        "babble_hornbeet",
        "slime_demonite",
        "slime_arcdemon",
        "slime_agdevil",
        "boxslime_demonite",
        "rockslime_arcdemon",
        "slime_goldgolem",
        "slime_balzak",
        "slime_curselamp",
        "drakslime_goldgolem",
        "fangslime_evilpot",
        "slime_dracolord1",
        "slime_baramos",
        "slime_hargon",
        "boxslime_dracolord1",
        "healer_sidoh",
        "slime_poisongon",
        "slime_giantmoth",
        "slime_spooky",
        "boxslime_treeslime",
        "slime_pillowrat",
        "slime_funkybird",
        "slime_madplant",
        "slime_copycat",
        "slime_almiraj",
        "slime_gulpbeast",
        "slime_trumpeter",
        "slime_kingleo",
        "slime_darkhorn",
        "slime_madcat",
        "slime_digster",
        "slime_deadnite",
        "slime_golem",
        "slime_stoneman",
        "slime_bombcrag",
        "drakslime_swordgon",
        "drakslime_spikerous",
        "drakslime_greatdrak",
        "drakslime_battlerex",
        "drakslime_skydragon",
        "slimenite_swordgon",
        "rockslime_swordgon",
        "metabble_swordgon",
        "slime_roboster",
        "slime_skullroo",
        "spotking_greatdrak",
        "spotking_battlerex",
        "spotking_divinegon",
        "spotking_unicorn",
        "spotking_kingleo",
        "spotking_madcondor",
        "spotking_zapbird",
        "spotking_whipbird",
        "spotking_gigantes",
        "spotking_centasaur",
        "spotking_deadnoble",
        "spotking_whiteking",
        "kingslime_greatdrak",
        "kingslime_battlerex",
        "kingslime_divinegon",
        "kingslime_unicorn",
        "kingslime_kingleo",
        "kingslime_madcondor",
        "kingslime_zapbird",
        "kingslime_whipbird",
        "kingslime_gigantes",
        "kingslime_centasaur",
        "kingslime_deadnoble",
        "kingslime_whiteking",
        "metalking_greatdrak",
        "metalking_battlerex",
        "metalking_divinegon",
        "metalking_unicorn",
        "metalking_kingleo",
        "metalking_madcondor",
        "metalking_zapbird",
        "metalking_whipbird",
        "metalking_gigantes",
        "metalking_centasaur",
        "metalking_deadnoble",
        "metalking_whiteking",
        "spotslime_spotslime",
        "slime_slime",
        "slime_metaldrak",
        "metaly_metaly",
        "spotking_metaldrak",
        "kingslime_metaldrak",
        "metabble_metabble",
        "spotking_goldgolem",
        "kingslime_goldgolem",
        "metalking_goldgolem",
        "metalking_metalking",
    ],
)
def test_slime_breeding_combos(
    pedigree: Species,
    mate: Species,
    expected: Species,
) -> None:
    """Breeding pedigree + mate yields expected Slime result (per Rules sheet)."""
    result = get_breeding_result(pedigree=pedigree, mate=mate)
    assert result == expected


@pytest.mark.parametrize(
    ("pedigree", "mate", "expected"),
    [
        # Any Dragon + any Slime -> DragonKid
        (MonsterSpecies.DRAGON, MonsterSpecies.SLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.BOXSLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.HEALER, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.PTERANOD, MonsterSpecies.SPOTSLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.POISONGON, MonsterSpecies.SNAILY, MonsterSpecies.DRAGONKID),
        # Any Dragon + any Beast -> Tortragon
        (MonsterSpecies.DRAGON, MonsterSpecies.ANTEATER, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.GRIZZLY, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.CATFLY, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.SWORDGON, MonsterSpecies.WILDAPE, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.UNICORN, MonsterSpecies.GREATDRAK),
        # Any Dragon + any Bird -> Pteranod (Phoenix is mate for SkyDragon, not Pteranod)
        (MonsterSpecies.DRAGON, MonsterSpecies.DRACKY, MonsterSpecies.PTERANOD),
        (MonsterSpecies.DRAGON, MonsterSpecies.BULLBIRD, MonsterSpecies.PTERANOD),
        (MonsterSpecies.GASGON, MonsterSpecies.BULLBIRD, MonsterSpecies.PTERANOD),
        (MonsterSpecies.FAIRYDRAK, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        # Any Dragon + any Plant -> Gasgon
        (MonsterSpecies.DRAGON, MonsterSpecies.FIREWEED, MonsterSpecies.GASGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.FLORAMAN, MonsterSpecies.GASGON),
        (MonsterSpecies.PTERANOD, MonsterSpecies.AMBERWEED, MonsterSpecies.GASGON),
        (MonsterSpecies.POISONGON, MonsterSpecies.CACTIBALL, MonsterSpecies.GASGON),
        # Any Dragon + any Bug -> FairyDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.CATAPILA, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.DRAGON, MonsterSpecies.BUTTERFLY, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.HORNBEET, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.SWORDGON, MonsterSpecies.ARMYANT, MonsterSpecies.FAIRYDRAK),
        # Any Dragon + any Devil -> LizardMan
        (MonsterSpecies.DRAGON, MonsterSpecies.DEMONITE, MonsterSpecies.LIZARDMAN),
        (MonsterSpecies.DRAGON, MonsterSpecies.ARCDEMON, MonsterSpecies.LIZARDMAN),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.AGDEVIL, MonsterSpecies.LIZARDMAN),
        (MonsterSpecies.GASGON, MonsterSpecies.DEMONITE, MonsterSpecies.LIZARDMAN),
        # Any Dragon + any Zombie -> Poisongon
        (MonsterSpecies.DRAGON, MonsterSpecies.SPOOKY, MonsterSpecies.POISONGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.GIANTMOTH, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.PTERANOD, MonsterSpecies.SPOOKY, MonsterSpecies.POISONGON),
        # Any Dragon + any Material -> Swordgon
        (MonsterSpecies.DRAGON, MonsterSpecies.GOLDGOLEM, MonsterSpecies.SWORDGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.BALZAK, MonsterSpecies.SWORDGON),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.CURSELAMP, MonsterSpecies.SWORDGON),
        (MonsterSpecies.POISONGON, MonsterSpecies.EVILPOT, MonsterSpecies.SWORDGON),
        # DragonKid + DragonKid -> Dragon
        (MonsterSpecies.DRAGONKID, MonsterSpecies.DRAGONKID, MonsterSpecies.DRAGON),
        # Any Dragon + Picky -> MiniDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        (MonsterSpecies.PTERANOD, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        (MonsterSpecies.SWORDGON, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        # Any Dragon + GulpBeast -> MadDragon
        (MonsterSpecies.DRAGON, MonsterSpecies.GULPBEAST, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GULPBEAST, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.POISONGON, MonsterSpecies.GULPBEAST, MonsterSpecies.MADDRAGON),
        # Gasgon + any Beast -> MadDragon
        (MonsterSpecies.GASGON, MonsterSpecies.ANTEATER, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.GASGON, MonsterSpecies.GRIZZLY, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.GASGON, MonsterSpecies.MADCAT, MonsterSpecies.MADDRAGON),
        # Any Dragon + MadCondor -> Rayburn
        (MonsterSpecies.DRAGON, MonsterSpecies.MADCONDOR, MonsterSpecies.RAYBURN),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.MADCONDOR, MonsterSpecies.RAYBURN),
        (MonsterSpecies.SWORDGON, MonsterSpecies.MADCONDOR, MonsterSpecies.RAYBURN),
        # LizardMan + [Wingslime, Trumpeter, MadCat, FaceTree, Lionex, GoatHorn, GateGuard, Gigantes] -> Rayburn
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.WINGSLIME, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.TRUMPETER, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.MADCAT, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.FACETREE, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.LIONEX, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GOATHORN, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GATEGUARD, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GIGANTES, MonsterSpecies.RAYBURN),
        # Any Dragon + Voodoll -> Chamelgon
        (MonsterSpecies.DRAGON, MonsterSpecies.VOODOLL, MonsterSpecies.CHAMELGON),
        (MonsterSpecies.PTERANOD, MonsterSpecies.VOODOLL, MonsterSpecies.CHAMELGON),
        (MonsterSpecies.ANDREAL, MonsterSpecies.VOODOLL, MonsterSpecies.CHAMELGON),
        # Any Dragon + Gohopper -> LizardFly
        (MonsterSpecies.DRAGON, MonsterSpecies.GOHOPPER, MonsterSpecies.LIZARDFLY),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.GOHOPPER, MonsterSpecies.LIZARDFLY),
        (MonsterSpecies.FAIRYDRAK, MonsterSpecies.GOHOPPER, MonsterSpecies.LIZARDFLY),
        # Any Dragon + Gulpple -> Andreal
        (MonsterSpecies.DRAGON, MonsterSpecies.GULPPLE, MonsterSpecies.ANDREAL),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.GULPPLE, MonsterSpecies.ANDREAL),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.GULPPLE, MonsterSpecies.ANDREAL),
        # [Gasgon, MadDragon, BattleRex, SkyDragon] + [Goategon, Trumpeter, MadCondor, ...] -> Andreal
        (MonsterSpecies.GASGON, MonsterSpecies.GOATEGON, MonsterSpecies.ANDREAL),
        (MonsterSpecies.GASGON, MonsterSpecies.TRUMPETER, MonsterSpecies.ANDREAL),
        (MonsterSpecies.MADDRAGON, MonsterSpecies.MADCONDOR, MonsterSpecies.ANDREAL),
        (MonsterSpecies.MADDRAGON, MonsterSpecies.ARCDEMON, MonsterSpecies.ANDREAL),
        (MonsterSpecies.BATTLEREX, MonsterSpecies.LIONEX, MonsterSpecies.ANDREAL),
        (MonsterSpecies.BATTLEREX, MonsterSpecies.GOLEM, MonsterSpecies.ANDREAL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.FUNKYBIRD, MonsterSpecies.ANDREAL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.DEADNOBLE, MonsterSpecies.ANDREAL),
        # Any Dragon + Babble -> KingCobra
        (MonsterSpecies.DRAGON, MonsterSpecies.BABBLE, MonsterSpecies.KINGCOBRA),
        (MonsterSpecies.PTERANOD, MonsterSpecies.BABBLE, MonsterSpecies.KINGCOBRA),
        (MonsterSpecies.CHAMELGON, MonsterSpecies.BABBLE, MonsterSpecies.KINGCOBRA),
        # Any Dragon + [ArmyCrab, Digster] -> Spikerous
        (MonsterSpecies.DRAGON, MonsterSpecies.ARMYCRAB, MonsterSpecies.SPIKEROUS),
        (MonsterSpecies.DRAGON, MonsterSpecies.DIGSTER, MonsterSpecies.SPIKEROUS),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.ARMYCRAB, MonsterSpecies.SPIKEROUS),
        (MonsterSpecies.OROCHI, MonsterSpecies.DIGSTER, MonsterSpecies.SPIKEROUS),
        # DragonKid + DragonKid -> GreatDrak (note +4); Dragon + Dragon -> GreatDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.DRAGON, MonsterSpecies.GREATDRAK),
        # Any Dragon + [SpotKing, KingSlime, MetalKing, BattleRex, Unicorn, ...] -> GreatDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.SPOTKING, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.DRAGON, MonsterSpecies.KINGSLIME, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.DRAGON, MonsterSpecies.METALKING, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.BATTLEREX, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.PTERANOD, MonsterSpecies.UNICORN, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.GASGON, MonsterSpecies.ZAPBIRD, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.WHIPBIRD, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.RAYBURN, MonsterSpecies.GIGANTES, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.CRESTPENT, MonsterSpecies.CENTASAUR, MonsterSpecies.GREATDRAK),
        # Any Dragon + BigRoost -> Crestpent
        (MonsterSpecies.DRAGON, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        # Crestpent + Crestpent -> Wingsnake
        (MonsterSpecies.CRESTPENT, MonsterSpecies.CRESTPENT, MonsterSpecies.WINGSNAKE),
        # Wingsnake + Wingsnake -> Coatol
        (MonsterSpecies.WINGSNAKE, MonsterSpecies.WINGSNAKE, MonsterSpecies.COATOL),
        # [Pteranod, Gasgon, LizardMan, BattleRex, SkyDragon] + [DarkHorn, MadKnight, Copycat, Stoneman] -> Coatol
        (MonsterSpecies.PTERANOD, MonsterSpecies.DARKHORN, MonsterSpecies.COATOL),
        (MonsterSpecies.PTERANOD, MonsterSpecies.MADKNIGHT, MonsterSpecies.COATOL),
        (MonsterSpecies.GASGON, MonsterSpecies.COPYCAT, MonsterSpecies.COATOL),
        (MonsterSpecies.GASGON, MonsterSpecies.STONEMAN, MonsterSpecies.COATOL),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.DARKHORN, MonsterSpecies.COATOL),
        (MonsterSpecies.BATTLEREX, MonsterSpecies.COPYCAT, MonsterSpecies.COATOL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.MADKNIGHT, MonsterSpecies.COATOL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.STONEMAN, MonsterSpecies.COATOL),
        # Any Dragon + any Boss -> Orochi
        (MonsterSpecies.DRAGON, MonsterSpecies.DRACOLORD1, MonsterSpecies.OROCHI),
        (MonsterSpecies.DRAGON, MonsterSpecies.BARAMOS, MonsterSpecies.OROCHI),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.HARGON, MonsterSpecies.OROCHI),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.SIDOH, MonsterSpecies.OROCHI),
        # [Andreal, GreatDrak] + MedusaEye -> Orochi
        (MonsterSpecies.ANDREAL, MonsterSpecies.MEDUSAEYE, MonsterSpecies.OROCHI),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.MEDUSAEYE, MonsterSpecies.OROCHI),
        # Any Dragon + [KingLeo, Lionex, Ogre, MadKnight, EvilArmor] -> BattleRex
        (MonsterSpecies.DRAGON, MonsterSpecies.KINGLEO, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.LIONEX, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.OGRE, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.MADKNIGHT, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.EVILARMOR, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.PTERANOD, MonsterSpecies.KINGLEO, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.OROCHI, MonsterSpecies.LIONEX, MonsterSpecies.BATTLEREX),
        # Any Dragon + Phoenix -> SkyDragon
        (MonsterSpecies.DRAGON, MonsterSpecies.PHOENIX, MonsterSpecies.SKYDRAGON),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.PHOENIX, MonsterSpecies.SKYDRAGON),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.PHOENIX, MonsterSpecies.SKYDRAGON),
        # SkyDragon + Orochi -> Divinegon
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.OROCHI, MonsterSpecies.DIVINEGON),
    ],
    ids=[
        "dragon_slime",
        "dragon_drakslime",
        "minidrak_boxslime",
        "tortragon_healer",
        "pteranod_spotslime",
        "poisongon_snaily",
        "dragon_anteater",
        "dragon_grizzly",
        "minidrak_catfly",
        "swordgon_wildape",
        "lizardman_unicorn",
        "dragon_dracky",
        "dragon_bullbird",
        "gasgon_bullbird",
        "fairydrak_bigroost",
        "dragon_fireweed",
        "dragon_floraman",
        "pteranod_amberweed",
        "poisongon_cactiball",
        "dragon_catapila",
        "dragon_butterfly",
        "tortragon_hornbeet",
        "swordgon_armyant",
        "dragon_demonite",
        "dragon_arcdemon",
        "minidrak_agdevil",
        "gasgon_demonite",
        "dragon_spooky",
        "dragon_giantmoth",
        "pteranod_spooky",
        "dragon_goldgolem",
        "dragon_balzak",
        "lizardman_curselamp",
        "poisongon_evilpot",
        "dragonkid_dragonkid",
        "dragon_picky",
        "tortragon_picky",
        "pteranod_picky",
        "swordgon_picky",
        "dragon_gulpbeast",
        "lizardman_gulpbeast",
        "poisongon_gulpbeast",
        "gasgon_anteater",
        "gasgon_grizzly",
        "gasgon_madcat",
        "dragon_madcondor",
        "minidrak_madcondor",
        "swordgon_madcondor",
        "lizardman_wingslime",
        "lizardman_trumpeter",
        "lizardman_madcat",
        "lizardman_facetree",
        "lizardman_lionex",
        "lizardman_goathorn",
        "lizardman_gateguard",
        "lizardman_gigantes",
        "dragon_voodoll",
        "pteranod_voodoll",
        "andreal_voodoll",
        "dragon_gohopper",
        "tortragon_gohopper",
        "fairydrak_gohopper",
        "dragon_gulpple",
        "minidrak_gulpple",
        "greatdrak_gulpple",
        "gasgon_goategon",
        "gasgon_trumpeter",
        "maddragon_madcondor",
        "maddragon_arcdemon",
        "battlerex_lionex",
        "battlerex_golem",
        "skydragon_funkybird",
        "skydragon_deadnoble",
        "dragon_babble",
        "pteranod_babble",
        "chamelgon_babble",
        "dragon_armycrab",
        "dragon_digster",
        "lizardman_armycrab",
        "orochi_digster",
        "dragon_dragon",
        "dragon_spotking",
        "dragon_kingslime",
        "dragon_metalking",
        "minidrak_battlerex",
        "pteranod_unicorn",
        "gasgon_zapbird",
        "lizardman_whipbird",
        "rayburn_gigantes",
        "crestpent_centasaur",
        "dragon_bigroost",
        "tortragon_bigroost",
        "skydragon_bigroost",
        "crestpent_crestpent",
        "wingsnake_wingsnake",
        "pteranod_darkhorn",
        "pteranod_madknight",
        "gasgon_copycat",
        "gasgon_stoneman",
        "lizardman_darkhorn",
        "battlerex_copycat",
        "skydragon_madknight",
        "skydragon_stoneman",
        "dragon_dracolord1",
        "dragon_baramos",
        "minidrak_hargon",
        "greatdrak_sidoh",
        "andreal_medusaeye",
        "greatdrak_medusaeye",
        "dragon_kingleo",
        "dragon_lionex",
        "dragon_ogre",
        "dragon_madknight",
        "dragon_evilarmor",
        "pteranod_kingleo",
        "orochi_lionex",
        "dragon_phoenix",
        "minidrak_phoenix",
        "greatdrak_phoenix",
        "skydragon_orochi",
    ],
)
def test_dragon_breeding_combos(
    pedigree: Species,
    mate: Species,
    expected: Species,
) -> None:
    """
    All combos that result in a Dragon-class monster (Rules sheet Dragon section).

    Sheet is grouped by result class; every expected is Dragon family. Mates
    (e.g. Phoenix, KingLeo, Ogre, MedusaEye) appear only as the other parent.
    """
    result = get_breeding_result(pedigree=pedigree, mate=mate)
    assert result == expected
