"""
Tests for breeding.utils.

Slime and Dragon result combinations are derived from the Rules sheet
in monster_breeding.xlsx (reference document for game rules).

Class-based recipes (e.g. any Slime + any Dragon -> DrakSlime) are tested
with multiple pedigree/mate species. Species-specific recipes use one or more pairs each.
"""

import pytest

from breeding.utils import get_breeding_result
from monsters.constants import MonsterSpecies, Species


@pytest.mark.parametrize(
    ("pedigree", "mate", "expected"),
    [
        # Any Slime + any Dragon -> DrakSlime
        (MonsterSpecies.SLIME, MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.MINIDRAK, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.TORTRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.PTERANOD, MonsterSpecies.DRAKSLIME),
        (MonsterSpecies.SPOTSLIME, MonsterSpecies.ANDREAL, MonsterSpecies.DRAKSLIME),
        # Any Slime + any Beast -> Spotslime
        (MonsterSpecies.SLIME, MonsterSpecies.ANTEATER, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.CATFLY, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.WILDAPE, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.GRIZZLY, MonsterSpecies.SPOTSLIME),
        (MonsterSpecies.WINGSLIME, MonsterSpecies.ANTEATER, MonsterSpecies.SPOTSLIME),
        # Any Slime + any Bird -> Wingslime
        (MonsterSpecies.SLIME, MonsterSpecies.DRACKY, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BULLBIRD, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.PHOENIX, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.TREESLIME, MonsterSpecies.DRACKY, MonsterSpecies.WINGSLIME),
        (MonsterSpecies.SNAILY, MonsterSpecies.BIGROOST, MonsterSpecies.WINGSLIME),
        # Any Slime + any Plant -> Treeslime
        (MonsterSpecies.SLIME, MonsterSpecies.FIREWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.AMBERWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.FLORAMAN, MonsterSpecies.TREESLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.FIREWEED, MonsterSpecies.TREESLIME),
        (MonsterSpecies.HEALER, MonsterSpecies.CACTIBALL, MonsterSpecies.TREESLIME),
        # Any Slime + any Bug -> Snaily
        (MonsterSpecies.SLIME, MonsterSpecies.CATAPILA, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIME, MonsterSpecies.BUTTERFLY, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIME, MonsterSpecies.ARMYANT, MonsterSpecies.SNAILY),
        (MonsterSpecies.SLIMENITE, MonsterSpecies.CATAPILA, MonsterSpecies.SNAILY),
        (MonsterSpecies.BABBLE, MonsterSpecies.HORNBEET, MonsterSpecies.SNAILY),
        # Any Slime + any Devil -> SlimeNite
        (MonsterSpecies.SLIME, MonsterSpecies.DEMONITE, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.SLIME, MonsterSpecies.ARCDEMON, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.SLIME, MonsterSpecies.AGDEVIL, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DEMONITE, MonsterSpecies.SLIMENITE),
        (MonsterSpecies.ROCKSLIME, MonsterSpecies.ARCDEMON, MonsterSpecies.SLIMENITE),
        # Any Slime + any Material -> BoxSlime (mates that don't trigger other recipes)
        (MonsterSpecies.SLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BALZAK, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.CURSELAMP, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.BOXSLIME),
        (MonsterSpecies.FANGSLIME, MonsterSpecies.EVILPOT, MonsterSpecies.BOXSLIME),
        # Any Slime + any Boss -> Kingslime
        (MonsterSpecies.SLIME, MonsterSpecies.DRACOLORD1, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BARAMOS, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.HARGON, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.DRACOLORD1, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.HEALER, MonsterSpecies.SIDOH, MonsterSpecies.KINGSLIME),
        # Species-specific: Babble (row 8) - slime + poisongon, giantmoth, or zombie
        (MonsterSpecies.SLIME, MonsterSpecies.POISONGON, MonsterSpecies.BABBLE),
        (MonsterSpecies.SLIME, MonsterSpecies.GIANTMOTH, MonsterSpecies.BABBLE),
        (MonsterSpecies.SLIME, MonsterSpecies.SPOOKY, MonsterSpecies.BABBLE),
        (MonsterSpecies.BOXSLIME, MonsterSpecies.TREESLIME, MonsterSpecies.BOXSLIME),
        # Healer (row 11) - slime + pillowrat, funkybird, madplant, copycat
        (MonsterSpecies.SLIME, MonsterSpecies.PILLOWRAT, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.FUNKYBIRD, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.MADPLANT, MonsterSpecies.HEALER),
        (MonsterSpecies.SLIME, MonsterSpecies.COPYCAT, MonsterSpecies.HEALER),
        # FangSlime (row 12) - slime + almiraj, gulpbeast, trumpeter, kingleo, darkhorn, madcat
        (MonsterSpecies.SLIME, MonsterSpecies.ALMIRAJ, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.GULPBEAST, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.TRUMPETER, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.KINGLEO, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.DARKHORN, MonsterSpecies.FANGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.MADCAT, MonsterSpecies.FANGSLIME),
        # RockSlime (row 13) - slime + digster, deadnite, golem, stoneman, bombcrag
        (MonsterSpecies.SLIME, MonsterSpecies.DIGSTER, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.DEADNITE, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.GOLEM, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.STONEMAN, MonsterSpecies.ROCKSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.BOMBCRAG, MonsterSpecies.ROCKSLIME),
        # SlimeBorg (row 14) - [drakslime,slimenite,rockslime,metabble] + [swordgon,spikerous,greatdrak,battlerex,skydragon]
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SPIKEROUS, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.GREATDRAK, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.BATTLEREX, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.DRAKSLIME, MonsterSpecies.SKYDRAGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIMENITE, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.ROCKSLIME, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.METABBLE, MonsterSpecies.SWORDGON, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIME, MonsterSpecies.ROBOSTER, MonsterSpecies.SLIMEBORG),
        (MonsterSpecies.SLIME, MonsterSpecies.SKULLROO, MonsterSpecies.SLABBIT),
        # SpotKing + any of [greatdrak, battlerex, ...] -> Kingslime (row 17 style)
        (MonsterSpecies.SPOTKING, MonsterSpecies.GREATDRAK, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.BATTLEREX, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.DIVINEGON, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.UNICORN, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.KINGLEO, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.MADCONDOR, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.ZAPBIRD, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.WHIPBIRD, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.GIGANTES, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.CENTASAUR, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.DEADNOBLE, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SPOTKING, MonsterSpecies.WHITEKING, MonsterSpecies.KINGSLIME),
        # Kingslime + any of [greatdrak, battlerex, ...] -> SpotKing
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GREATDRAK, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.BATTLEREX, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.DIVINEGON, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.UNICORN, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.KINGLEO, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.MADCONDOR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.ZAPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.WHIPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GIGANTES, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.CENTASAUR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.DEADNOBLE, MonsterSpecies.SPOTKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.WHITEKING, MonsterSpecies.SPOTKING),
        # MetalKing + any of [greatdrak, battlerex, ...] -> SpotKing
        (MonsterSpecies.METALKING, MonsterSpecies.GREATDRAK, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.BATTLEREX, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.DIVINEGON, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.UNICORN, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.KINGLEO, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.MADCONDOR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.ZAPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.WHIPBIRD, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.GIGANTES, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.CENTASAUR, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.DEADNOBLE, MonsterSpecies.SPOTKING),
        (MonsterSpecies.METALKING, MonsterSpecies.WHITEKING, MonsterSpecies.SPOTKING),
        (MonsterSpecies.SPOTSLIME, MonsterSpecies.SPOTSLIME, MonsterSpecies.SPOTKING),
        (MonsterSpecies.SLIME, MonsterSpecies.SLIME, MonsterSpecies.KINGSLIME),
        (MonsterSpecies.SLIME, MonsterSpecies.METALDRAK, MonsterSpecies.METALY),
        (MonsterSpecies.METALY, MonsterSpecies.METALY, MonsterSpecies.METABBLE),
        # MetalKing (row 24) - spotking or kingslime + metaldrak
        (MonsterSpecies.SPOTKING, MonsterSpecies.METALDRAK, MonsterSpecies.METALKING),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.METALDRAK, MonsterSpecies.METALKING),
        (MonsterSpecies.METABBLE, MonsterSpecies.METABBLE, MonsterSpecies.METALKING),
        # GoldSlime (row 26) - spotking, kingslime, or metalking + goldgolem
        (MonsterSpecies.SPOTKING, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.KINGSLIME, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.METALKING, MonsterSpecies.GOLDGOLEM, MonsterSpecies.GOLDSLIME),
        (MonsterSpecies.METALKING, MonsterSpecies.METALKING, MonsterSpecies.GOLDSLIME),
    ],
    ids=[
        "slime_dragon",
        "slime_minidrak",
        "slime_tortragon",
        "boxslime_dragon",
        "drakslime_pteranod",
        "spotslime_andreal",
        "slime_anteater",
        "slime_catfly",
        "slime_wildape",
        "boxslime_grizzly",
        "wingslime_anteater",
        "slime_dracky",
        "slime_bullbird",
        "slime_phoenix",
        "treeslime_dracky",
        "snaily_bigroost",
        "slime_fireweed",
        "slime_amberweed",
        "slime_floraman",
        "drakslime_fireweed",
        "healer_cactiball",
        "slime_catapila",
        "slime_butterfly",
        "slime_armyant",
        "slimenite_catapila",
        "babble_hornbeet",
        "slime_demonite",
        "slime_arcdemon",
        "slime_agdevil",
        "boxslime_demonite",
        "rockslime_arcdemon",
        "slime_goldgolem",
        "slime_balzak",
        "slime_curselamp",
        "drakslime_goldgolem",
        "fangslime_evilpot",
        "slime_dracolord1",
        "slime_baramos",
        "slime_hargon",
        "boxslime_dracolord1",
        "healer_sidoh",
        "slime_poisongon",
        "slime_giantmoth",
        "slime_spooky",
        "boxslime_treeslime",
        "slime_pillowrat",
        "slime_funkybird",
        "slime_madplant",
        "slime_copycat",
        "slime_almiraj",
        "slime_gulpbeast",
        "slime_trumpeter",
        "slime_kingleo",
        "slime_darkhorn",
        "slime_madcat",
        "slime_digster",
        "slime_deadnite",
        "slime_golem",
        "slime_stoneman",
        "slime_bombcrag",
        "drakslime_swordgon",
        "drakslime_spikerous",
        "drakslime_greatdrak",
        "drakslime_battlerex",
        "drakslime_skydragon",
        "slimenite_swordgon",
        "rockslime_swordgon",
        "metabble_swordgon",
        "slime_roboster",
        "slime_skullroo",
        "spotking_greatdrak",
        "spotking_battlerex",
        "spotking_divinegon",
        "spotking_unicorn",
        "spotking_kingleo",
        "spotking_madcondor",
        "spotking_zapbird",
        "spotking_whipbird",
        "spotking_gigantes",
        "spotking_centasaur",
        "spotking_deadnoble",
        "spotking_whiteking",
        "kingslime_greatdrak",
        "kingslime_battlerex",
        "kingslime_divinegon",
        "kingslime_unicorn",
        "kingslime_kingleo",
        "kingslime_madcondor",
        "kingslime_zapbird",
        "kingslime_whipbird",
        "kingslime_gigantes",
        "kingslime_centasaur",
        "kingslime_deadnoble",
        "kingslime_whiteking",
        "metalking_greatdrak",
        "metalking_battlerex",
        "metalking_divinegon",
        "metalking_unicorn",
        "metalking_kingleo",
        "metalking_madcondor",
        "metalking_zapbird",
        "metalking_whipbird",
        "metalking_gigantes",
        "metalking_centasaur",
        "metalking_deadnoble",
        "metalking_whiteking",
        "spotslime_spotslime",
        "slime_slime",
        "slime_metaldrak",
        "metaly_metaly",
        "spotking_metaldrak",
        "kingslime_metaldrak",
        "metabble_metabble",
        "spotking_goldgolem",
        "kingslime_goldgolem",
        "metalking_goldgolem",
        "metalking_metalking",
    ],
)
def test_slime_breeding_combos(
    pedigree: Species,
    mate: Species,
    expected: Species,
) -> None:
    """Breeding pedigree + mate yields expected Slime result (per Rules sheet)."""
    result = get_breeding_result(pedigree=pedigree, mate=mate)
    assert result == expected


@pytest.mark.parametrize(
    ("pedigree", "mate", "expected"),
    [
        # Any Dragon + any Slime -> DragonKid
        (MonsterSpecies.DRAGON, MonsterSpecies.SLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.DRAGON, MonsterSpecies.DRAKSLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.BOXSLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.HEALER, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.PTERANOD, MonsterSpecies.SPOTSLIME, MonsterSpecies.DRAGONKID),
        (MonsterSpecies.POISONGON, MonsterSpecies.SNAILY, MonsterSpecies.DRAGONKID),
        # Any Dragon + any Beast -> Tortragon
        (MonsterSpecies.DRAGON, MonsterSpecies.ANTEATER, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.GRIZZLY, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.CATFLY, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.SWORDGON, MonsterSpecies.WILDAPE, MonsterSpecies.TORTRAGON),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.UNICORN, MonsterSpecies.GREATDRAK),
        # Any Dragon + any Bird -> Pteranod (Phoenix is mate for SkyDragon, not Pteranod)
        (MonsterSpecies.DRAGON, MonsterSpecies.DRACKY, MonsterSpecies.PTERANOD),
        (MonsterSpecies.DRAGON, MonsterSpecies.BULLBIRD, MonsterSpecies.PTERANOD),
        (MonsterSpecies.GASGON, MonsterSpecies.BULLBIRD, MonsterSpecies.PTERANOD),
        (MonsterSpecies.FAIRYDRAK, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        # Any Dragon + any Plant -> Gasgon
        (MonsterSpecies.DRAGON, MonsterSpecies.FIREWEED, MonsterSpecies.GASGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.FLORAMAN, MonsterSpecies.GASGON),
        (MonsterSpecies.PTERANOD, MonsterSpecies.AMBERWEED, MonsterSpecies.GASGON),
        (MonsterSpecies.POISONGON, MonsterSpecies.CACTIBALL, MonsterSpecies.GASGON),
        # Any Dragon + any Bug -> FairyDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.CATAPILA, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.DRAGON, MonsterSpecies.BUTTERFLY, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.HORNBEET, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.SWORDGON, MonsterSpecies.ARMYANT, MonsterSpecies.FAIRYDRAK),
        # Any Dragon + any Devil -> LizardMan
        (MonsterSpecies.DRAGON, MonsterSpecies.DEMONITE, MonsterSpecies.LIZARDMAN),
        (MonsterSpecies.DRAGON, MonsterSpecies.ARCDEMON, MonsterSpecies.LIZARDMAN),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.AGDEVIL, MonsterSpecies.LIZARDMAN),
        (MonsterSpecies.GASGON, MonsterSpecies.DEMONITE, MonsterSpecies.LIZARDMAN),
        # Any Dragon + any Zombie -> Poisongon
        (MonsterSpecies.DRAGON, MonsterSpecies.SPOOKY, MonsterSpecies.POISONGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.GIANTMOTH, MonsterSpecies.FAIRYDRAK),
        (MonsterSpecies.PTERANOD, MonsterSpecies.SPOOKY, MonsterSpecies.POISONGON),
        # Any Dragon + any Material -> Swordgon
        (MonsterSpecies.DRAGON, MonsterSpecies.GOLDGOLEM, MonsterSpecies.SWORDGON),
        (MonsterSpecies.DRAGON, MonsterSpecies.BALZAK, MonsterSpecies.SWORDGON),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.CURSELAMP, MonsterSpecies.SWORDGON),
        (MonsterSpecies.POISONGON, MonsterSpecies.EVILPOT, MonsterSpecies.SWORDGON),
        # DragonKid + DragonKid -> Dragon
        (MonsterSpecies.DRAGONKID, MonsterSpecies.DRAGONKID, MonsterSpecies.DRAGON),
        # Any Dragon + Picky -> MiniDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        (MonsterSpecies.PTERANOD, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        (MonsterSpecies.SWORDGON, MonsterSpecies.PICKY, MonsterSpecies.MINIDRAK),
        # Any Dragon + GulpBeast -> MadDragon
        (MonsterSpecies.DRAGON, MonsterSpecies.GULPBEAST, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GULPBEAST, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.POISONGON, MonsterSpecies.GULPBEAST, MonsterSpecies.MADDRAGON),
        # Gasgon + any Beast -> MadDragon
        (MonsterSpecies.GASGON, MonsterSpecies.ANTEATER, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.GASGON, MonsterSpecies.GRIZZLY, MonsterSpecies.MADDRAGON),
        (MonsterSpecies.GASGON, MonsterSpecies.MADCAT, MonsterSpecies.MADDRAGON),
        # Any Dragon + MadCondor -> Rayburn
        (MonsterSpecies.DRAGON, MonsterSpecies.MADCONDOR, MonsterSpecies.RAYBURN),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.MADCONDOR, MonsterSpecies.RAYBURN),
        (MonsterSpecies.SWORDGON, MonsterSpecies.MADCONDOR, MonsterSpecies.RAYBURN),
        # LizardMan + [Wingslime, Trumpeter, MadCat, FaceTree, Lionex, GoatHorn, GateGuard, Gigantes] -> Rayburn
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.WINGSLIME, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.TRUMPETER, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.MADCAT, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.FACETREE, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.LIONEX, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GOATHORN, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GATEGUARD, MonsterSpecies.RAYBURN),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.GIGANTES, MonsterSpecies.RAYBURN),
        # Any Dragon + Voodoll -> Chamelgon
        (MonsterSpecies.DRAGON, MonsterSpecies.VOODOLL, MonsterSpecies.CHAMELGON),
        (MonsterSpecies.PTERANOD, MonsterSpecies.VOODOLL, MonsterSpecies.CHAMELGON),
        (MonsterSpecies.ANDREAL, MonsterSpecies.VOODOLL, MonsterSpecies.CHAMELGON),
        # Any Dragon + Gohopper -> LizardFly
        (MonsterSpecies.DRAGON, MonsterSpecies.GOHOPPER, MonsterSpecies.LIZARDFLY),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.GOHOPPER, MonsterSpecies.LIZARDFLY),
        (MonsterSpecies.FAIRYDRAK, MonsterSpecies.GOHOPPER, MonsterSpecies.LIZARDFLY),
        # Any Dragon + Gulpple -> Andreal
        (MonsterSpecies.DRAGON, MonsterSpecies.GULPPLE, MonsterSpecies.ANDREAL),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.GULPPLE, MonsterSpecies.ANDREAL),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.GULPPLE, MonsterSpecies.ANDREAL),
        # [Gasgon, MadDragon, BattleRex, SkyDragon] + [Goategon, Trumpeter, MadCondor, ...] -> Andreal
        (MonsterSpecies.GASGON, MonsterSpecies.GOATEGON, MonsterSpecies.ANDREAL),
        (MonsterSpecies.GASGON, MonsterSpecies.TRUMPETER, MonsterSpecies.ANDREAL),
        (MonsterSpecies.MADDRAGON, MonsterSpecies.MADCONDOR, MonsterSpecies.ANDREAL),
        (MonsterSpecies.MADDRAGON, MonsterSpecies.ARCDEMON, MonsterSpecies.ANDREAL),
        (MonsterSpecies.BATTLEREX, MonsterSpecies.LIONEX, MonsterSpecies.ANDREAL),
        (MonsterSpecies.BATTLEREX, MonsterSpecies.GOLEM, MonsterSpecies.ANDREAL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.FUNKYBIRD, MonsterSpecies.ANDREAL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.DEADNOBLE, MonsterSpecies.ANDREAL),
        # Any Dragon + Babble -> KingCobra
        (MonsterSpecies.DRAGON, MonsterSpecies.BABBLE, MonsterSpecies.KINGCOBRA),
        (MonsterSpecies.PTERANOD, MonsterSpecies.BABBLE, MonsterSpecies.KINGCOBRA),
        (MonsterSpecies.CHAMELGON, MonsterSpecies.BABBLE, MonsterSpecies.KINGCOBRA),
        # Any Dragon + [ArmyCrab, Digster] -> Spikerous
        (MonsterSpecies.DRAGON, MonsterSpecies.ARMYCRAB, MonsterSpecies.SPIKEROUS),
        (MonsterSpecies.DRAGON, MonsterSpecies.DIGSTER, MonsterSpecies.SPIKEROUS),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.ARMYCRAB, MonsterSpecies.SPIKEROUS),
        (MonsterSpecies.OROCHI, MonsterSpecies.DIGSTER, MonsterSpecies.SPIKEROUS),
        # DragonKid + DragonKid -> GreatDrak (note +4); Dragon + Dragon -> GreatDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.DRAGON, MonsterSpecies.GREATDRAK),
        # Any Dragon + [SpotKing, KingSlime, MetalKing, BattleRex, Unicorn, ...] -> GreatDrak
        (MonsterSpecies.DRAGON, MonsterSpecies.SPOTKING, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.DRAGON, MonsterSpecies.KINGSLIME, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.DRAGON, MonsterSpecies.METALKING, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.BATTLEREX, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.PTERANOD, MonsterSpecies.UNICORN, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.GASGON, MonsterSpecies.ZAPBIRD, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.WHIPBIRD, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.RAYBURN, MonsterSpecies.GIGANTES, MonsterSpecies.GREATDRAK),
        (MonsterSpecies.CRESTPENT, MonsterSpecies.CENTASAUR, MonsterSpecies.GREATDRAK),
        # Any Dragon + BigRoost -> Crestpent
        (MonsterSpecies.DRAGON, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        (MonsterSpecies.TORTRAGON, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.BIGROOST, MonsterSpecies.CRESTPENT),
        # Crestpent + Crestpent -> Wingsnake
        (MonsterSpecies.CRESTPENT, MonsterSpecies.CRESTPENT, MonsterSpecies.WINGSNAKE),
        # Wingsnake + Wingsnake -> Coatol
        (MonsterSpecies.WINGSNAKE, MonsterSpecies.WINGSNAKE, MonsterSpecies.COATOL),
        # [Pteranod, Gasgon, LizardMan, BattleRex, SkyDragon] + [DarkHorn, MadKnight, Copycat, Stoneman] -> Coatol
        (MonsterSpecies.PTERANOD, MonsterSpecies.DARKHORN, MonsterSpecies.COATOL),
        (MonsterSpecies.PTERANOD, MonsterSpecies.MADKNIGHT, MonsterSpecies.COATOL),
        (MonsterSpecies.GASGON, MonsterSpecies.COPYCAT, MonsterSpecies.COATOL),
        (MonsterSpecies.GASGON, MonsterSpecies.STONEMAN, MonsterSpecies.COATOL),
        (MonsterSpecies.LIZARDMAN, MonsterSpecies.DARKHORN, MonsterSpecies.COATOL),
        (MonsterSpecies.BATTLEREX, MonsterSpecies.COPYCAT, MonsterSpecies.COATOL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.MADKNIGHT, MonsterSpecies.COATOL),
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.STONEMAN, MonsterSpecies.COATOL),
        # Any Dragon + any Boss -> Orochi
        (MonsterSpecies.DRAGON, MonsterSpecies.DRACOLORD1, MonsterSpecies.OROCHI),
        (MonsterSpecies.DRAGON, MonsterSpecies.BARAMOS, MonsterSpecies.OROCHI),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.HARGON, MonsterSpecies.OROCHI),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.SIDOH, MonsterSpecies.OROCHI),
        # [Andreal, GreatDrak] + MedusaEye -> Orochi
        (MonsterSpecies.ANDREAL, MonsterSpecies.MEDUSAEYE, MonsterSpecies.OROCHI),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.MEDUSAEYE, MonsterSpecies.OROCHI),
        # Any Dragon + [KingLeo, Lionex, Ogre, MadKnight, EvilArmor] -> BattleRex
        (MonsterSpecies.DRAGON, MonsterSpecies.KINGLEO, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.LIONEX, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.OGRE, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.MADKNIGHT, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.DRAGON, MonsterSpecies.EVILARMOR, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.PTERANOD, MonsterSpecies.KINGLEO, MonsterSpecies.BATTLEREX),
        (MonsterSpecies.OROCHI, MonsterSpecies.LIONEX, MonsterSpecies.BATTLEREX),
        # Any Dragon + Phoenix -> SkyDragon
        (MonsterSpecies.DRAGON, MonsterSpecies.PHOENIX, MonsterSpecies.SKYDRAGON),
        (MonsterSpecies.MINIDRAK, MonsterSpecies.PHOENIX, MonsterSpecies.SKYDRAGON),
        (MonsterSpecies.GREATDRAK, MonsterSpecies.PHOENIX, MonsterSpecies.SKYDRAGON),
        # SkyDragon + Orochi -> Divinegon
        (MonsterSpecies.SKYDRAGON, MonsterSpecies.OROCHI, MonsterSpecies.DIVINEGON),
    ],
    ids=[
        "dragon_slime",
        "dragon_drakslime",
        "minidrak_boxslime",
        "tortragon_healer",
        "pteranod_spotslime",
        "poisongon_snaily",
        "dragon_anteater",
        "dragon_grizzly",
        "minidrak_catfly",
        "swordgon_wildape",
        "lizardman_unicorn",
        "dragon_dracky",
        "dragon_bullbird",
        "gasgon_bullbird",
        "fairydrak_bigroost",
        "dragon_fireweed",
        "dragon_floraman",
        "pteranod_amberweed",
        "poisongon_cactiball",
        "dragon_catapila",
        "dragon_butterfly",
        "tortragon_hornbeet",
        "swordgon_armyant",
        "dragon_demonite",
        "dragon_arcdemon",
        "minidrak_agdevil",
        "gasgon_demonite",
        "dragon_spooky",
        "dragon_giantmoth",
        "pteranod_spooky",
        "dragon_goldgolem",
        "dragon_balzak",
        "lizardman_curselamp",
        "poisongon_evilpot",
        "dragonkid_dragonkid",
        "dragon_picky",
        "tortragon_picky",
        "pteranod_picky",
        "swordgon_picky",
        "dragon_gulpbeast",
        "lizardman_gulpbeast",
        "poisongon_gulpbeast",
        "gasgon_anteater",
        "gasgon_grizzly",
        "gasgon_madcat",
        "dragon_madcondor",
        "minidrak_madcondor",
        "swordgon_madcondor",
        "lizardman_wingslime",
        "lizardman_trumpeter",
        "lizardman_madcat",
        "lizardman_facetree",
        "lizardman_lionex",
        "lizardman_goathorn",
        "lizardman_gateguard",
        "lizardman_gigantes",
        "dragon_voodoll",
        "pteranod_voodoll",
        "andreal_voodoll",
        "dragon_gohopper",
        "tortragon_gohopper",
        "fairydrak_gohopper",
        "dragon_gulpple",
        "minidrak_gulpple",
        "greatdrak_gulpple",
        "gasgon_goategon",
        "gasgon_trumpeter",
        "maddragon_madcondor",
        "maddragon_arcdemon",
        "battlerex_lionex",
        "battlerex_golem",
        "skydragon_funkybird",
        "skydragon_deadnoble",
        "dragon_babble",
        "pteranod_babble",
        "chamelgon_babble",
        "dragon_armycrab",
        "dragon_digster",
        "lizardman_armycrab",
        "orochi_digster",
        "dragon_dragon",
        "dragon_spotking",
        "dragon_kingslime",
        "dragon_metalking",
        "minidrak_battlerex",
        "pteranod_unicorn",
        "gasgon_zapbird",
        "lizardman_whipbird",
        "rayburn_gigantes",
        "crestpent_centasaur",
        "dragon_bigroost",
        "tortragon_bigroost",
        "skydragon_bigroost",
        "crestpent_crestpent",
        "wingsnake_wingsnake",
        "pteranod_darkhorn",
        "pteranod_madknight",
        "gasgon_copycat",
        "gasgon_stoneman",
        "lizardman_darkhorn",
        "battlerex_copycat",
        "skydragon_madknight",
        "skydragon_stoneman",
        "dragon_dracolord1",
        "dragon_baramos",
        "minidrak_hargon",
        "greatdrak_sidoh",
        "andreal_medusaeye",
        "greatdrak_medusaeye",
        "dragon_kingleo",
        "dragon_lionex",
        "dragon_ogre",
        "dragon_madknight",
        "dragon_evilarmor",
        "pteranod_kingleo",
        "orochi_lionex",
        "dragon_phoenix",
        "minidrak_phoenix",
        "greatdrak_phoenix",
        "skydragon_orochi",
    ],
)
def test_dragon_breeding_combos(
    pedigree: Species,
    mate: Species,
    expected: Species,
) -> None:
    """
    All combos that result in a Dragon-class monster (Rules sheet Dragon section).

    Sheet is grouped by result class; every expected is Dragon family. Mates
    (e.g. Phoenix, KingLeo, Ogre, MedusaEye) appear only as the other parent.
    """
    result = get_breeding_result(pedigree=pedigree, mate=mate)
    assert result == expected


@pytest.mark.parametrize(
    ("pedigree", "mate", "expected"),
    [
        # Any Beast + any Slime -> Tonguella (avoid Beast+DrakSlime/LizardMan -> Goategon)
        (MonsterSpecies.ANTEATER, MonsterSpecies.SLIME, MonsterSpecies.TONGUELLA),
        (MonsterSpecies.SKULLROO, MonsterSpecies.SLIME, MonsterSpecies.TONGUELLA),
        (MonsterSpecies.MADCAT, MonsterSpecies.BOXSLIME, MonsterSpecies.TONGUELLA),
        (MonsterSpecies.UNICORN, MonsterSpecies.HEALER, MonsterSpecies.TONGUELLA),
        (MonsterSpecies.CATFLY, MonsterSpecies.SPOTSLIME, MonsterSpecies.TONGUELLA),
        # Any Beast + any Dragon -> Almiraj (avoid Grizzly/Trumpeter/WildApe + Dragon -> GulpBeast/Yeti)
        (MonsterSpecies.ANTEATER, MonsterSpecies.DRAGON, MonsterSpecies.ALMIRAJ),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.MINIDRAK, MonsterSpecies.ALMIRAJ),
        (MonsterSpecies.CATFLY, MonsterSpecies.DRAGON, MonsterSpecies.ALMIRAJ),
        (MonsterSpecies.CATFLY, MonsterSpecies.PTERANOD, MonsterSpecies.ALMIRAJ),
        (MonsterSpecies.SKULLROO, MonsterSpecies.SWORDGON, MonsterSpecies.ALMIRAJ),
        # Any Beast + any Bird -> CatFly
        (MonsterSpecies.ANTEATER, MonsterSpecies.DRACKY, MonsterSpecies.CATFLY),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.BULLBIRD, MonsterSpecies.CATFLY),
        (MonsterSpecies.UNICORN, MonsterSpecies.PHOENIX, MonsterSpecies.CATFLY),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.BIGROOST, MonsterSpecies.CATFLY),
        (MonsterSpecies.SACCER, MonsterSpecies.DRACKY, MonsterSpecies.CATFLY),
        # Any Beast + any Plant -> PillowRat
        (MonsterSpecies.ANTEATER, MonsterSpecies.FIREWEED, MonsterSpecies.PILLOWRAT),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.FLORAMAN, MonsterSpecies.PILLOWRAT),
        (MonsterSpecies.CATFLY, MonsterSpecies.CACTIBALL, MonsterSpecies.PILLOWRAT),
        (MonsterSpecies.WILDAPE, MonsterSpecies.AMBERWEED, MonsterSpecies.PILLOWRAT),
        (MonsterSpecies.SKULLROO, MonsterSpecies.FIREWEED, MonsterSpecies.PILLOWRAT),
        # Any Beast + any Bug -> Saccer
        (MonsterSpecies.ANTEATER, MonsterSpecies.CATAPILA, MonsterSpecies.SACCER),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.BUTTERFLY, MonsterSpecies.SACCER),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.ARMYANT, MonsterSpecies.SACCER),
        (MonsterSpecies.CATFLY, MonsterSpecies.HORNBEET, MonsterSpecies.SACCER),
        (MonsterSpecies.UNICORN, MonsterSpecies.GIANTMOTH, MonsterSpecies.SACCER),
        # Grizzly + any Devil -> GulpBeast
        (MonsterSpecies.GRIZZLY, MonsterSpecies.DEMONITE, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.ARCDEMON, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.AGDEVIL, MonsterSpecies.GULPBEAST),
        # Any Beast + any Zombie -> Skullroo
        (MonsterSpecies.ANTEATER, MonsterSpecies.SPOOKY, MonsterSpecies.SKULLROO),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.SPOOKY, MonsterSpecies.SKULLROO),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.SPOOKY, MonsterSpecies.SKULLROO),
        (MonsterSpecies.CATFLY, MonsterSpecies.SPOOKY, MonsterSpecies.SKULLROO),
        # Any Beast + any Material -> WindBeast
        (MonsterSpecies.ANTEATER, MonsterSpecies.GOLDGOLEM, MonsterSpecies.WINDBEAST),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.BALZAK, MonsterSpecies.WINDBEAST),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.CURSELAMP, MonsterSpecies.WINDBEAST),
        (MonsterSpecies.CATFLY, MonsterSpecies.EVILPOT, MonsterSpecies.WINDBEAST),
        (MonsterSpecies.SACCER, MonsterSpecies.GOLDGOLEM, MonsterSpecies.WINDBEAST),
        # CatFly + any Bird -> WindBeast
        (MonsterSpecies.CATFLY, MonsterSpecies.DRACKY, MonsterSpecies.WINDBEAST),
        (MonsterSpecies.CATFLY, MonsterSpecies.BULLBIRD, MonsterSpecies.WINDBEAST),
        (MonsterSpecies.CATFLY, MonsterSpecies.BIGROOST, MonsterSpecies.WINDBEAST),
        # Saccer + any Dragon -> Anteater
        (MonsterSpecies.SACCER, MonsterSpecies.DRAGON, MonsterSpecies.ANTEATER),
        (MonsterSpecies.SACCER, MonsterSpecies.MINIDRAK, MonsterSpecies.ANTEATER),
        (MonsterSpecies.SACCER, MonsterSpecies.TORTRAGON, MonsterSpecies.ANTEATER),
        (MonsterSpecies.SACCER, MonsterSpecies.PTERANOD, MonsterSpecies.ANTEATER),
        # Any Beast + Mudron -> SuperTen
        (MonsterSpecies.ANTEATER, MonsterSpecies.MUDRON, MonsterSpecies.SUPERTEN),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.MUDRON, MonsterSpecies.SUPERTEN),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.MUDRON, MonsterSpecies.SUPERTEN),
        (MonsterSpecies.CATFLY, MonsterSpecies.MUDRON, MonsterSpecies.SUPERTEN),
        # Tonguella or GulpBeast + [Treeslime, FangSlime, ...] -> SuperTen
        (MonsterSpecies.TONGUELLA, MonsterSpecies.TREESLIME, MonsterSpecies.SUPERTEN),
        (MonsterSpecies.TONGUELLA, MonsterSpecies.FANGSLIME, MonsterSpecies.SUPERTEN),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.MADDRAGON, MonsterSpecies.SUPERTEN),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.FUNKYBIRD, MonsterSpecies.SUPERTEN),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.COPYCAT, MonsterSpecies.SUPERTEN),
        # Any Beast + Tortragon -> IronTurt (avoid Grizzly+Dragon -> GulpBeast)
        (MonsterSpecies.ANTEATER, MonsterSpecies.TORTRAGON, MonsterSpecies.IRONTURT),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.TORTRAGON, MonsterSpecies.IRONTURT),
        (MonsterSpecies.CATFLY, MonsterSpecies.TORTRAGON, MonsterSpecies.IRONTURT),
        (MonsterSpecies.SKULLROO, MonsterSpecies.TORTRAGON, MonsterSpecies.IRONTURT),
        # Any Beast + DuckKite -> Mommonja
        (MonsterSpecies.ANTEATER, MonsterSpecies.DUCKKITE, MonsterSpecies.MOMMONJA),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.DUCKKITE, MonsterSpecies.MOMMONJA),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.DUCKKITE, MonsterSpecies.MOMMONJA),
        # Any Beast + StubSuck -> HammerMan
        (MonsterSpecies.ANTEATER, MonsterSpecies.STUBSUCK, MonsterSpecies.HAMMERMAN),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.STUBSUCK, MonsterSpecies.HAMMERMAN),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.STUBSUCK, MonsterSpecies.HAMMERMAN),
        # Any Beast + SabreMan -> MadGopher
        (MonsterSpecies.ANTEATER, MonsterSpecies.SABREMAN, MonsterSpecies.MADGOPHER),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.SABREMAN, MonsterSpecies.MADGOPHER),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.SABREMAN, MonsterSpecies.MADGOPHER),
        # Any Beast + LizardFly -> FairyRat (avoid Grizzly+... -> GulpBeast)
        (MonsterSpecies.ANTEATER, MonsterSpecies.LIZARDFLY, MonsterSpecies.FAIRYRAT),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.LIZARDFLY, MonsterSpecies.FAIRYRAT),
        (MonsterSpecies.CATFLY, MonsterSpecies.LIZARDFLY, MonsterSpecies.FAIRYRAT),
        # Any Beast + FangSlime -> Unicorn
        (MonsterSpecies.ANTEATER, MonsterSpecies.FANGSLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.FANGSLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.FANGSLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.CATFLY, MonsterSpecies.FANGSLIME, MonsterSpecies.UNICORN),
        # Any Beast + MadPecker -> WildApe
        (MonsterSpecies.ANTEATER, MonsterSpecies.MADPECKER, MonsterSpecies.WILDAPE),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.MADPECKER, MonsterSpecies.WILDAPE),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.MADPECKER, MonsterSpecies.WILDAPE),
        # Almiraj + any Dragon -> WildApe
        (MonsterSpecies.ALMIRAJ, MonsterSpecies.DRAGON, MonsterSpecies.WILDAPE),
        (MonsterSpecies.ALMIRAJ, MonsterSpecies.MINIDRAK, MonsterSpecies.WILDAPE),
        (MonsterSpecies.ALMIRAJ, MonsterSpecies.SWORDGON, MonsterSpecies.WILDAPE),
        # WildApe + WildApe -> Trumpeter
        (MonsterSpecies.WILDAPE, MonsterSpecies.WILDAPE, MonsterSpecies.TRUMPETER),
        # SuperTen + any Dragon -> Trumpeter
        (MonsterSpecies.SUPERTEN, MonsterSpecies.DRAGON, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.SUPERTEN, MonsterSpecies.MINIDRAK, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.SUPERTEN, MonsterSpecies.PTERANOD, MonsterSpecies.TRUMPETER),
        # Any Beast + any Boss -> DarkHorn
        (MonsterSpecies.ANTEATER, MonsterSpecies.DRACOLORD1, MonsterSpecies.DARKHORN),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.BARAMOS, MonsterSpecies.DARKHORN),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.HARGON, MonsterSpecies.DARKHORN),
        (MonsterSpecies.UNICORN, MonsterSpecies.SIDOH, MonsterSpecies.DARKHORN),
        # Any Beast + Eyeball -> BigEye (avoid Grizzly+Devil -> GulpBeast)
        (MonsterSpecies.ANTEATER, MonsterSpecies.EYEBALL, MonsterSpecies.BIGEYE),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.EYEBALL, MonsterSpecies.BIGEYE),
        (MonsterSpecies.CATFLY, MonsterSpecies.EYEBALL, MonsterSpecies.BIGEYE),
        # Any Beast + Orc -> Yeti (avoid Grizzly+Devil -> GulpBeast)
        (MonsterSpecies.ANTEATER, MonsterSpecies.ORC, MonsterSpecies.YETI),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.ORC, MonsterSpecies.YETI),
        (MonsterSpecies.CATFLY, MonsterSpecies.ORC, MonsterSpecies.YETI),
        (MonsterSpecies.SKULLROO, MonsterSpecies.ORC, MonsterSpecies.YETI),
        # Any Beast + DrakSlime or LizardMan -> Goategon (Beast+Slime gives Tonguella, so only LizardMan here)
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.LIZARDMAN, MonsterSpecies.GOATEGON),
        (MonsterSpecies.CATFLY, MonsterSpecies.LIZARDMAN, MonsterSpecies.GOATEGON),
        # Beast + [Devil, MetalDrak, ...] -> Grizzly (use only pairs that don't match GulpBeast)
        (MonsterSpecies.ANTEATER, MonsterSpecies.DEMONITE, MonsterSpecies.GRIZZLY),
        (MonsterSpecies.PILLOWRAT, MonsterSpecies.ARCDEMON, MonsterSpecies.GRIZZLY),
        (MonsterSpecies.CATFLY, MonsterSpecies.METALDRAK, MonsterSpecies.GRIZZLY),
        (MonsterSpecies.SACCER, MonsterSpecies.ROBOSTER, MonsterSpecies.GRIZZLY),
        (MonsterSpecies.SKULLROO, MonsterSpecies.GOLEM, MonsterSpecies.GRIZZLY),
        (MonsterSpecies.MADGOPHER, MonsterSpecies.STONEMAN, MonsterSpecies.GRIZZLY),
        # [Ironturt, Goategon, WildApe, MadCat] + [Pteranod, Gasgon, ...] -> Yeti
        (MonsterSpecies.IRONTURT, MonsterSpecies.PTERANOD, MonsterSpecies.YETI),
        (MonsterSpecies.IRONTURT, MonsterSpecies.GASGON, MonsterSpecies.YETI),
        (MonsterSpecies.GOATEGON, MonsterSpecies.SWORDGON, MonsterSpecies.YETI),
        (MonsterSpecies.WILDAPE, MonsterSpecies.MADDRAGON, MonsterSpecies.YETI),
        (MonsterSpecies.MADCAT, MonsterSpecies.BATTLEREX, MonsterSpecies.YETI),
        (MonsterSpecies.MADCAT, MonsterSpecies.SKYDRAGON, MonsterSpecies.YETI),
        # [Tonguella, GulpBeast, Grizzly, ...] + Slime -> Unicorn
        (MonsterSpecies.TONGUELLA, MonsterSpecies.SLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.SLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.SLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.YETI, MonsterSpecies.SLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.GOATEGON, MonsterSpecies.SLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.WILDAPE, MonsterSpecies.DRAKSLIME, MonsterSpecies.UNICORN),
        (MonsterSpecies.TRUMPETER, MonsterSpecies.BOXSLIME, MonsterSpecies.UNICORN),
        # GulpBeast + [MetalDrak, Balzak, ...] -> Trumpeter
        (MonsterSpecies.GULPBEAST, MonsterSpecies.METALDRAK, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.BALZAK, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.ROBOSTER, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.LAVAMAN, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.ICEMAN, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.GOLEM, MonsterSpecies.TRUMPETER),
        (MonsterSpecies.GULPBEAST, MonsterSpecies.STONEMAN, MonsterSpecies.TRUMPETER),
        # Trumpeter + [Trumpeter, MetalDrak, Balzak, GoldGolem] -> KingLeo
        (MonsterSpecies.TRUMPETER, MonsterSpecies.TRUMPETER, MonsterSpecies.KINGLEO),
        (MonsterSpecies.TRUMPETER, MonsterSpecies.METALDRAK, MonsterSpecies.KINGLEO),
        (MonsterSpecies.TRUMPETER, MonsterSpecies.BALZAK, MonsterSpecies.KINGLEO),
        (MonsterSpecies.TRUMPETER, MonsterSpecies.GOLDGOLEM, MonsterSpecies.KINGLEO),
        # Roboster + [GulpBeast, SuperTen, Unicorn, ...] -> KingLeo
        (MonsterSpecies.ROBOSTER, MonsterSpecies.GULPBEAST, MonsterSpecies.KINGLEO),
        (MonsterSpecies.ROBOSTER, MonsterSpecies.SUPERTEN, MonsterSpecies.KINGLEO),
        (MonsterSpecies.ROBOSTER, MonsterSpecies.UNICORN, MonsterSpecies.KINGLEO),
        (MonsterSpecies.ROBOSTER, MonsterSpecies.TRUMPETER, MonsterSpecies.KINGLEO),
        (MonsterSpecies.ROBOSTER, MonsterSpecies.DARKHORN, MonsterSpecies.KINGLEO),
        (MonsterSpecies.ROBOSTER, MonsterSpecies.MADCAT, MonsterSpecies.KINGLEO),
        # [Tonguella, Grizzly, Yeti, ...] + [Digster, Skullgon, ...] -> GulpBeast
        (MonsterSpecies.TONGUELLA, MonsterSpecies.DIGSTER, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.SKULLGON, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.YETI, MonsterSpecies.DEADNOBLE, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.UNICORN, MonsterSpecies.WHITEKING, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.WILDAPE, MonsterSpecies.SKELETOR, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.TRUMPETER, MonsterSpecies.DIGSTER, MonsterSpecies.GULPBEAST),
        # [Grizzly, Yeti, Trumpeter, BigEye] + Dragon -> GulpBeast
        (MonsterSpecies.GRIZZLY, MonsterSpecies.DRAGON, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.YETI, MonsterSpecies.MINIDRAK, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.TRUMPETER, MonsterSpecies.PTERANOD, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.BIGEYE, MonsterSpecies.SWORDGON, MonsterSpecies.GULPBEAST),
        # [Ironturt, Grizzly, Yeti, Unicorn, Goategon, WildApe] + [MetalDrak, ...] -> GulpBeast
        (MonsterSpecies.IRONTURT, MonsterSpecies.METALDRAK, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.GRIZZLY, MonsterSpecies.ROBOSTER, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.YETI, MonsterSpecies.LAVAMAN, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.UNICORN, MonsterSpecies.ICEMAN, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.GOATEGON, MonsterSpecies.GOLEM, MonsterSpecies.GULPBEAST),
        (MonsterSpecies.WILDAPE, MonsterSpecies.STONEMAN, MonsterSpecies.GULPBEAST),
    ],
    ids=[
        "anteater_slime",
        "skullroo_slime",
        "madcat_boxslime",
        "unicorn_healer",
        "catfly_spotslime",
        "anteater_dragon",
        "pillowrat_minidrak",
        "catfly_dragon",
        "catfly_pteranod",
        "skullroo_swordgon",
        "anteater_dracky",
        "grizzly_bullbird",
        "unicorn_phoenix",
        "pillowrat_bigroost",
        "saccer_dracky",
        "anteater_fireweed",
        "grizzly_floraman",
        "catfly_cactiball",
        "wildape_amberweed",
        "skullroo_fireweed",
        "anteater_catapila",
        "grizzly_butterfly",
        "pillowrat_armyant",
        "catfly_hornbeet",
        "unicorn_giantmoth",
        "grizzly_demonite",
        "grizzly_arcdemon",
        "grizzly_agdevil",
        "anteater_spooky",
        "grizzly_spooky",
        "pillowrat_spooky",
        "catfly_spooky",
        "anteater_goldgolem",
        "grizzly_balzak",
        "pillowrat_curselamp",
        "catfly_evilpot",
        "saccer_goldgolem",
        "catfly_dracky",
        "catfly_bullbird",
        "catfly_bigroost",
        "saccer_dragon",
        "saccer_minidrak",
        "saccer_tortragon",
        "saccer_pteranod",
        "anteater_mudron",
        "grizzly_mudron",
        "pillowrat_mudron",
        "catfly_mudron",
        "tonguella_treeslime",
        "tonguella_fangslime",
        "gulpbeast_maddragon",
        "gulpbeast_funkybird",
        "gulpbeast_copycat",
        "anteater_tortragon",
        "pillowrat_tortragon",
        "catfly_tortragon",
        "skullroo_tortragon",
        "anteater_duckkite",
        "grizzly_duckkite",
        "pillowrat_duckkite",
        "anteater_stubsuck",
        "grizzly_stubsuck",
        "pillowrat_stubsuck",
        "anteater_sabreman",
        "grizzly_sabreman",
        "pillowrat_sabreman",
        "anteater_lizardfly",
        "pillowrat_lizardfly",
        "catfly_lizardfly",
        "anteater_fangslime",
        "grizzly_fangslime",
        "pillowrat_fangslime",
        "catfly_fangslime",
        "anteater_madpecker",
        "grizzly_madpecker",
        "pillowrat_madpecker",
        "almiraj_dragon",
        "almiraj_minidrak",
        "almiraj_swordgon",
        "wildape_wildape",
        "superten_dragon",
        "superten_minidrak",
        "superten_pteranod",
        "anteater_dracolord1",
        "grizzly_baramos",
        "pillowrat_hargon",
        "unicorn_sidoh",
        "anteater_eyeball",
        "pillowrat_eyeball",
        "catfly_eyeball",
        "anteater_orc",
        "pillowrat_orc",
        "catfly_orc",
        "skullroo_orc",
        "pillowrat_lizardman",
        "catfly_lizardman",
        "anteater_demonite",
        "pillowrat_arcdemon",
        "catfly_metaldrak",
        "saccer_roboster",
        "skullroo_golem",
        "madgopher_stoneman",
        "ironturt_pteranod",
        "ironturt_gasgon",
        "goategon_swordgon",
        "wildape_maddragon",
        "madcat_battlerex",
        "madcat_skydragon",
        "tonguella_slime",
        "gulpbeast_slime",
        "grizzly_slime",
        "yeti_slime",
        "goategon_slime",
        "wildape_drakslime",
        "trumpeter_boxslime",
        "gulpbeast_metaldrak",
        "gulpbeast_balzak",
        "gulpbeast_roboster",
        "gulpbeast_lavaman",
        "gulpbeast_iceman",
        "gulpbeast_golem",
        "gulpbeast_stoneman",
        "trumpeter_trumpeter",
        "trumpeter_metaldrak",
        "trumpeter_balzak",
        "trumpeter_goldgolem",
        "roboster_gulpbeast",
        "roboster_superten",
        "roboster_unicorn",
        "roboster_trumpeter",
        "roboster_darkhorn",
        "roboster_madcat",
        "tonguella_digster",
        "grizzly_skullgon",
        "yeti_deadnoble",
        "unicorn_whiteking",
        "wildape_skeletor",
        "trumpeter_digster",
        "grizzly_dragon",
        "yeti_minidrak",
        "trumpeter_pteranod",
        "bigeye_swordgon",
        "ironturt_metaldrak",
        "grizzly_roboster",
        "yeti_lavaman",
        "unicorn_iceman",
        "goategon_golem",
        "wildape_stoneman",
    ],
)
def test_beast_breeding_combos(
    pedigree: Species,
    mate: Species,
    expected: Species,
) -> None:
    """
    All combos that result in a Beast-class monster (Rules sheet Beast section).

    Every expected is Beast family. Mates from other families appear only as the second argument.
    """
    result = get_breeding_result(pedigree=pedigree, mate=mate)
    assert result == expected
